### ISSUE TITLE
Support HTML print

### ISSUE THREAD

**Issue by GoldenZero** [mike42/escpos-php#10]
Dose this lib support printing HTML, else could you add this feature

Thank you,

**Comment by mike42** [comment]
Hello,

No, this feature is not currently available. My suggestions would be:
- If you have a specific piece of HTML to print, paste it here and I'll step you through the conversion.
- There are libraries which convert a web-page into an image, and the library supports images on many printers.
- I have seen a library designed for converting HTML to ESC/pos on Github.

I previously considered writing something to map basic HTML to escpos-php calls, because PHP programmers often end up with HTML. However modern HTML is basically un-styled, mooting the usefulness of the feature (ie, no HTML4 parser will be added).

Its more likely that Ill implement something like this down the road if I have some more information about your use case:
- Is a program generating the HTML? Does it come with a stylesheet? Is it a full document, or just a snippet? What is its character encoding?
- What features do you think this type of output needs most of all? (Take a look at README.md and think about which functions you would need if you could only use 1/3 of them)
- Do you have any examples of markup which you would attempt to print today if the feature was available?

**Comment by mike42** [comment]
Hi,

I've added an example which involves rendering the page with [wkhtmltopdf](http://wkhtmltopdf.org/) and then printing with the normal `bitImage()` method. See commit 3e55f15dfb820a79dddd6fffad9e5f3cfd0da8e8

I wont be making any changes to the code to support HTML in text-form at this stage (patches welcome), so if the speed, quality or printer support means that you can't use raster images, you'll simply need to ask `escpos-php` to format the receipt via the existing command-set.
