### ISSUE TITLE
“web-based point-of-sale (POS) applications” - How?

### ISSUE THREAD

**Issue by c-myers1** [mike42/escpos-php#1001]
With respect to “... support for receipt printing to any PHP app, including web-based point-of-sale (POS) applications,”: how exactly is this achieved with escpos-php (for a Linux server php app to print on a local windows printer?) Is this automatic with smb set up?

**Comment by c-myers1** [comment]
Ok, a pretty vexed issue as described in this [FAQ](https://github.com/mike42/escpos-php/blob/development/doc/FAQ.md).

**Comment by mutiemule** [comment]
Printing on local will work well with this package.

However, to print online, you will need to develop a desktop service which has to be installed on the local computer where you need printing to be done.  This is because PHP is a server-side scripting language, so once you put this online, it won't be able to communicate to the local printer. Thus, you need a client service running on the local machine and this is where electron js and node js come into play.

I resolved this by developing an electron js service based on [node-escpos package](https://www.npmjs.com/package/escpos) which can receive commands from the online print command and then communicate those commands to the printer through USB. 

Operating System does not matter in this case, you can be hosting on Linux based server and printing on a windows server. This desktop service interfaces between the online service and the local service. 

You can check out the [node-escpos printer driver package ](https://github.com/song940/node-escpos) for some inspiration on how to go about this.

Check the [FAQs on how to print online](https://github.com/mike42/escpos-php/blob/development/doc/FAQ.md) to have some pointers too.
