### ISSUE TITLE
XML(HTML) formated ESC/POS commands

### ISSUE THREAD

**Issue by tjunussov** [mike42/escpos-php#102]
Great job! It would be great if there was XML(HTML) formating like styling of receipts
I saw this Python Library https://github.com/fvdsn/py-xml-escpos

**Comment by mike42** [comment]
Interesting feature. That repo appears to be a fork of [python-escpos](https://github.com/python-escpos) (which I've also been working on), with an added `def receipt(self,xml)` method.

Currently, the best way to print HTML in escpos-php is to rasterise your page via `wkhtmltoimage` (see [example/print-from-html.php](https://github.com/mike42/escpos-php/blob/master/example/print-from-html.php)). There is a major speed improvement coming up for image handling which will make this much more viable, and I may build it into a command (Linux users only).

I'll leave this open as a request to add support for specifying receipts as text (markup in a custom HTML-like schema, which outputs native ESC/POS commands) This would presumably be a wrapper around the `Printer` class.

**Comment by tjunussov** [comment]
Don't you think raster image would be blurry against native fonts ( ESC/POS styling ) ?
especialy on small font sizes.
p.s Thanks for advice, I will try it

**Comment by mike42** [comment]
I think that print speed is a bigger concern with this technique (it's really quite slow at the moment), but you're correct, the native fonts are cleaner.

With `wkhtmltoimage`, you get *all* of HTML, so as long as your printer supports high-density output, you can always compensate for this by adjusting the face, size and anti-aliasing parameters via CSS.

To get a feel for it, you don't really need a printer. I render pages at ~576 pixels wide (widest I can print on my TM-T20), and convert them via the `pbm` format, which is pure black & white.

--
````
wkhtmltoimage --width 576 https://en.m.wikipedia.org/wiki/Champion_\(apple\) apple.png
convert apple.png apple.pbm
convert apple.pbm apple.png
````

Which looks like-

![apple](https://cloud.githubusercontent.com/assets/2080552/14065305/0744b72e-f470-11e5-87aa-79e5ecd13dda.png)

--

Or the included example, which doesn't look bad on 80mm paper IMO-

````
wkhtmltoimage --width 576 example/resources/document.html document.png                                                         
convert document.png document.pbm
convert document.pbm document.png
````

![document](https://cloud.githubusercontent.com/assets/2080552/14065340/5889f3aa-f471-11e5-9702-1ba68227e942.png)

**Comment by mike42** [comment]
Closing this off after much thought about whether this fits into the roadmap for `escpos-php`.

Generally there are two ways to do this:

- **Full HTML** needs to be converted to an image, which is best done with an external tool. This project (plus some other dedicated tools) can already print image files pretty well.
- **More limited XML or HTML-like data** could be rendered to ESC/POS. Nobody has mentioned it on the issue tracker, but this would be most useful in the context of data interchange between products (such as a template engine in a POS tool posting data to a PHP agent). Eg, it would be neat to store receipt templates with base64-encoded images right in your database.

Data interchange formats are great, and I would like to see a good ecosystem of tools for open source printing, but we are not a format converter. I also don't see value in creating a format that only our library understands when we have plenty of existing scope (read: bugs) just as a library of PHP functions which generates output for receipt printers.

I would be happy to call out any suitably licensed projects in the FAQ if they can XML to ESC/POS using this (or another) library to a fill the use case for XML printing if one exists, so that another project can act as a separately-maintained abstraction.

On the other hand, if an upstream project develops a suitable open source thermal-printer-specific XSD for data interchange, then I would be open to pull requests that implement it here as well, because compatibility is good!

Hope this explains why I'm closing this!

**Comment by alex071995** [comment]
Regards

I think you should implement something like this repository https://github.com/miracle2k/py-xml-escpos, convert from xml to esc / pos and that way html from html to image and with the image and use that image as a preview.
