### ISSUE TITLE
Error communicating with Network printer via Web Application

### ISSUE THREAD

**Issue by theoremanand** [mike42/escpos-php#1058]
Dear All,

We have developed a web application using PHP and using mike42 Network Printing class to print the invoice.
The printer at the store is setup with a static IP and a port.

When we run the application via a localhost (Different Networks. Both the client and printer are in different networks. Just that the application is deployed locally using WAMP SERVER) the application works fine and we are getting the print.
When we deploy the application in hostinger server and access it via a website, the print does not come and shows up a error that Could not connect to the printer.

We have checked all the dependency and everything is matching.
Is there a way to know what is wrong ? or anything at Hostinger which is blocking the issue ? or does your class need any other extensions to communicate with the local IP address via port ?

Regards,
Anand

**Comment by samuelT2** [comment]
Just out of interest - how does your web application know to which IP it needs to print? I assume your printer has a static IP assigned, which is reachable from outside of the network?
In our case, a Raspberry Pi, which is in the same network as the printer, calls a slim framework web service, parses and prints the response.

**Comment by Vallevard** [comment]
Hi, I think it's because your application is somewhere in the world and the application is trying to print in that server which does not have a printer.
We did the same think as @samuelT2 said, in our case we have a local app, in the web app we send the information to print to localhost:8081 (where the local app is running) the local app receive that information and send that information to the printer.

Your remote app does not have a direct access to the printer because are in diferents networks.
I thinks it's posible but you need to configure the printer to access to the internet so the remote app could access to the ip of the printer (something like that).

**Comment by theoremanand** [comment]
Guys, yes I understand the process. My printer has a static IP assigned which can be access from the world. The Static IP is set in my web application so it can directly send the print instruction to the printer via 9001 port.

**Comment by samuelT2** [comment]
Port forwarding on the destination router is setup?

**Comment by theoremanand** [comment]
Yes, the port is open. I am able to generate a print from different network only when I run the webapp in localhoat via wampserver.

Example: Printer is installed at my customer place in a different town and I am at my home. Through my localhoat wamp server, I can send a print command to status ip and it prints successfully.

Only when I am hosted the application on hostinger and GoDaddy cloud, I am unable to receive any command. Upon testing ping through php, I am getting the connection refused and timeout errors. 

Is there any dependency of any extension ? I don't know what is stopping my command to reach the Ip.

Hoatinger is saying everything is ok at there end and it's my ISP issue.

Isp is saying port is open and they are able to print it so it's not there fault.

**Comment by samuelT2** [comment]
Are you making use of INTL and CURL extensions? Are both extensions installed/activated within your host service? If so, I assume your hoster is somehow restricting direct IP access (as you're able to print to the printer from localhost, the network and setup from the printer looks fine).

**Comment by jevevargas** [comment]
buenas tardes, yo tengo problemas tambien al imprimir en red, y mis impresoras son TMU950 estan conectadas con puerto serial

**Comment by mike42** [comment]
Assuming you are using `NetworkPrintConnector`, this library will simply do a TCP connection to the IP and port that you ask for. [Here is the code](https://github.com/mike42/escpos-php/blob/f414320fc510afcacd4cbb75902f827399dee429/src/Mike42/Escpos/PrintConnectors/NetworkPrintConnector.php#L35).

The next troubleshooting step would be to log on to the server, then test connectivity from **outside of PHP** (use a command-line tool such as `netcat`, or something similar for the `NetworkPrintConnector`). Assuming that you get the same result, you could then debug this as a network problem, not a PHP problem.

I find it easiest to run the actual printing code on a server on the same LAN as the printer. If I needed to run an app off-premises, then I would set up a secure tunnel from a device on-premises to the server (VPN or SSH) so that the applications on that server could see the printers without too much trouble.

**Comment by tecnoher** [comment]
Hi, I solved it throw dyndns, I set up my DNS as IP on the network connection string, and in the network router I did a forward from port 9100 to the thermal printer IP.
Hope this helps some

**Comment by mutiemule** [comment]
Printing on local will work well with this package.

However, to print online, you will need to develop a desktop service which has to be installed on the local computer where you need printing to be done.  This is because PHP is a server-side scripting language, so once you put this online, it won't be able to communicate to the local printer. Thus, you need a client service running on the local machine and this is where electron js and node js come into play.

I resolved this by developing an electron js service based on [node-escpos package](https://www.npmjs.com/package/escpos) which can receive commands from the online print command and then communicate those commands to the printer through USB. 

Operating System does not matter in this case, you can be hosting on Linux based server and printing on a windows server. This desktop service interfaces between the online service and the local service. 

You can check out the [node-escpos printer driver package ](https://github.com/song940/node-escpos) for some inspiration on how to go about this.

**Comment by warmwhisky** [comment]
> Printing on local will work well with this package.
> 
> However, to print online, you will need to develop a desktop service which has to be installed on the local computer where you need printing to be done. This is because PHP is a server-side scripting language, so once you put this online, it won't be able to communicate to the local printer. Thus, you need a client service running on the local machine and this is where electron js and node js come into play.
> 
> I resolved this by developing an electron js service based on [node-escpos package](https://www.npmjs.com/package/escpos) which can receive commands from the online print command and then communicate those commands to the printer through USB.
> 
> Operating System does not matter in this case, you can be hosting on Linux based server and printing on a windows server. This desktop service interfaces between the online service and the local service.
> 
> You can check out the [node-escpos printer driver package ](https://github.com/song940/node-escpos) for some inspiration on how to go about this.

Is your electron js service available?

**Comment by mutiemule** [comment]
Yes, how can I assist?

-- 
Solutech is a limited liability company registered under the laws of the 
Republic of Kenya with registration number​ CPR/2014/171968.​​ 
​The 
content of this email is confidential and intended for the recipient(s) 
specified in this message only. It is strictly forbidden to share any part 
of this message with any third party, without written consent from me. 
Please consider the environment before printing this email.

**Comment by warmwhisky** [comment]
> Yes, how can I assist?

How can I print from a web app?

**Comment by mutiemule** [comment]
What I developed might not work exactly for you since I heavily customized it to fit our needs.

I borrowed heavily from this package: https://github.com/mike42/escpos-php
And this package as well: https://www.npmjs.com/package/escpos

Also, borrow heavily from this: https://github.com/share424/escpos-server
