### ISSUE TITLE
how to comunicate with a USB printer in clients-side

### ISSUE THREAD

**Issue by IanStratico** [mike42/escpos-php#1059]
First thaks for this library, is so usefull.

Now i have a web application runnig on Xampp that prints a recipt with a php script usig this library, the printer where prints the recipt is connected by usb. But now i want to use the pc that is running Xampp as a server an connect 2 Pc to it and run the Web Application that i made. The problem is that i dont know how to communicate with the printers that are conected by usb in the clients-side pc. Because when i run my Web Application in the clients-side pc the recipt is print on the printer that is conected to the server

**Comment by mike42** [comment]
This is not directly possible from server-side PHP. You need an agent running on the client to forward the print job, so performing this task is outside the scope of `escpos-php`.

This library can interface with CUPS shared printers, Windows shared printers, and Ethernet printers. If you can convert your USB printer into one of these, and understand how to make it visible to the PHP server over the network reliably/safely, then you this hardware it still suitable.

This will be much easier if the PHP printing process is on the same LAN as the printers.

**Comment by mutiemule** [comment]
Printing on local will work well with this package.

However, to print online, you will need to develop a desktop service which has to be installed on the local computer where you need printing to be done.  This is because PHP is a server-side scripting language, so once you put this online, it won't be able to communicate to the local printer. Thus, you need a client service running on the local machine and this is where electron js and node js come into play.

I resolved this by developing an electron js service based on [node-escpos package](https://www.npmjs.com/package/escpos) which can receive commands from the online print command and then communicate those commands to the printer through USB. 

Operating System does not matter in this case, you can be hosting on Linux based server and printing on a windows server. This desktop service interfaces between the online service and the local service. 

You can check out the [node-escpos printer driver package ](https://github.com/song940/node-escpos) for some inspiration on how to go about this.
