### ISSUE TITLE
Remote server, local printer

### ISSUE THREAD

**Issue by lovetoast** [mike42/escpos-php#108]
HI!

Great script! However, let's say I have local printer, via ethernet, and I access a website hosted remotely, how can I print to the local printer? Would I need to open the port? Is there not a way to access it through html/JS?

**Comment by lovetoast** [comment]
I should have perhaps read the rest of the forum, sorry!

**Comment by mutiemule** [comment]
Printing on local will work well with this package.

However, to print online, you will need to develop a desktop service which has to be installed on the local computer where you need printing to be done.  This is because PHP is a server-side scripting language, so once you put this online, it won't be able to communicate to the local printer. Thus, you need a client service running on the local machine and this is where electron js and node js come into play.

I resolved this by developing an electron js service based on [node-escpos package](https://www.npmjs.com/package/escpos) which can receive commands from the online print command and then communicate those commands to the printer through USB. 

Operating System does not matter in this case, you can be hosting on Linux based server and printing on a windows server. This desktop service interfaces between the online service and the local service. 

You can check out the [node-escpos printer driver package ](https://github.com/song940/node-escpos) for some inspiration on how to go about this.

Check the [FAQs on how to print online](https://github.com/mike42/escpos-php/blob/fe9350e61fb5e38416ec6243873c37fa65f34eb5/doc/FAQ.md#can-i-print-from-my-server-on-the-internet) to have some pointers too.
