### ISSUE TITLE
Issue in priting from server

### ISSUE THREAD

**Issue by gau147** [mike42/escpos-php#128]
Hi,
I am just trying to print the page from website to local printer. 
Here is below link, when you open it shows the error Like printer connection error. 
http://jain.mdlski.com/doctor/seo/testprint

I have tried the following syntax, but does not work. 
//$connector = new WindowsPrintConnector("smb://jain.mdlski.com/COMPUTERNAME/Receipt Printer");
        //$connector = new WindowsPrintConnector("smb://Guest@computername/Receipt Printer");

```
    //$connector = new NetworkPrintConnector("173.254.28.25","80");
    //$connector = new NetworkPrintConnector("223.225.247.136");
    $connector = new WindowsPrintConnector("smb://gaurav:gaurav123@GAURAV-PC/Receipt Printer");
```

Can you please suggest the solution.

**Comment by gau147** [comment]
Hi 

I have also checked the 121 issue. https://github.com/mike42/escpos-php/issues/121
but don't get the solution.

**Comment by mike42** [comment]
#121 is not a solution, it just expands on the README: You need to test that you can send text to your printer on the command line before attempting to use this driver.

If you don't yet have a working command to send text to your printer, then you need to find yourself some printer/network support to get you there.

Once you have a working command to send text to your printer, the README will show you the rest, or you can post the command here on the issue tracker if you need some help finding the right `PrintConnector`.

**Comment by pakricard** [comment]
Hi: I'm at the same point (wanting to print locally from a remote web). Is it possible to write the receipt to a file (with all the ESC POS commands and then php just prints it via a silent printing add-on?

The idea would be to create a TXT file with the commands and text and send it to the printer. 
Makes it any sense?

Thanks.

**Comment by gau147** [comment]
Hi 

I will try to implement with TXT file and update you soon. Do you any reference of this.?

Thanks

**Comment by pakricard** [comment]
Hi:
I have no reference about it, the idea just crossed my mind as it's very simple to silent print with one browser add-on (https://addons.mozilla.org/en-US/firefox/addon/seamless-print/ as example), but to do that we need a file to send. That's the general idea, but devil lives in the details.

If we send a file to a ESC POS printer with commands in it, will it print correctly? If so, then should work. Brand new to ESC POS so no clue about it.

Thanks

**Comment by mutiemule** [comment]
Printing on local will work well with this package.

However, to print online, you will need to develop a desktop service which has to be installed on the local computer where you need printing to be done.  This is because PHP is a server-side scripting language, so once you put this online, it won't be able to communicate to the local printer. Thus, you need a client service running on the local machine and this is where electron js and node js come into play.

I resolved this by developing an electron js service based on [node-escpos package](https://www.npmjs.com/package/escpos) which can receive commands from the online print command and then communicate those commands to the printer through USB. 

Operating System does not matter in this case, you can be hosting on Linux based server and printing on a windows server. This desktop service interfaces between the online service and the local service. 

You can check out the [node-escpos printer driver package ](https://github.com/song940/node-escpos) for some inspiration on how to go about this.

Check the [FAQs on how to print online](https://github.com/mike42/escpos-php/blob/fe9350e61fb5e38416ec6243873c37fa65f34eb5/doc/FAQ.md#can-i-print-from-my-server-on-the-internet) to have some pointers too.
