### ISSUE TITLE
Epson FX, LX and LQ

### ISSUE THREAD

**Issue by ardumlao** [mike42/escpos-php#141]
Hi...!

I just wanna know how escpos-php works using Epson FX, LX and LQ.

Thanks and Regards.

**Comment by mike42** [comment]
Printers that users have found to work are listed [here](https://github.com/mike42/escpos-php/tree/688c9dff49bc8010b26d409e9a86c4cad025a1b3#printers), but there are no reports of Epson FX, LX and LQ models having been tested with this driver.

You would need to look at whether these printers understand ESC/POS to know whether this driver will be useful to you.

**Comment by kumiz2k** [comment]
Hi Mike42, 

Thanks for your library and i already test for Epson LX-310 and LQ-2180. But when i test printing a barcode, the output is only text. So just read the manual, when print barcode using ASCII Code : ESC+(+B. Can u explain using your function for direct ASCII Code ? Thanks 
For manual link : https://files.support.epson.com/pdf/lx300p/lx300pu1.pdf

**Comment by mike42** [comment]
The manual shows that the printer accepts ESC/P, rather than ESC/POS (different protocol). They have a lot in common, but you are likely to encounter compatibility issues on the more advanced stuff.

I'm not currently treating ESC/P as in-scope for this driver, but I'm open to reviewing any pull requests which improve output for you printer without breaking the main use case (ESC/POS receipt printers).

I've written up an example in the linked commit which shows how to send raw data using `$printer -> getPrintConnector -> write()`. Another option is to extend the `Printer` class, and just override anything that doesn't work.
