### ISSUE TITLE
PHP Warning:  fread() expects parameter 1 to be resource, boolean given when calling getPrinterStatus()

### ISSUE THREAD

**Issue by nitinsbuzz** [mike42/escpos-php#151]
OS: Windows 10

If a network printer is inaccessible or unreachable, the following error is repeated numerous times when getPrinterStatus() is called. It causes the server to hang for a while. Maybe an idea to check if the file handler is not false and then continue the code or throw an exception and return so that the server does not hang. 

`PHP Warning:  fread() expects parameter 1 to be resource, boolean given in C:\...\vendor\mike42\escpos-php\src\Mike42\Escpos\PrintConnectors\FilePrintConnector.php on line 62`

until the max execution time

`PHP Fatal error:  Maximum execution time of 360 seconds exceeded`

```
 $connector = new NetworkPrintConnector("192.x.x.x", 9100);

 $printer = new Printer($connector);
 $printer -> text("Hello World!\n");
 $printer -> cut();
 $printer -> close();

 $printer -> getPrinterStatus();
```

**Comment by mike42** [comment]
Looks like a bug. I would expect this to throw an exception from the connector instead of hanging. Should be a simple fix in the `NetworkPrintConnector` class.

As an aside, I haven't seen `getPrinterStatus()` work on any printers, and is most likely going to be removed in a future release. It crashes my TM-T20 pretty reliably, and I've got two other printers which just ignore the request.

If your network printer is made by Epson, you might be interested in the auto-status back (ASB) snippet that was posted at #43.

**Comment by cdeber** [comment]
getPrinterStatus() not working in my TM-T20ii too.

**Comment by nitinsbuzz** [comment]
It seems that you need to use a seperate EPSON API to enable printer status to be accessible. Will look further into this. Nonetheless, ASB is a good solution as well.

Just a side note..
The readme here states that `$printer->setBarcodeHeight((int) $dots)` and `$printer->setPrintLeftMargin((int) $dots)` require an integer (number of dots) and the standard is 8 and 3 respectively but on windows 10 it seems different. For example, as Barcode height i am using 60 which is almost equal to 1/3 of the standard barcode size.

OS: Windows 10
Printer: Epson TM-T20

**Comment by mike42** [comment]
Closing this off. At the time of writing, the documented behavior of the library does not include reading from the printer, so this is no longer a bug.
