### ISSUE TITLE
I have gp-u80300i POS printer

### ISSUE THREAD

**Issue by knojiyak** [mike42/escpos-php#152]
Hello,

Can you add support for gp-u80300i Thermal Printer.

http://www.gainscha.com/en/pro.asp?anid=71&nid=121&op=2

**Comment by mike42** [comment]
Looks like your printer supports ESC/POS (check the manual to make sure), so it's just a matter of making sure it's enabled, and getting data to the printer from PHP.

So your steps from here are-

- Check the README and see if you can print from the command line
- Check your platform & interface, see [compatibility table](https://github.com/mike42/escpos-php#compatibility) and attempt to print a 'Hello World' receipt from PHP.
- Check out the examples to see what works & what doesn't.
- If something important is broken, open an issue with a reference to the programmer guide and expected input/output. I'm happy to track printer compatibility issues, and would welcome any pull requests toward a `CapabilityProfile` to improve support for this printer if it turns out to be lacking.

Also, since this is not an Epson-branded printer, use the `SimpleCapabilityProfile` ([README link](https://github.com/mike42/escpos-php/blob/master/README.md#using-a-capabilityprofile)) to ask the driver to avoid some more complex output.
