### ISSUE TITLE
ECline Printer

### ISSUE THREAD

**Issue by ferkun** [mike42/escpos-php#171]
Is an economic printer

**Comment by mike42** [comment]
Hey,

There's no actionable information here. Could you elaborate a bit?

- Which model of ECLine printer?
- Did you mean to report successful or buggy output?

**Comment by ferkun** [comment]
Yes. You're right.

Sorry for the last message , was totaly draft :)

I'm using your connector with this printer ec line 5890x

It's working without problems connected as a oki 9 pins in cups. 

In fact this is a very popular and very problematic printer in my country. 

The model is "ec line 5890x", but the real manufacturer is  'gainscha' (gainscha.com.cn)

I have more work to do with this printer because  do not open the cash drawer.

I have to load an old machine with win 32 to load the original driver and then set the cash drawer ON. This can't be do it with any 64 bits windows.

if you like to include this model in your list is full compatible with oki 9 pins in CUPS.

Best Regards

**Comment by mike42** [comment]
Thanks for reporting.

If you have any compatibility issues with text encoding on this printer (ie. non-ASCII characters), please consider posting a self-test page or link to the programming guide for our new database, so that we can improve support for all receipt printers (example: receipt-print-hq/escpos-printer-db#13).
