### ISSUE TITLE
how to use escpos-php in codeigniter

### ISSUE THREAD

**Issue by mramdanf** [mike42/escpos-php#177]
hello, thanks for awesome library.
sir can you please tell me how use escpos-php library in codeigniter?
thanks in advance.

**Comment by mike42** [comment]
I don't use that framework myself, but this is available as a composer package, which I believe is very common in the PHP world.

Maybe you could check with some resources like StackOverflow to see how others are using composer packages in CodeIgniter?

**Comment by lifox89** [comment]
@mramdanf I have tried implementing it in code igniter using xampp. Maybe you have figured it out already for yourself, but for the benefit of others here's how I did it.

1. Copy the **autoload.php** and the **SRC** folder inside your main folder  **_(htdocs/projectfolder/)_**
2. Create a php file in your helpers folder. **_(application/helpers/)_**. Eg. **printer_helper.php**
3. Then inside **printer_helper.php**, copy the **'require'** and **'use'** lines (this should be outside a function). 
4. Then create a function that will contain the printer commands with data you will passing unto this function (**$printer->text(), ->cut() and etc..)**
5. In your controller, load the helper ( **$this->load->helper('printer_helper'); )**
5. Then in your model, you can just directly call the function you created in step 4, passing array of data to be printed.

Happy printing! :)

**Comment by mramdanf** [comment]
many thanks for your help @lifox89, i will try it

**Comment by Stenerson** [comment]
@mramdanf, 
I'm sure @lifox89's solution will work but just to give you (and others) an alternative, in my application I created a library called `ReceiptPrint` that creates an escpos-php connection and printer and provides a function (or functions) to print receipts.

I like this approach because it encapsulates all of the printing business (adding lines, text, justification, etc.) within the library. All the caller needs to do is connect to a printer and call a print function.

[I created a gist](https://gist.github.com/Stenerson/49b2ed292796e1ccfcfc89e49a2dab79) with the library and an example of how to call it. The idea would be to subclass the `ReceiptPrint` class and add a specific print function for each label or just create new print functions in the `ReceiptPrint` class for each of your labels.

```php
try {
  $this->load->library('ReceiptPrint');
  $this->receiptprint->connect('192.168.0.110', 9100);
  $this->receiptprint->print_test_receipt('Hello World!');
} catch (Exception $e) {
  log_message("error", "Error: Could not print. Message ".$e->getMessage());
  $this->receiptprint->close_after_exception();
}
```

Hopefully that helps as well!

_Note: I'm still on CodeIgniter 2.2.x. I'm not sure what's changed in 3.x+ but I assume this would still work._

**Comment by mramdanf** [comment]
thanks for solutions @Stenerson, it works pefectly. but im facing another problem on add image logo when printing, i was modify for a little your `ReceiptPrint` class but when i call $this->receiptprint->connect('10.69.69.3', 9100); give an error that image was not found.

this is complete [ReceiptPrint](https://gist.github.com/mramdanf/a99fc98c8334300d8a8e9f61ad781eeb#file-receiptprint-php) thas was modify. and im sure that the image is on the place that i was pointed. your help is realy apreciated thanks in advance.

**Comment by Stenerson** [comment]
@mramdanf I haven't worked with images in this library but is it possible that the path is incorrect? To be perfectly honest I **always** struggle with paths in php. 

Maybe try `$this->img_logo = EscposImage::load(__DIR__ . "\escpos-php-development\logo_pos.png", false);` since this is the way you're successfully loading the `autoload` script?

On an unrelated note I would also suggest moving the image load out of the connect function and into the print function.  Maybe something like this:

```php
public function print_test_receipt($text = "")
{
    $this->check_connection();
    $img_logo = EscposImage::load(__DIR__ . "\escpos-php-development\logo_pos.png", false);
    $this->printer->setJustification(Printer::JUSTIFY_CENTER);
    $this->printer->graphics($img_logo);
    $this->add_line("Testing Receipt Print");
    $this->add_line(); // blank line
    $this->add_line($text);
    $this->add_line(); // blank line
    $this->add_line(date('Y-m-d H:i:s'));
    $this->printer->cut(Printer::CUT_PARTIAL);
    $this->printer->close();
}
```

**Comment by mike42** [comment]
You also have an escape sequence for a non print-able character in your path: [\e](http://php.net/manual/en/regexp.reference.escape.php).

You can save some trouble by always use forward slashes for filenames: "/foo/bar". This works on any platform.

Other fixes include writing two backslashes each time (escape it): "\\\\foo\\\\bar", or using single quotes instead: '\\foo\\bar'.

**Comment by mike42** [comment]
Assuming this is answered, I'll close this off now.
