### ISSUE TITLE
how to fix this?

### ISSUE THREAD

**Issue by monkhsaikhan** [mike42/escpos-php#18]
Catchable fatal error: Argument 2 passed to EscposPrintBuffer::__construct() must implement interface PrintConnector, null given, called in C:\xampp\htdocs\escpos\Escpos.php on line 191 and defined in C:\xampp\htdocs\escpos\src\EscposPrintBuffer.php on line 89

**Comment by mike42** [comment]
Hello,

You are instantiating `escpos-php` from a webserver, without telling it how to talk to your receipt printer. 

````
$printer = new Escpos();
````

So that I can point you at a relevant example, could you please let me know more about what you're trying to do. Specifically:
- What type of printer do you have, and how is it connected?
- Is the printer connected to the same computer that you're running XAMPP on?
- Can you confirm that you have printed to it directly from the command-line or operating system print functions, and that it works?

**Comment by alvirtuoso** [comment]
I have the same problem. I have my thermal epson t22 connectted via usb into my mac. I've been able to print to it from print dialog using my browser. I use MAMP.
I just used your sample code for testing.
$printer = new Escpos();
$printer -> text("Hello World!\n");
$printer -> cut();
$printer -> close();

**Comment by mike42** [comment]
Please fetch a fresh copy of the code and update your snippet to include the use of a `PrintConnector` to tell the library how to communicate with your printer. The [basic usage](https://github.com/mike42/escpos-php#basic-usage) in README.md to include information about how to choose a connector.

@alvirtuoso - please refer to #85 for tracking Mac/USB issues.
