### ISSUE TITLE
Will this library work with Epson Bluetooth printer TM-P20?

### ISSUE THREAD

**Issue by 05bca054** [mike42/escpos-php#185]
Hi Mike,

First of all Awesome library for thermal printer.

I have remote LAMP server and using android system to print from web browser(Chrome) through printer which is connected to Bluetooth printer TM-P20(Epson).

http://www.epson.co.in/epson_india/printers_and_all_in_ones/pos/product.page?product_name=Epson_TM-P20

Can i take direct print using given PHP script which risedes on remote server and run on android chrome browser over Bluetooth printer which attached to android system like given above?

LAMP server ---> android chrome web client ----> Bluetooth thermal printer(Attached to Android system)

-Naitik

**Comment by mike42** [comment]
The raw output that is generated from this driver will work on the P80.

The final step is what will trip you up. How do you plan to transport binary data from Chrome to your printer?

**Comment by 05bca054** [comment]
In the PDF format.

I have php PDF library called mpdf which generates 3 inch thermal print invoice(Only text, no logo, no bar-code) and this PDF is going to print afterward but i want direct implementation using this library if possible.

Current process is once PDF is downloaded on android chrome browser(Using web panel). Open it manually and then print manually using Bluetooth paired printer.

**Comment by mike42** [comment]
I'd stick with the PDF workflow. This server-side driver would not be straightforward to use in you setup, since your client really needs to kick off system printing from a web browser (client-side bluetooth).

To illustrate the difference, I originally created escpos-php for a similar setup. I had a tablet, an Ethernet printer, and a Linux server. The user hit "Print" on the tablet, which sent a POST request to the server. The server then communicated with the printer directly (TCP from the server side)
