### ISSUE TITLE
Printing image from internet url

### ISSUE THREAD

**Issue by eserenna** [mike42/escpos-php#195]
Used https://partner.wowfi.my/assets/img/essential/logo_wowfi.png as image but returns an error of does not exist, or file not readable. Is it permission issue or this library does not read images from url?

**Comment by mike42** [comment]
Not currently.

The image loader will give up if it can't confirm that a file exists ([exact code](https://github.com/mike42/escpos-php/blob/4b855426b48d7b26b99e7fc997189e6562f06558/src/Mike42/Escpos/EscposImage.php#L427)). This allows the error message associated with incorrect filenames to be the same for all implementations.

The libraries used for implementations (Imagick or GD) actually support URL loading, so if you remove the check that I linked to above, you might have some luck.

The code if you're interested-

- [EscposImage](https://github.com/mike42/escpos-php/blob/4b855426b48d7b26b99e7fc997189e6562f06558/src/Mike42/Escpos/EscposImage.php)
- [GdEscposImage](https://github.com/mike42/escpos-php/blob/4b855426b48d7b26b99e7fc997189e6562f06558/src/Mike42/Escpos/GdEscposImage.php)
- [ImagickEscposImage](https://github.com/mike42/escpos-php/blob/4b855426b48d7b26b99e7fc997189e6562f06558/src/Mike42/Escpos/ImagickEscposImage.php)

It may not apply to you, but since [old versions of ImageMagick](https://blog.cloudflare.com/inside-imagetragick-the-real-payloads-being-used-to-hack-websites-2/) are still in the wild, the image handling is not suitable for user-supplied input.

**Comment by eserenna** [comment]
I'm using EscposImage::load in my project and i'm getting this error message.
File 'https://partner.wowfi.my/assets/img/essential/logo_wowfi.png' does not exist, or is not readable.
But 'https://partner.wowfi.my/assets/img/essential/logo_wowfi.png' does exist. Does it mean that it is not readable? And what does it mean by not readable?

**Comment by mike42** [comment]
You can click through my link to the code above to see that `file_exists()` and `is_readable()` are used. Their limitations are documented by the PHP project, please refer there for definitions of "exists" and "readable"-

- http://php.net/manual/en/function.is-readable.php
- http://php.net/manual/en/function.file-exists.php

You could either try removing the check, downloading the file on the fly, or loading the file off the filesystem instead.

**Comment by mdestafadilah** [comment]
i'm still get it... not only HTTPS but HTTP too... open issues please.

**Comment by Finnca** [comment]
File 'https://temporal.facto.cl/2021/01/b85f0c777a8814239501d7dc7c5c36d6.png' does not exist, or is not readable."
