### ISSUE TITLE
Printing is not consistent and it has unwanted characters. 

### ISSUE THREAD

**Issue by JoshNull** [mike42/escpos-php#198]
Hi! I need help. I have 2 questions:
- I can't print consistenly. I need to restart the printer when it fails to print but sometimes this trick doesn't work. (This can't be a hardware issue because I can print manually)
- Sometimes it has unwanted characters, maybe the format is failing to apply.

I followed the instructions and reviewed it many times but I can't seem to make it work properly. **I'm using Epson TM-88IV on an usb to parallel connection.**

Please confirm that USB-Parallel connection is compatible. I can see that parallel is compatible but how about with USB? Sorry I just need to make sure. 

Here's my code:

```
<?php
require __DIR__. '/vendor/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;

$connector = new FilePrintConnector("/dev/usb/lp0");
$printer = new Printer($connector);

$printer->initialize();
$printer->setJustification(Printer::JUSTIFY_CENTER);
$printer->selectPrintMode(Printer::MODE_DOUBLE_WIDTH);
$printer->text($myVarOne."\n\n");
$printer->selectPrintMode();
$printer->text($myVarTwo."\n\n");
$printer->selectPrintMode(Printer::MODE_DOUBLE_WIDTH);
$printer->text($myVarThree."\n\n\n");
$printer->selectPrintMode();
$printer->cut();
$printer->close();
?>
```

**Comment by mike42** [comment]
I use an Epson TM-U220 via a USB-Parallel adapter. via `usblp`, which looks to be similar to your setup. The only issue I have is with large images, as it's easy to exceed the size of this printer's tiny buffer.

The two issues may have the same cause. Unwanted characters are usually a sign that a command has not been understood. Since these commands are all quite simple, so I would be looking closely at the values of `$myVarOne` etc, then searching for concurrency or transport issues.

Your best next first is to print to a file (eg. `new FilePrintConnector("/tmp/foo.bin")`), then boot up the printer, and start sending this on the command-line to try to replicate the breakage outside of PHP.

```
cat /tmp/foo.bin > /dev/usb/lp0
``

Next, make sure your scripts are the only thing printing. How have you tested printing "manually"? Is there some print system that is also set up to use the printer, which may be sending commands as well?

As your last checklist for debugging, your printer may have a series of DIP switches to alter the default behaviour, bet set these at the defaults, hard-code the values of the variables in your script while testing, and check the PHP error log for failed prints. If none of this works, it is also a good idea to start with a "Hello World" script, make sure it works reliably, then build it up bit-by-bit to determine whether a specific command is causing the problems (just eliminating variables, pretty much).

Hope this informs your debugging efforts!

**Comment by JoshNull** [comment]
Thank you Mike! I'll try your suggestions and post an update.

**Comment by mike42** [comment]
Closing this issue as inactive, hope you were able to solve it. Please file a new issue if you believe there's an `escpos-php` bug lurking there.
