### ISSUE TITLE
Works with Hasar HTP 250

### ISSUE THREAD

**Issue by rcabralyu** [mike42/escpos-php#204]
Well it's work with Hasar HTP 250, but i let a little comment, if show 
Fatal error: Call to undefined function mb_detect_encoding() even installing with composer, it's because need to do "apt-get install php7.0-mbstring" and restart apache2. 
And images must have a height lower than 300px, same with codebar.

Thanks for this great library, you save me!

**Comment by mike42** [comment]
Thanks for reporting.

You're correct- mbstring should be listed as a dependency, so that composer can show an error. This is being tracked at issue #201.

If you need to print long images, see if `bitImageColumnFormat()` works on your printer. It sends a separate print command for each line, so there is no size limit if the printer can keep up. I've made a new issue about printing large images #206, as I've noticed something similar.
