### ISSUE TITLE
 Printing large pictures becomes garbled and the printer stops functioning

### ISSUE THREAD

**Issue by Shane5453** [mike42/escpos-php#222]
Hi thanks for providing you with such a nice package

I am currently experiencing a problem when printing large images
The printer will print garbled characters and stop functioning
Ask how to solve this problem?
There can be a large picture of a fractional print synthesis method

I have seen an ImagePrintBuffer method
Is there an example to use?

Sorry to bother you, please forgive me

**Comment by mike42** [comment]
You may be seeing a known issue. Can you provide a few more details?

- Which manufacturer/model of printer do you use?
- Do you have a code snippet that shows how you are trying to print? I want to see which method you are using to print images.
- What dimensions are the largest images that print without problems?

**Comment by Shane5453** [comment]
the printer that i use is EPSON TM-T70II and TM-T82II. the paper roll size is 57mm.
the code snippet is follow by next:

`
<?php
require __DIR__ . '/vendor/mike42/escpos-php/autoload.php';
use Mike42\Escpos\PrintConnectors\NetworkPrintConnector;
use Mike42\Escpos\Printer;
use Mike42\Escpos\EscposImage;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;

$connector = new NetworkPrintConnector("10.0.1.70", 9100);
$printer = new Printer($connector);

try {
    $tux = EscposImage::load("bigKitchImg.png", false);
    $printer -> graphics($tux);
    $printer -> feed();
    $printer -> cut();
} catch (Exception $e) {
    /* Images not supported on your PHP, or image file not found */
    $printer -> text($e -> getMessage() . "\n");
}

$printer -> close();
`

also I provide the example img url of largest img with/without problems by following...
with problems:
http://i.imgur.com/ijKfUE9.png
http://i.imgur.com/1dbLifj.jpg

without problems:
http://i.imgur.com/iNejBPY.png
http://i.imgur.com/zSVlCxl.jpg

thanks

**Comment by mike42** [comment]
Ok, thanks for that detailed information. What you are seeing is being tracked as issue #206, and I have the same issue on my Epson TM-T20II with 80mm paper. I'll close this off as a duplicate.

I'm hoping to get a feature to slice the image up into smaller pieces, so that the buffer does not get over-run like this when large images are used.

In the meantime, you may want to try either chopping up the images yourself (so that only smaller images are used), or running `$printer -> bitImageColumnFormat($tux);`. This alternative image printing command already has to send the picture one line at a time, so you can get some white in the output, but hopefully this is an improvement on what your printer is currently doing.
