### ISSUE TITLE
Can't connect to client's printer from server 

### ISSUE THREAD

**Issue by JrHasanBUDAK** [mike42/escpos-php#230]
Hi, 
I need to connect client printer (BIXOLON SRP270). My system on linux server, my clients are connecting with browser on Windows. 

Is there any way to do this ?  
```
---------------------------------------------------------
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use App\Http\Controllers\Controller;
use App\Http\Controllers\PrivateApi\MusteriController;
class PrinterController extends Controller
{
    private $printer_etiket = "BIXOLON";
    private $printer_fis = "OTHER";
    private $user;
    private $connector;
    private $printer;
    public function __construct(){
        $this->middleware('auth');
        $this->user = Auth::user(); 
    }
    
    private function setConnector(){
        $this->connector = new WindowsPrintConnector($this->printer_etiket);
    }
    
    private function setPrinter(){
        if(!$this->connector){
            $this->setConnector();
        }
        $this->printer = new Printer($this->connector);  
        $this->printer->initialize();
    }
    private function getPrinter(){
        if(!$this->printer){
            $this->setPrinter();
        }
        return $this->printer;
    } 
------------------------------------------------
```

**Comment by mike42** [comment]
PHP is a server-side language, and can't see hardware on client machines.

Since this query has come up a few times before, please have a read of "[Can I print from my server on the Internet?](https://github.com/mike42/escpos-php/blob/4d2db9cdc7cd9b35fbbc62390516a20e4d5f55f2/doc/FAQ.md#can-i-print-from-my-server-on-the-internet)" from the FAQ, which discusses what you're trying to do.

**Comment by JrHasanBUDAK** [comment]
Thanks for information. I preferred to use [qz.io](https://qz.io) it's solved my problem. 

Best regards

**Comment by mutiemule** [comment]
Printing on local will work well with this package.

However, to print online, you will need to develop a desktop service which has to be installed on the local computer where you need printing to be done.  This is because PHP is a server-side scripting language, so once you put this online, it won't be able to communicate to the local printer. Thus, you need a client service running on the local machine and this is where electron js and node js come into play.

I resolved this by developing an electron js service based on [node-escpos package](https://www.npmjs.com/package/escpos) which can receive commands from the online print command and then communicate those commands to the printer through USB. 

Operating System does not matter in this case, you can be hosting on Linux based server and printing on a windows server. This desktop service interfaces between the online service and the local service. 

You can check out the [node-escpos printer driver package ](https://github.com/song940/node-escpos) for some inspiration on how to go about this.

Check the [FAQs on how to print online](https://github.com/mike42/escpos-php/blob/fe9350e61fb5e38416ec6243873c37fa65f34eb5/doc/FAQ.md#can-i-print-from-my-server-on-the-internet) to have some pointers too.
