### ISSUE TITLE
Unable to do Remote Printing?

### ISSUE THREAD

**Issue by yongjp** [mike42/escpos-php#238]
Hi. I'm trying to print the receipt remotely over the internet. Is this possible?
I've opened the port 9100 on the router but still can't seem to connect to the printer. 

I've tested locally and it works. The error is shown below. Any help would be greatly appreciated.
Caught exception: Cannot initialise NetworkPrintConnector: Connection timed out

My printer setup is connected directly to the router and I am able to reach the printer on a separate network by entering 58.182.XXX.XX:9100 on the address bar on Chrome

My code is as follows

require __DIR__ . '/autoload.php';

use Mike42\Escpos\PrintConnectors\NetworkPrintConnector;
use Mike42\Escpos\Printer;

$printerIP = "58.182.XXX.XX";
//$printerIP = "192.168.0.108";

try
{
	$connector = new NetworkPrintConnector($printerIP, 9100);
	
	$printer = new Printer($connector);
	$printer -> initialize();
	$printer -> text("Hello World!\n");
	$printer -> cut();	
	$printer -> close();
}
catch (Exception $e)
{
	echo 'Caught exception: ',  $e->getMessage(), "\n"; 
}

**Comment by Stenerson** [comment]
@yongjp Printing from the Internet is definitely possible. Have you checked out [Can I print from my server on the Internet?](https://github.com/mike42/escpos-php/blob/development/doc/FAQ.md#can-i-print-from-my-server-on-the-internet) in the FAQ? Maybe one of those answers will help.  If you're timing out it is almost certainly not an issue with this library but something with your network or settings.

You mentioned you were able to connect to the printer on an outside network. 
- Is the outside network the same one that your Internet server resides on? 
- Are you able to telnet into the printer `telnet 58.182.XXX.XX 9100` from your Internet server and print text from telnet? (The printer will print anything you submit to the telnet session once connected).

If you can telnet to the printer from your server you should be able to connect to it with this library.

In my opinion, the easiest way to do this (without resorting to pure client side printing) is to use port forwarding to forward an external port to your printer's port 9100. There are some possible security implications to this depending on your use case but it's simple and it works.

**Comment by yongjp** [comment]
"In my opinion, the easiest way to do this (without resorting to pure client side printing) is to use port forwarding to forward an external port to your printer's port 9100. There are some possible security implications to this depending on your use case but it's simple and it works."

This works. Thanks for saving me hours of work. Was close to ripping my hair out.

**Comment by sandeepkhehra** [comment]
@yongjp @Stenerson I am facing the same issue over my server and i am able to print the receipts via TELNET but not thought this library. I am getting a "could not establish connection". Same IP address and port number though.

could anyone of you please guide me how to do the port forwarding?
I am on Windows machine and the webserver has Ubuntu.

Any help would be appreciated.

**Comment by mutiemule** [comment]
Printing on local will work well with this package.

However, to print online, you will need to develop a desktop service which has to be installed on the local computer where you need printing to be done.  This is because PHP is a server-side scripting language, so once you put this online, it won't be able to communicate to the local printer. Thus, you need a client service running on the local machine and this is where electron js and node js come into play.

I resolved this by developing an electron js service based on [node-escpos package](https://www.npmjs.com/package/escpos) which can receive commands from the online print command and then communicate those commands to the printer through USB. 

Operating System does not matter in this case, you can be hosting on Linux based server and printing on a windows server. This desktop service interfaces between the online service and the local service. 

You can check out the [node-escpos printer driver package ](https://github.com/song940/node-escpos) for some inspiration on how to go about this.

Check the [FAQs on how to print online](https://github.com/mike42/escpos-php/blob/fe9350e61fb5e38416ec6243873c37fa65f34eb5/doc/FAQ.md#can-i-print-from-my-server-on-the-internet) to have some pointers too.
