### ISSUE TITLE
Support cut functionality EPSON TM-T88IV on multiple and different system

### ISSUE THREAD

**Issue by priyankaPHP** [mike42/escpos-php#240]
Hi Mike ,

Your library is awesome it works perfectly on both windows and linux through FilePrintConnector and WindowsPrintConnector connectivity.
But my actual requirement is that I am required to make connectivity to any numbers of computer at different platforms(like Linux , Android devices & windows) which means through WindowsPrintConnector I am able to make connection to only one particular system at a time{ $connector = new Mike42_Escpos_PrintConnectors_WindowsPrintConnector("smb://username:password@IP/workgroup/share printername"); }
Is there exist a way to connect to multiple system at a time and my printer is USB port EPSON TM-T88IV and hosting of code would be on LINUX i.e. AWS.

Please suggest me on this since I am stuck on this from very long time.

**Comment by mike42** [comment]
If I understand correctly, you want to easily connect to different types of printers based on something like a connection string, rather than a hard-coded implementation.

I could write some new code in `PrintConnector` to acceot a URI, then return different implementations based on the scheme used. Would your usage be easier if this sort of usage was possible?

```php
$foo = new PrintConnector::get("file:///dev/usb/lp0"); // FilePrintConnector
$foo = new PrintConnector::get("tcp://x.y.z.w:9100/"); // NetworkPrintConnector
$foo = new PrintConnector::get("ipp://foobar/"); // CupsPrintConnector
$foo = new PrintConnector::get("smb://windows/printer"); // creates a WindowsPrintConnector
```

It not clear from your question how the AWS server is going to be able to see the printers. If you haven't planned this out, then you may find some relevant information in the FAQ entry: [Can I print from my server on the Internet?](https://github.com/mike42/escpos-php/blob/b79a8050cdb0a0314e7d87253b62ca39eb4a4be6/doc/FAQ.md#can-i-print-from-my-server-on-the-internet)
