### ISSUE TITLE
Metapace T-1 works

### ISSUE THREAD

**Issue by nitinsbuzz** [mike42/escpos-php#241]
Metapace T-1 thermal printer works perfectly (cashbox pulse + printing) even though the make is not listed in the cups manufacturer list. Selected the first option from Samsung instead. If there is a better option, please do let me know. 

Linux Ubuntu 14.04
using CupsPrinterConnector

**Comment by mike42** [comment]
Thanks for reporting. Here is some detailed background on your driver question, which may be rolled into an FAQ entry in future.

This project lets you generate binary ESC/POS code from PHP, so it is a print driver already. We just use CUPS to transport the binary data.

This means that "Other / Raw Queue" or "Generic / Text Only" (depending on your system) are actually the most appropriate drivers to select for a setup involving just **PHP &rarr; CUPS &rarr; Printer** ([related blog post for OS X CUPS setups](https://mike42.me/blog/2015-10-how-to-connect-a-usb-receipt-printer-up-on-mac-os-x)).

You can select a CUPS driver as well, and since we use raw printing, this wont affect `escpos-php`. The CUPS driver could be then be used when you print from applications that do not speak ESC/POS (ie, **LibreOffice &rarr; CUPS &rarr; Printer**, or **Chrome &rarr; CUPS &rarr; Printer**), so you should test the setup by printing a CUPS test page, and ask your vendor for which driver to use / support if you have any issues (`escpos-php` is not involved at all, so please don't ask here!).
