### ISSUE TITLE
Print on local printer when source files on external (WAN) server

### ISSUE THREAD

**Issue by ban007** [mike42/escpos-php#242]
Hi!
when i try to print to my local TM printer i get the error message that says smbclient not found. I supose that my php script tries to print to a sharename in it's network. My script is hosted on an external server but the client who executes the script is at my home. How can i get the printing on my local connected USB printer?
Thanks! Ban.

**Comment by mike42** [comment]
There is some background for this and a few strategies discussed in the FAQ: [Can I print from my server on the Internet?](https://github.com/mike42/escpos-php/blob/b79a8050cdb0a0314e7d87253b62ca39eb4a4be6/doc/FAQ.md#can-i-print-from-my-server-on-the-internet)

The actual error message means that the server is running Linux, and you've asked it to print to a Windows machine over the LAN, but the command `smbclient` is not available to send the print job.

**Comment by mutiemule** [comment]
Printing on local will work well with this package.

However, to print online, you will need to develop a desktop service which has to be installed on the local computer where you need printing to be done.  This is because PHP is a server-side scripting language, so once you put this online, it won't be able to communicate to the local printer. Thus, you need a client service running on the local machine and this is where electron js and node js come into play.

I resolved this by developing an electron js service based on [node-escpos package](https://www.npmjs.com/package/escpos) which can receive commands from the online print command and then communicate those commands to the printer through USB. 

Operating System does not matter in this case, you can be hosting on Linux based server and printing on a windows server. This desktop service interfaces between the online service and the local service. 

You can check out the [node-escpos printer driver package ](https://github.com/song940/node-escpos) for some inspiration on how to go about this.

Check the [FAQs on how to print online](https://github.com/mike42/escpos-php/blob/fe9350e61fb5e38416ec6243873c37fa65f34eb5/doc/FAQ.md#can-i-print-from-my-server-on-the-internet) to have some pointers too.
