### ISSUE TITLE
how can i print unicode string such as persian

### ISSUE THREAD

**Issue by rezanajaf86** [mike42/escpos-php#243]
hi , 
can i print persian string , my device print persian string with printer_write($handle, "$text")
tank you

**Comment by mike42** [comment]
It's not clear to me whether you are using `escpos-php`.

Could you confirm that you are using this driver, and post back enough information for this question to be tracked?

Eg,

- your ESC/POS printer make/model
- a code snippet showing how you have tried to print a string in your script with `escpos-php`
- a picture of the output so that I can see how it looks different to the UTF-8 string in your code
