### ISSUE TITLE
Exception in ImagickEscposImage.php line 249

### ISSUE THREAD

**Issue by watio** [mike42/escpos-php#245]
I try to print print pdf and i get this error
Exception in ImagickEscposImage.php line 249:
exception 'ImagickException' with message 'PDFDelegateFailed `The system cannot find the file specified.
' @ error/pdf.c/ReadPDFImage/801' in 

Can you help me please ?

**Comment by mike42** [comment]
This error is coming from the ImageMagick library, espos-php is just passing it on.

Since this library is widely used, a [web search for the exception](https://www.google.com/search?q=PDFDelegateFailed+The+system+cannot+find+the+file+specified) is probably the best place to start. Looks like you need to install some extra programs before PDF's will work.

**Comment by watio** [comment]
Exactly, i install GS and this solves the problem. 
tank you

how can i print .rtf document ?

**Comment by mike42** [comment]
This driver has no RTF code at all, so you would need to convert it to an image first.

I'm open to reviewing any pull requests that add support for new input formats, so please check out the [developer guide](https://github.com/mike42/escpos-php/blob/development/CONTRIBUTING.md) if this interests you.
