### ISSUE TITLE
HS-589C Hebrew output

### ISSUE THREAD

**Issue by theunreal** [mike42/escpos-php#246]
I'm trying to print hebrew characters from my thermal printer using simply USB, but it does prints jibrish instead of my language, Hebrew.
I used simply this:

```
 // Enter the share name for your USB printer here
    $connector = new WindowsPrintConnector("POS-58");
    //$connector = new WindowsPrintConnector("Receipt Printer");
    /* Print a "Hello world" receipt" */
    $printer = new Printer($connector);
    $printer -> text("שלום\n");
    $printer -> cut();
    
    /* Close printer */
    $printer -> close();
```

How setting a language can be done? Is it about this library or about the printer?

When I tried to print from a word document it did work

**Comment by mike42** [comment]
It sounds like you need to load the right `CapabilityProfile` for your printer, which tells the driver how to use the different code pages (by default, a profile for Epson printers is used).

Which model printer are you using?

**Comment by theunreal** [comment]
Hey @mike42 , I'm trying to use a new cheap printer I ordered online. In the program documentation I can see that the code page I need is PC862

**Comment by mike42** [comment]
Did some quick googling and [found the printer](http://www.hsprinter.com/en/product/cheapest-receipt-printer-HS-589CU.html). The 589C appears visually similar to the ZJ-5890, which is a good start, since they're very common.

You seem to be aware that ESC/POS printers don't understand UTF-8, so we do a lot of encoding-related stuff as part this driver. From your snippet, I see two main blockers.

- No printer profile upstream yet to get PC862 on your printer (track this [here](https://github.com/receipt-print-hq/escpos-printer-db/issues/13))
- We don't have a PHP implementation of the unicode bidirectional text layout algorithm, so you have to be pretty creative to get the characters to print the right order (!)

If you do a search on the issue tracker for `ImagePrintBuffer`, you will find some short-term work-arounds too.

**Comment by globalcitizen** [comment]
Try...
```
    $printer -> text(iconv('utf8','pc862',"שלום\n"));
```

**Comment by mike42** [comment]
`$printer -> text()` accepts UTF-8 and switches code pages based on the profile, so I would not suggest converting like that.

Some progress on this though, we now have a profile for that printer, so Hebrew output will "work". For that reason, I'm closing this off.

You would absolutely need to manually reverse (and optionally right-align) your text, because the printer is always going to expect left-to-right text. We currently send every glyph directly to the printer, and the printer will expect left-to-right text.

For future readers, I'm open to reviewing any improvements that either implement a command to switch text direction, if one exists, or to introduce **line buffering, bi-directional text layout and word wrapping** in the `$printer -> text()` function, which seems to be the "correct" way to solve this.
