### ISSUE TITLE
Use of custom font type

### ISSUE THREAD

**Issue by ridicc** [mike42/escpos-php#250]
You can use other font types to be the case. How would the implementation.
thanks.

**Comment by mike42** [comment]
Most ESC/POS printers come with two fonts: "A" (normal) and "B" (small). These are set via [setFont()](https://github.com/mike42/escpos-php/blob/b79a8050cdb0a0314e7d87253b62ca39eb4a4be6/README.md#setfontfont). This is used a few times in the examples that are included with the repo.

**Comment by ridicc** [comment]
How to use a specific font type. For example (Source type: "Times New Roman"), as the implement.
Thank you very much for the reply.

**Comment by mike42** [comment]
This driver generates binary ESC/POS for receipt printers, and unfortunately, there is no ESC/POS command for "use Times New Roman".

However, there is ESC/POS command for "print this image", so you can always render some text to an image in and then print the image, if you want to. Libraries for creating images from PHP include [Imagick](http://php.net/manual/en/book.imagick.php) and [Gd](http://php.net/manual/en/book.image.php).

I would encourage you to look at a component called `ImagePrintBuffer`, which will eventually allow you to print text in any font. This changes the `text()` function to generate tiny images with Imagick. There is an example that uses a custom Arabic font with an `ImagePrintBuffer` [here](https://github.com/mike42/escpos-php/blob/ba2ed8c0b78fd4aa4cc2a16eb5f81c29b0e83307/example/specific/6-arabic-epos-tep-220m.php).

Usage is something like:

```php
<?php
$buffer = new ImagePrintBuffer();
$buffer -> setFont($fontPath);
$buffer -> setFontSize($fontSize);
$profile = CapabilityProfile::getInstance();
$connector = new FilePrintConnector("/dev/usb/lp0");
$printer = new Printer($connector, $profile);
$printer -> setPrintBuffer($buffer);
$printer -> text("Hello world\n");
```

The `ImagePrintBuffer` component is not widely used, so if using image libraries to render text is a major part of your use case, then please consider hacking it into shape. I'm open to reviewing any pull requests for maintenance and improvements to this component so that it can be properly supported.

**Comment by keophilavanh** [comment]
your code run for me have error , how can i do 
`<?php
/* Change to the correct path if you copy this example! */
require __DIR__ . '/../../vendor/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;

use Mike42\Escpos\CapabilityProfile;
use Mike42\Escpos\PrintBuffers\EscposPrintBuffer;
use Mike42\Escpos\PrintBuffers\ImagePrintBuffer;


try {
    // Enter the share name for your USB printer here
    //$connector = "Microsoft Print to PDF";
    $connector = new WindowsPrintConnector("POS-80C");

    /* Print a "Hello world" receipt" */
    $printer = new Printer($connector);
    
    $profile = CapabilityProfile::load("default");
    $buffer = new ImagePrintBuffer();
    $buffer -> setFont(__DIR__ . '/../../phetsarath_ot.ttf');
    $buffer -> setFontSize(12);

    /* Print a series of receipts containing i18n example strings */
    $printer = new Printer($connector, $profile);
   $printer -> setPrintBuffer($buffer);
    $printer -> text("ລະບົບຮ້ານອາຫານ\n");

    $printer -> cut();
    /* Close printer */
    $printer -> close();
} catch (Exception $e) {
    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}
`

**Comment by keophilavanh** [comment]
![image](https://github.com/mike42/escpos-php/assets/36201795/13445398-b71d-42c1-9582-19e9efd7d074)
