### ISSUE TITLE
Is this plugin compatible with citizen tz30-m01 printer ?

### ISSUE THREAD

**Issue by achalj09** [mike42/escpos-php#253]

**Comment by mike42** [comment]
Good question! I can't answer it myself, because I don't have this printer. I'm guessing you do though, and would suggest checking that it supports ESC/POS, then simply trying it out with the [`"simple"` capability profile](https://github.com/mike42/escpos-php/blob/a79dc7516e71f0749ea081e95d7fdfec8ffbdbb9/README.md#using-a-capabilityprofile).

Please also consider submitting a Citizen TZ30-M01 test page and a link to vendor documentation to the [ESC/POS printer database](https://github.com/receipt-print-hq/escpos-printer-db) project, which can allow us to support any advanced features (like QR codes and non-ASCII text) that your printer may be capable of.

See also FAQ question [Can you add support for Printer X?](https://github.com/mike42/escpos-php/blob/4d2db9cdc7cd9b35fbbc62390516a20e4d5f55f2/doc/FAQ.md#can-you-add-support-for-printer-x)
