### ISSUE TITLE
How to print Vietnamese characters

### ISSUE THREAD

**Issue by isaacheung** [mike42/escpos-php#254]
I got a ZiJiang 8250 which claims to support WCP1258.  Unfortunately Windows-1258 is not a supported encoding for PHP.  How do I go about converting a UTF-8 Vietnamese string and get it printed properly?  

Can someone write a textVietnamese() similar to textChinese()?

**Comment by mike42** [comment]
Good news and bad news.

The `text()` function accepts UTF-8 text, and will switch code pages as necessary, so that you can print any non-ASCII characters that your printer knows about. It requires that you [set up the printer with the right `CapabilityProfile`](https://github.com/mike42/escpos-php#using-a-capabilityprofile), so that escpos-php knows that WCP1258 is available, and how to access it.

But the bad news: There is no profile for the ZJ8250, and non-ASCII characters will not be available on your printer until the profile is written. Are you able to locate programmer guide or print a test page, and post a link/image [upstream ESC/POS printer database](https://github.com/receipt-print-hq/escpos-printer-db) project so that we can kick that off? 

There is a [request open for the ZJ5890T](https://github.com/receipt-print-hq/escpos-printer-db/issues/130), which shows the sort of information that is needed to construct a profile for your printer.

**Comment by isaacheung** [comment]
Hi Mike,

My self test printout for Zijiang 8250 is the same as your Zjiang Zj-5890T except with different print width.

With "ESC t 27" or "ESC t 94" I was able to print the code points from 128 to 255 which are exactly the same as the official WCP1258 characters.  The problem is that these are not pre-composed characters. WCP1258 uses combining diacritical. So I assume if I want to print the letter ẳ, I would print the letter ă (code point \xE3) first and then the combination hook ̉  (\xD2) .  

<?php
/* ASCII constants */
const ESC = "\x1b";
const GS="\x1d";
echo ESC . "@"; // Reset to defaults
echo ESC . "t" . chr(27); // vietnamese
echo ESC . chr(227) . chr(210);  // ă and  ̉  

echo ESC."d".chr(5); // Blank line
echo GS."V\x41".chr(3); // Cut
exit(0);
?>
But doing so the ă and the ̉  were printed side by side.  I have to admit that I'm confused even how 
WCP1258 works on Windows.  Hopefully you can sort it out for us and I hope the vendor's including Windows-1258 is not just a marketing formality but actually with some merits.

**Comment by mike42** [comment]
I can confirm that you debugged this correctly. Hopefully this post points you in the right direction.

You can see how a UTF-8 character becomes multiple `Windows-1258` characters with `iconv`:

```
$ iconv --from-code=UTF-8 --to-code=CP1258
Tiếng Việt, còn gọi tiếng Việt Nam hay Việt ngữ, là ngôn ngữ của người Việt (người Kinh) và là ngôn ngữ chính thức tại Việt Nam.
Ti��ng Vi��t, co�n go�i ti��ng Vi��t Nam hay Vi��t ng��, l� ng�n ng�� cu�a ng���i Vi��t (ng���i Kinh) v� l� ng�n ng�� ch�nh th��c ta�i Vi��t Nam.
```
Attempting to print with code page 94.

```php
$connector = new FilePrintConnector("/dev/usb/lp1");
$table = 94;
$connector -> write("\x1b" . "t" . chr($table));
$connector -> write(iconv("UTF-8", "CP1258", "Tiếng Việt, còn gọi tiếng Việt Nam hay Việt ngữ, là ngôn ngữ của người Việt (người Kinh) và là ngôn ngữ chính thức tại Việt Nam.") . "\n");
$connector -> close();
```
But the result shows that the characters are not composed.

![2017-01-vietnamese-outp](https://cloud.githubusercontent.com/assets/2080552/22173623/33795504-e01d-11e6-9c81-9ed55c34336b.png)

So your POS-5890 doesn't really support Vietnamese text well enough to use it.

### Option 1: Work around the problem

My standard work-around here is to render text to an image, then print the image instead. It is done on the host with PHP, just check two things:

- Install Imagick extension
- You need a copy of a good i18n font like [Noto Sans](https://www.google.com/get/noto/).

```bash
$ sudo apt-get install php-imagick
$ php -m | grep imagick
imagick
```

This is currently implemented in `ImagePrintBuffer`. See `examples/character-encodings-with-images.php` for an existing example.

Snippet that should work for you (note that we use the `simple` profile, which is suggested for printers without their own):

```php
<?php

require __DIR__ . '/../autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;
use Mike42\Escpos\EscposImage;
use Mike42\Escpos\CapabilityProfile;
use Mike42\Escpos\PrintBuffers\EscposPrintBuffer;
use Mike42\Escpos\PrintBuffers\ImagePrintBuffer;

// Connection settings for the printer
$connector = new FilePrintConnector("/dev/usb/lp1");
$profile = CapabilityProfile::load("simple");

// Setup for printing text. You can switch between these as necessary.
$imageBuffer = new ImagePrintBuffer();
$imageBuffer -> setFont(__DIR__ . "/NotoSans-Regular.ttf");
$textBuffer = new EscposPrintBuffer();

$text = "Tiếng Việt, còn gọi tiếng Việt\n" .
        "Nam hay Việt ngữ, là ngôn ngữ \n" .
        "của người Việt (người Kinh) và\n" .
        "là ngôn ngữ chính thức tại\n" .
        "Việt Nam.";
$printer = new Printer($connector, $profile);
try {
  $printer -> setPrintBuffer($imageBuffer);
  $printer -> text($text);

  $printer -> setPrintBuffer($textBuffer);
  $printer -> text($text);
} finally {
  $printer -> close();
}
```

The image-based output can now render Vietnamese, while the text-based output uses a "?" for characters that are not understood:

![2017-01-vietnamese-outp-2](https://cloud.githubusercontent.com/assets/2080552/22173859/b1c5dedc-e022-11e6-9cc1-8e2bb5ab7347.png)

You do lose a lot of speed and flexibility when you print like this, but hey, it works.

### Option 2: Get an Epson printer

The work-around above looks good, but will cause slower printing, plus you have to manually wrap lines, and lose the ability to natively format text (bold, font size, underline, etc).

You would be doing yourself a favour if you got an Epson-branded printer, since they support (pre-composed) TCVN-3.

The below snippet was previously posted to #140, and shows how UTF-8 text is supposed to be used with this driver.

``` php
<?php
require __DIR__ . '/vendor/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;
use Mike42\Escpos\CapabilityProfiles\DefaultCapabilityProfile;

// Printer initialisation
$connector = new FilePrintConnector("/dev/usb/lp1");
$printer = new Printer($connector, $profile);
$printer -> text("Tiếng Việt, còn gọi tiếng Việt Nam hay Việt ngữ, là ngôn ngữ của người Việt (người Kinh) và là ngôn ngữ chính thức tại Việt Nam.\n");

// Printer shutdown
$printer -> cut();
$printer -> close();
```

![escpos-140-test](https://cloud.githubusercontent.com/assets/2080552/16894785/56a810ae-4ba5-11e6-9562-1627b8388b2c.png)

**Comment by makaraban** [comment]
I got error when i was print utf-8 as khmer language, it wasn't correct spelling I want as "សាកល្បងបោះពុម្ពជាភាសាខ្មែរ" but output as below:
<img src="https://camo.githubusercontent.com/5f24fad83e9f6184235a798726fb034c151e11d1/68747470733a2f2f73636f6e74656e742e66706e68312d312e666e612e666263646e2e6e65742f762f7433342e302d31322f32363133333435385f31303231303238383139313138353038325f313734363432373038395f6e2e6a70673f6f683d3630383762323261386334323063636630656530656533653533303237653035266f653d3541343736433341" alt="" data-canonical-src="https://scontent.fpnh1-1.fna.fbcdn.net/v/t34.0-12/26133458_10210288191185082_1746427089_n.jpg?oh=6087b22a8c420ccf0ee0ee3e53027e05&amp;oe=5A476C3A" style="max-width:100%;">
Please help me how to correct this to "សាកល្បងបោះពុម្ពជាភាសាខ្មែរ"
