### ISSUE TITLE
[BC Break] PHP 7 Support

### ISSUE THREAD

**Issue by gabbydgab** [mike42/escpos-php#255]
Hi @mike42 ,

Are you planning to have version 2.x for PHP 7? How can I help?

**Comment by mike42** [comment]
I should start a roadmap so that we can collect ideas for 2.x in one place.

I believe that current release of escpos-php should (at a minimum) run on everything that receives active or security support for PHP (currently, that is 5.6, 7.0 and 7.1). Additionally (so that we don't get inundated with newbie bug reports), it's nice to not run on packaged versions that are shipped with the latest version of each major Linux distribution. Eg, RHEL 7 is still shipping PHP 5.4.

We're doing pretty good, I think, since we run unit tests on all these versions, plus others.

![screenshot from 2017-01-08 17-50-32](https://cloud.githubusercontent.com/assets/2080552/21747943/45eab4d2-d5cb-11e6-8d7e-22fda3f86ada.png)

- 0.x: There are versions of this code that run on PHP 5.2.
- 1.x: Because of namespaces, we strictly require PHP 5.3+
- 2.x (planned) Because our development dependencies are being held back by PHP 5.3, I'll introduce short array syntax so that it will only run on PHP 5.4+ will be required. Unless somebody needs a particular feature, PHP 5.4 and 5.5 will remain a part of the build, so that we have minimal breakage.

**Comment by gabbydgab** [comment]
So version 2.x will be 5.4 up to 5.6 minimum support? and will have full 7.x features in 3.x?

**Comment by mike42** [comment]
Yep, 2.x will run on 5.4, 5.5, 5.6, 7.0, 7.1 if we release it in the first half of this year.

Which PHP 7 features are you keen to see implemented in escpos-php? The addition of scalar type hinting and function return types seem most applicable for a library.

**Comment by gabbydgab** [comment]
> The addition of scalar type hinting and function return types seem most applicable for a library.
:+1: 

also to make it more extendable without affecting the core features

**Comment by mike42** [comment]
Great ideas. In summary, I already run on PHP7, and I hope other users do too.

Some of the features that have been added to PHP recently will not be viable for inclusion for a few years, as we cannot reasonably remove support for PHP 5.x until it is truly obsolete. This is the nature of developing libraries in interpreted languages: you don't get to target one version.

There is no doubt that old versions will be removed with each major release, so I'll close this issue off, and we can re-visit in future when we have an identified use for these features, and no reason not to use them.
