### ISSUE TITLE
Tested Excelvan HOP-E200 on Raspberry pi 3 [USB + Bluetooth]

### ISSUE THREAD

**Issue by CrowDevelop** [mike42/escpos-php#256]
Works well in both interface but i have been forced to use bitImage() method, the graphics() method print "random" characters.

For bluetooth i just create a rfcomm port and bind it to the printer MAC.

**Comment by mike42** [comment]
Thanks for reporting, especially the `rfcomm` usage!

You might be the first person to use a bluetooth printer with this driver.

**Comment by user890104** [comment]
I figured it out, and got my HOIN HOP-H58 to work over bluetooth, because we were out of USB A to B cables.
first, start bluetoothctl
power on the controller
power on the printer
enter scan mode
when you see the printer, type: pair [printer mac addr]
wait for the pairing to complete, it does not require password
after pairing, it should auto connect, make sure it's connected, if not type: connect [printer mac addr]
close bluetoothctl or open another terminal
run as root: rfcomm bind hci0 [printer mac addr]
check if there's /dev/rfcomm0 and if you can write to it
you need to be in the dialout group to do so
then you can use: FilePrintConnector('/dev/rfcomm0')
