### ISSUE TITLE
Need help to use ESCPOS to worki with NT-360B USB Port Printer

### ISSUE THREAD

**Issue by linkanp** [mike42/escpos-php#261]
Hi, I've purchased a receipt printer which Model is  NT-360B of Netum Brand Name.
Here is the details of the printer, https://www.alibaba.com/product-detail/NT-360B-USB-port-Barcode-Label_60447560298.html?spm=a2700.7724838.0.0.S4fLyD&s=p

Please help me to make this printing working. 

Thank you in advance.

**Comment by mike42** [comment]
Please check out [Can you add support for Printer X?](https://github.com/mike42/escpos-php/blob/a79dc7516e71f0749ea081e95d7fdfec8ffbdbb9/doc/FAQ.md#can-you-add-support-for-printer-x) in the FAQ, it has some extra info about ways to improve support for your printer.

Since you have the hardware, you are best positioned to test it out and report back with any issues. Generally, this driver is suitable for a PHP programmer to interact with any ESC/POS printer. Best starting point is to check that your printer understands ESC/POS, then try it out with the default profile by stepping through the README, and posting back with any issues.
