### ISSUE TITLE
Can this printer work with the current Library.

### ISSUE THREAD

**Issue by wilayats** [mike42/escpos-php#263]
![image](https://cloud.githubusercontent.com/assets/6419400/21838708/61017996-d7f5-11e6-834f-b1a3329a1a97.png)

**Comment by JayzeeHuang** [comment]
> This project implements a subset of Epson's ESC/POS protocol for thermal receipt printers. It allows you to generate and print receipts with basic formatting, cutting, and barcodes on a compatible printer.

The library was developed to add drop-in support for receipt printing to any PHP app, including web-based point-of-sale (POS) applications.

The label said command support ESC/POS, please read the docs before you ask.

**Comment by mike42** [comment]
This is correct. Since we each have different hardware, you are actually in the best position to find out whether this particular model works.

Once you've checked that the printer accepts ESC/POS, please step through the README and attempt a "Hello World" receipt, reporting back with what works (and doesn't work!).

There's also a bit more background at [Can you add support for Printer X?](https://github.com/mike42/escpos-php/blob/a79dc7516e71f0749ea081e95d7fdfec8ffbdbb9/doc/FAQ.md#can-you-add-support-for-printer-x) in the FAQ, which includes suggestions for how to get a printer "profile" set up for your make/model.
