### ISSUE TITLE
SEWOOTECH SLK-TL210

### ISSUE THREAD

**Issue by Kurwa** [mike42/escpos-php#266]
I just using the POS thermal printer from sewootech can you please chack if your library supports

**Comment by Kurwa** [comment]
Hello Guys Thanks for the library
 High speed printing : 

   SLK-T21EB II/SLK-TL212 II/SLK-TE212 II : 220mm/sec

   SLK-TE213 : 300mm/sec 

• Paper width adjustable : 50~82.5mm

• ESC/POS command compatible

• ASB(Auto Status Back) Function

It supports

**Comment by mike42** [comment]
Looks like your printer supports ESC/POS. Please consider submitting a test page and link to vendor documentation to the upstream [receipt-print-hq/escpos-printer-db](https://github.com/receipt-print-hq/escpos-printer-db) project to get better support for this printer ([example](https://github.com/receipt-print-hq/escpos-printer-db/issues/13)).

Since this is a common question, I've just updated the FAQ with [I have Printer X. Can I use this driver?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#i-have-printer-x-can-i-use-this-driver), which contains a bit more detail.

**Comment by Kurwa** [comment]
OK Thanks Mr Michael
but the BIG problem I have been facing is to locate or to Identify the
Logical device name of the pos printer
which I was expecting to have in OleSetup but didn't find it

**Comment by mike42** [comment]
I don't really understand how you're attempting to set up your printer, and maybe your printer's interface (USB, Ethernet, Serial?), and which platform you are running PHP on? (Windows, Linux, Mac?).

This driver generates binary ESC/POS code from PHP, so it's only useful if you know how to get raw data to your printer.

**Comment by Kurwa** [comment]
It works fine in PHP I tested already but I was developing the other
windows application using C# (C sharp)
if you dont mind can we chat in skype my account name is em-man3

**Comment by Kurwa** [comment]
The platform I'm using is Window 8.1 but developing Windows
application(desktop application) using C# programing language

**Comment by mike42** [comment]
Might have been a good idea to flag that in the issue. This is an issue tracker for escpos-php, not a place to request developer assistance with an unrelated program.

I'll close this issue as it's off-topic here, but your question may be more appropriately directed to a Q&A site like StackOverflow.
