### ISSUE TITLE
How to use feedForm()

### ISSUE THREAD

**Issue by ihussain1024** [mike42/escpos-php#289]
I want to roll back the paper before printing start so that the prints from starting of the paper.

Any help ?

**Comment by mike42** [comment]
`feedForm()` will eject tickets or pages on some printers.

What type of printer do you have, and how does it respond to `feedForm()`?

**Comment by ihussain1024** [comment]
Hi @mike42 
I am using EPSON LX-310
Actually I want the printer to roll back th paper before starting printing so that it can print from start of the paper

**Comment by mike42** [comment]
This library generates binary ESC/POS code, which is understood by some receipt printers. Since your printer is not an ESC/POS printer, this library is likely to be of little use.

The command-set of the Epson LX-310 is [ESC/P](https://files.support.epson.com/pdf/general/escp2ref.pdf), which is different to ESC/POS. I have no plan to expand the driver's purpose beyond generating ESC/POS, but I am open to reviewing pull requests that improve the output on ESC/P printers without breaking existing features.

There are existing tools (eg CUPS filters) that can convert PDF to ESC/P, these may be easier to apply to your use case.
