### ISSUE TITLE
Unable to print barcode using TSC TTP 345 printer

### ISSUE THREAD

**Issue by ihussain1024** [mike42/escpos-php#293]
Hi @mike42 
I've succeed bill printing by using your library in model EPSON LX-310.
Now I am trying to print barcode in model TSC TTP 345 by using your library, but I am not able to print. Showing no error. I don't know why not working.

Any help

**Comment by mike42** [comment]
Google suggests that this printer understands a vendor language named TSPL/TSPL2 natively, rather than ESC/POS.

This library only speaks ESC/POS, so unless it can be set to an ESC/POS emulation mode, the code generated by this library will not be understood by your printer.

Aside, I don't think the Epson LX series are ESC/POS either, would be interested to see any snippets you have to get an idea of how it works

**Comment by ihussain1024** [comment]
Ya it works with Epson LX series
I just downloaded your library and placed it in root folder and  I followed some commands as below

1.     sudo usermod -a -G lp computer_user_name
2.     sudo gpasswd -a ww-data lp
3.     lpadmin -p localhost
4.     sudo rmmod usblp
5.     Then restart the computer
6.     Test printing
 It really works for me.

**Comment by ihussain1024** [comment]
Hey @mike42 
Can you just suggest me what kind of printer should I use so that I can print bar code by using your library.

**Comment by mike42** [comment]
Good to hear. Still surprised you get any output.

As always, while we're not in a position to maintain implementations of other printing languages, but I'm open to reviewing pull requests which improve compatibility for other printers without if it can be done without breaking the ESC/POS output.

I think I used an Epson TM-T88II and TM-T20 to write this, both have excellent command sets.
