### ISSUE TITLE
capabilities.json 'column' design oversimplistic

### ISSUE THREAD

**Issue by globalcitizen** [mike42/escpos-php#299]
Font columns is not always constant, and is therefore insufficient to accurately describe output capabilities. 

For example on the Q583P:
 - If I print Chinese I get 16 characters width in all fonts.
 - If I print numbers, I get 33 characters width in all fonts.
 - I can mix these on one line.
 - I have not shifted codepage.

Also, rotated printing (`ESC V n`) support breaks column width assumptions.

**Comment by mike42** [comment]
All good points. I'm going to close this off as invalid, because we don't maintain the capabilities database in this repository, and the driver does not currently use the font width values from the database.

This info is expressed as character/line because it appears on data sheets from the vendors using those units. If you have a better representation for widths in the database in mind, I would suggest sending improvements to [receipt-print-hq/escpos-printer-db](https://github.com/receipt-print-hq/escpos-printer-db).

Aside, I'm open to reviewing any pull requests that add word-wrap (eg. on spaces) to the driver. It's possible to calculate dots/character from characters/line and dots/line for monospace fonts, and most ESC/POS printers do not print characters with unusual widths without explicitly changing fonts (ie, `FONT A` and `FONT B` each have fixed widths on my TM-T20, including numerals)

We do not implement page mode ( #216 ), page bounds for the rotated text are not currently known to the driver.
