### ISSUE TITLE
Uploading the Project in a Live Server and using the Printer installed in that PC.

### ISSUE THREAD

**Issue by ashryverrr** [mike42/escpos-php#303]
Hi, it's my first time asking so please bear with me. I am using escpos in my localhost and so far I got it running, using all the commands. 
But now we uploaded my project to a web hosting, and I am having problems printing since I think that it cannot the detect the printer connected to the PC.  Can anybody help me or point me in the right direction on how to solve this problem? Thank You.

EDIT: Nevermind, please close this. I've read through the faq and saw that I have to use/find another library to help me with this.

**Comment by mike42** [comment]
No worries. For future readers, the relevant section of the FAQ is [Can I print from my server on the Internet?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#can-i-print-from-my-server-on-the-internet).

**Comment by mutiemule** [comment]
Printing on local will work well with this package.

However, to print online, you will need to develop a desktop service which has to be installed on the local computer where you need printing to be done.  This is because PHP is a server-side scripting language, so once you put this online, it won't be able to communicate to the local printer. Thus, you need a client service running on the local machine and this is where electron js and node js come into play.

I resolved this by developing an electron js service based on [node-escpos package](https://www.npmjs.com/package/escpos) which can receive commands from the online print command and then communicate those commands to the printer through USB. 

Operating System does not matter in this case, you can be hosting on Linux based server and printing on a windows server. This desktop service interfaces between the online service and the local service. 

You can check out the [node-escpos printer driver package ](https://github.com/song940/node-escpos) for some inspiration on how to go about this.

Check the [FAQs on how to print online](https://github.com/mike42/escpos-php/blob/fe9350e61fb5e38416ec6243873c37fa65f34eb5/doc/FAQ.md#can-i-print-from-my-server-on-the-internet) to have some pointers too.
