### ISSUE TITLE
New Driver

### ISSUE THREAD

**Issue by Skymidt** [mike42/escpos-php#316]
In brazil we work with Bematech printers. Precisely MP 4200 TH. His site have drivers and support things as manual (in our language).

**Comment by mike42** [comment]
Have you been able to test the printer in `escpos-php`? Which features work?

If you are getting some output, you might like to consider adding a new profile to the [receipt-print-hq/escpos-printer-db](https://github.com/receipt-print-hq/escpos-printer-db) so that text and images can be encoded correctly (a good example profile might be [POS-5890](https://github.com/receipt-print-hq/escpos-printer-db/blob/1627fa4f09949b3f43ab598278ead7786593eada/data/profile/POS-5890.yml)). I was able to find [this ESC/POS](http://www.bematech.com.br/administrador/files/equipamento/suporte/17/1394308953-Impressora_MP-4200TH_Manual_01_Manual_de_Programacao.pdf) manual on the Bematech website, which has all the information in it.

**Comment by gcardozo2809** [comment]
Hi @Skymidt , did you set up a profile for this? Would you share some info about how you set the printer up? I am doing it with an MP 4000 TH and all I get is random characters, it might be a driver issue.
