### ISSUE TITLE
Use variable to set Printer?

### ISSUE THREAD

**Issue by osvaldoalvaradodev** [mike42/escpos-php#337]
I everyone !!! 

I was try to set different printers, this printer as STRING loading of my BD. 
I use string to set name of printer, but this show me error.

Can i transform "string" to set name of printer?

```
//$printername = "Epson1"... "Epson2"...
$printername = "Epson1"
$connector = new WindowsPrintConnector($printername);

    /* Print a "Hello world" receipt" */
    $printer = new Printer($connector);
```

**Comment by Stenerson** [comment]
Hi @osvaldoalvaradodev, this definitely works and is probably how most people use the library (certainly myself included). 

It's likely that any error you're getting is related to the value of the string, rather than because a variable is being used. Could you post some more information as to how you set up the printer and what error you're getting? Thanks!
