### ISSUE TITLE
Star TSP100 Printer + Logo

### ISSUE THREAD

**Issue by Tif2310** [mike42/escpos-php#344]
Hi, 

I have a Star TSP100 printer, I'm running print tests with logos but only prints Ascii codes instead of the image. Could you help me?

Regards!

![scan](https://cloud.githubusercontent.com/assets/27514628/25053989/4ecf6aa2-2120-11e7-867f-8c1bff106c53.jpg)

This is code:
```
<?php
require __DIR__ . '/pos/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\EscposImage;
try {
    

$img = EscposImage::load("img/logo.png");   
    $connector = null;   
    $connector = new WindowsPrintConnector("smb://MOUNTRAK-ONLINE/tickets");    
    $printer = new Printer($connector);
    $printer -> graphics($img);    
    $printer -> text("Hello World! Tifo Super \n");
    $printer -> cut(Printer::CUT_PARTIAL,50);
    
   
    $printer -> close();
} catch (Exception $e) {
    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}
```

**Comment by mike42** [comment]
Not all printers speak the same type of ESC/POS, and it looks like yours does not support the `graphics()` command.

You might have better luck if you replace `graphics()` with a call to `bitImage()` or `bitImageColumnFormat()`.

The driver will eventually ship with a profile for each printer ([receipt-print-hq/escpos-printer-db](https://github.com/receipt-print-hq/escpos-printer-db)), which will allow the driver adjust its output to avoid this sort of issue. You should consider using the SP2000 profile until a TSP100 profile is available, so that you can avoid compatibility issues around text encoding.

The SP2000 is also made by Star, and is much closer to a TSP100 than the default profile, which is made for Epson-branded printers.

```
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\CapabilityProfile;
use Mike42\Escpos\Printer;

$profile = CapabilityProfile::load("SP2000")
$connector = new WindowsPrintConnector("smb://MOUNTRAK-ONLINE/tickets");    
$printer = new Printer($connector, $profile);
```

**Comment by Tif2310** [comment]
Mike!!!

Very, vary Thanks!! Work this code:

```

<?php
require __DIR__ . '/pos/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\CapabilityProfile;
use Mike42\Escpos\EscposImage;

$profile = CapabilityProfile::load("SP2000");
$connector = new WindowsPrintConnector("smb://MOUNTRAK-ONLINE/tickets");    
$printer = new Printer($connector, $profile);
$img = EscposImage::load("img/logo.png"); 
$printer -> bitImageColumnFormat($img);    
    $printer -> text("Hello World! Tifo Super \n");
    $printer -> cut(Printer::CUT_PARTIAL,50);
    $printer -> close();
![win_20170420_18_36_08_pro 3](https://cloud.githubusercontent.com/assets/27514628/25257097/4000fb14-25fb-11e7-8227-ab622b28608b.jpg)


```

**Comment by Tna99** [comment]
IS TSP800 is also similar to SP2000?
