### ISSUE TITLE
How do I decode the escpos binary correctly

### ISSUE THREAD

**Issue by asoneji** [mike42/escpos-php#350]
Here I have a simple code that generates escpos binary.

```
<?php

require __DIR__ . '/../vendor/autoload.php';

use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\DummyPrintConnector;

$connector = new DummyPrintConnector();
$printer = new Printer($connector);

$printer -> text("EN ESPAÑOL\n");

$data = $connector -> getData();

header('Content-type: application/octet-stream');
header('Content-Length: '.strlen($data));

$file = "temp.bin";
file_put_contents($file, $data);
$printer -> close();
?>
```
When I see the hexdump of the file I see the following:
`> hexdump -C temp.bin`
![hexdump](https://cloud.githubusercontent.com/assets/5489067/25258504/ba8934d4-25f4-11e7-8611-d70c0a78c0e0.png)

In hexdump **Ñ** = **a5**. Now how do I go from **a5** to **Ñ**. When I do hex to string for **a5** I get **¥**. I think I am doing something incorrectly. I was wondering if you can provide some insight to what the correct way I should decode the hex to string.

**Comment by Stenerson** [comment]
@asoneji There are some utilities that are maintained in a separate library to convert esc/pos back to text. Is that what you're looking for? 

Here's the link: https://github.com/receipt-print-hq/escpos-tools

**Comment by asoneji** [comment]
@Stenerson I am aware of [escpos-tools](https://github.com/receipt-print-hq/escpos-tools). Similar to that I am decoding the message and having an issue. I am not able to decode correctly as described in the question.

**Comment by mike42** [comment]
Fun question.

**Short answer:**  [CP437](https://en.wikipedia.org/wiki/Code_page_437) was used to encode all of that text. To reverse it, a minimal example might be-

```
$ echo -e '\x45\x53\x50\x41\xa5\x4f\x4c' | iconv --from-code=CP437 --to-code=UTF-8
ESPAÑOL
```

**Long answer:** In this project, you will find that ESC/POS printers are assumed to universally understand legacy code page [CP437](https://en.wikipedia.org/wiki/Code_page_437). They also and accept a command to switch the code page so that they can print other languages. This library will accept UTF-8 text, and then switches code pages as often as necessary to encode other languages.

So your decoding algorithm would be:

- start extracting text by converting CP437 to UTF-8.
- if you find a code page switch (`ESC t`), you then look up which code page is now being used (data is in `capabilities.json`), and start converting from that code page to UTF-8 instead.
- if you hit a re-initialization (`ESC @`), then go back to CP437.

(Aside: [escpos-tools](https://github.com/receipt-print-hq/escpos-tools) is only correct for ASCII at the moment, but code page support is coming. See receipt-print-hq/escpos-tools#5 for progress on that)
