### ISSUE TITLE
Client server socket

### ISSUE THREAD

**Issue by nitinsbuzz** [mike42/escpos-php#369]
Right now you have the option to use the network connector to connect (tcp://?) to a server to send data. Maybe an option to add a client and server script in the future that allows a permanent connection from a remote area (behind a home router for example) that listens to print commands.

**Comment by mike42** [comment]
This is an interesting feature request. We get a lot of traffic on this issue tracker from setups where a print kiosk is behind a NAT (such as a home router), while the print server is on the Internet.

I'm not a fan of long-running PHP processes, but I'll leave this issue open until we have a good, general solution to getting the print data delivered in this sort of setup.

Previous work in this area include-

- The FAQ suggests the use of a secure tunnel to expose a shared printer, since encryption and authentication are practically mandatory once your traffic is going across a WAN. In practice, OpenVPN or an SSH tunnel is the easiest way to achieve this.
- We do have an "API print connector" which allows `escpos-php` to connect out to a listening webserver. The webserver receiving the connections is then configured with its own `PrintConnector` to pass on the job. This will not work through a NAT unless you open ports.

**Comment by nitinsbuzz** [comment]
I did it with ratchet and web sockets. If you are interested in this solution. I can post it here. It is only a few lines of code.

**Comment by mike42** [comment]
I would be interested to see, would you mind posting it?

**Comment by nitinsbuzz** [comment]
I will rewrite my solution and post the solution as soon as i can.

**Comment by mike42** [comment]
I've considered this feature request, and I'm going to close it as an unwanted feature.

We can do LAN printing via standard protocols, and `stunnel`, `SSH` or `OpenVPN` can make anything look like a LAN via standard protocols. That is sufficient, and not every problem needs to be solved from PHP.

**Comment by mutiemule** [comment]
Printing on local will work well with this package.

However, to print online, you will need to develop a desktop service which has to be installed on the local computer where you need printing to be done.  This is because PHP is a server-side scripting language, so once you put this online, it won't be able to communicate to the local printer. Thus, you need a client service running on the local machine and this is where electron js and node js come into play.

I resolved this by developing an electron js service based on [node-escpos package](https://www.npmjs.com/package/escpos) which can receive commands from the online print command and then communicate those commands to the printer through USB. 

Operating System does not matter in this case, you can be hosting on Linux based server and printing on a windows server. This desktop service interfaces between the online service and the local service. 

You can check out the [node-escpos printer driver package ](https://github.com/song940/node-escpos) for some inspiration on how to go about this.

Check the [FAQs on how to print online](https://github.com/mike42/escpos-php/blob/fe9350e61fb5e38416ec6243873c37fa65f34eb5/doc/FAQ.md#can-i-print-from-my-server-on-the-internet) to have some pointers too.
