### ISSUE TITLE
hello, how to support chinese charset!

### ISSUE THREAD

**Issue by uxnow** [mike42/escpos-php#37]
do I need to create  an $profile, and how! thanks.

**Comment by mike42** [comment]
Hi uxnow,

There is currently [no support for Chinese characters](https://github.com/mike42/escpos-php/blob/1d8052d42041dcd3d527e8d51647cf3db511441b/test/unit/EscposPrintBufferTest.php), simply because nobody has requested it yet (also, the printer I test this driver on does not print Chinese).

So that I can look at this in more detail, please let me know a few things:
- What manufacturer and model is your printer?
- Does your printer have documentation available which lists supported code pages? (if so, please send a link!)
- Do you have some sample text which I can use for testing?

**Comment by bobbyhsu** [comment]
Hi mike42,

Is this still work in progress? Printing Chinese characters? I am using a Espon ID80TP.

Thanks

Bobby

**Comment by mike42** [comment]
Hi, no progress on this, simply because more information is needed-

- Does your printer have documentation available which lists supported code pages? (if so, please send a link!)
- Do you have some sample text which I can use for testing?
 - A good mix of letters, numbers, currency symbol

At this stage, it's most likely that I'll first try to render the sample text to an image for printing (using `ImagePrintBuffer` and an appropriate font), and then if the documentation is suitable, have a shot at encoding the characters directly in ESC/POS.

**Comment by bobbyhsu** [comment]
The document is buried inside a download link and it is in chinese. So I just copy paste what I think is relevant. Hope it is not too muich:

The following is a list of character set supported, the default character set is RT_CS_CP437. 

RT_CS_CP437	0	CP437【US，European standard】
CS_KATAKANA	1	KataKana【KataKana】
CS_CP850	2	CP850【multilingual】
CS_CP860	3	CP860【Portugal】
CS_CP863	4	CP863【Canada - French】
CS_CP865	5	CP865【Nordic】
CS_WP1251	6	WCP1251【Cyrillic】
CS_CP866	7	CP866【Slavic2】
CS_MIK	8	MIK【Slavic / Bulgarian】
CS_CP755	9	CP755【Eastern Europe, Latvia2】
CS_CP862	15 CP862【Hebrew】
CS_WCP1252	16	WCP1252【 Latin1】
CS_WCP1253	17	WCP1253【Greece】
CS_CP852	18	CP852【Latin2】
CS_CP858	19	CP858【Latin characters1+European languages】
CS_IRANII	20	Iran II【Persian】 RT_CS_LATVIA	21	Latvia
CS_CP864	22	CP864【Arabic】
CS_ISO88591	23	ISO-8859-1【Western Europe】
CS_CP737	24	CP737【Greece】
CS_WCP1257	25	WCP1257【Baltic】
CS_THAI	26	Thai
CS_CP720	27	CP720【Arabic】
CS_CP855	28	CP855
CS_857	29	CP857【Turkish】
CS_WCP1250	30	WCP1250【Central Europe】	RONGTA Printer	8
CS_CP775	31	CP775
CS_WCP1254	32	WCP1254【Turkish】
CS_WCP1255	33	WCP1255【Hebrew】
CS_WCP1256	34	WCP1256【Arabic】
CS_WCP1258	35	WCP1258【Vietnamese】
CS_ISO88592	36	ISO-8859-2【Latin2】
CS_ISO88593	37	ISO-8859-3【Latin3】
CS_ISO88594	38	ISO-8859-4【Baltic】
CS_ISO88595	39	ISO-8859-5【Cyrillic】
CS_ISO88596	40	ISO-8859-6【Arabic】
CS_ISO88597	41	ISO-8859-7【Greek】
CS_ISO88598	42	ISO-8859-8【Hebrew】
CS_ISO88599	43	ISO-8859-9【Turkish】
CS_ISO885915	44	ISO-8859-15【9Latin 9】
CS_THAI2	45	【Thai 2】
CS_CP856	46	CP856
CS_CP874	47	CP874	

The following is a list of supported international character set, the default character set is RT_ICS_CHINESE

ICS_USA	0	United States
ICS_FRANCE	1	France
ICS_GERMANY	2	Germany
ICS_ENGLAND	3	British
ICS_DENMARKI	4	Denmark I
ICS_SWEDEN	5	Sweden
ICS_ITALY	6	Italy
ICS_SPAINI	7	Spanish I
ICS_JAPAN	8	Japan
ICS_NORWAY	9	Norway
ICS_DENMARKII	10	Denmark II
ICS_SPAINII	11	Spain II
ICS_LATIN	12	Latin America
ICS_KOREAN	13	Korea
ICS_SLOVENIA	14	Slovenia
ICS_CHINA	15	China	RONGTA Printer	9	

About the ImagePrintBuffer, I am new to php and I don't have ImageMagic extenntion so it won't work for me.

**Comment by bobbyhsu** [comment]
Some text examples:

艾德蒙 AOC E2450SWH 23.6吋 LED液晶寬螢幕特價$ 19900

**Comment by bobbyhsu** [comment]
Hi mike42,

Any updates?

**Comment by kwangwei** [comment]
hi @bobbyhsu , did you manage to figure this out somehow? i experience similar problems.

**Comment by bobbyhsu** [comment]
In Escpos.php, I change the text() method to the following and it works.

The data in my input is in UTF-8 code format. So i figure if I can target the data and convert to GBK or BIG5 code and send send it to printer and it did work. My printer is RT80 with Chinese character fonts loaded. So this only work if your printer loads with Chinese fonts.

Here is the code.

$str = iconv("UTF-8","GBK//IGNORE",$str); // added for converting to GBK data format
$this->buffer->writeText((string)$str);

Since all my output is goign to be GBK, so it is easier for me just change text() in Escpos.php. If you have other coding, then you need to write a wraper around this text() to accommodate another non-english characters.

Hope this help.

**Comment by kwangwei** [comment]
Thanks. On top of tht i had to 'On' chinese characters by lifting a switch below. Its finally working. thanks!

**Comment by mike42** [comment]
Based on what @bobbyhsu has posted, I've added a function to the main library which tells the printer to expect GBK text, sends some GBK (converted from UTF-8), and switches back to 'alphanumeric' when done.

Use it like this-

````php
require __DIR__ . '/vendor/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;
use Mike42\Escpos\CapabilityProfiles\SimpleCapabilityProfile;

$connector = new FilePrintConnector("/dev/usb/lp1");
$profile = SimpleCapabilityProfile::getInstance();

$printer = new Printer($connector);
// Note that on the printer tested (ZJ5890), the font only contained simplified characters.
$printer -> textChinese("示例文本打印机!\n\n");
````

This has been tested on a ZJ5890T. For other printers, you may have to make changes, such as-
- change a DIP switch
- remove the "FS." and "FS&" in the new function, or
- change GBK to BIG5.

Please write a new bug report if the new method does not work for you, or if you had to modify it to work with your printer. You can include information such as your printer model, a sample string, a code snippet and picture of the output, or a link to the manufacturer documentation. This information will help others to get their printers working as well.

----

New snippet-

````php
	/**
	 * Add Chinese text to the buffer. This is a specific workaround for the common Zijian printer- The printer will be switched to a two-byte mode and sent GBK-encoded text.
	 * 
	 * Support for this will be merged into a print buffer.
	 * 
	 * @param string $str Text to print, as UTF-8
	 */
	function textChinese($str = "") {
		self::validateString($str, __FUNCTION__);
		$this -> connector -> write(self::FS . "&");
		$str = iconv("UTF-8","GBK//IGNORE", $str);
		$this -> buffer -> writeTextRaw((string)$str);
		$this -> connector -> write(self::FS . ".");
	}
````

**Comment by dhanasekarperiaswamy** [comment]
with the new snippet, I tried to print registered trademark and trademark symbols but could not print. I tried replacing IGNORE with TRANSLIT as per https://stackoverflow.com/questions/8727735/iconv-detected-an-illegal-character-in-input-string. With this new change, at least I get R and TM within braces so that I replace with required characters. Hope this helps.
