### ISSUE TITLE
load pdf error

### ISSUE THREAD

**Issue by sunry2ntkh** [mike42/escpos-php#370]
'ImagickException' with message 'NoDecodeDelegateForThisImageFormat `PDF' @ error/constitute.c/ReadImage/501' in C:\wamp64\www\LibraryPrinter\escpos\src\Mike42\Escpos\ImagickEscposImage.php on line 228

**Comment by mike42** [comment]
@sunry2ntk - You can find with [a web search](https://www.google.com/search?q='NoDecodeDelegateForThisImageFormat+`PDF') that this is an ImageMagick issue, not an `espos-php` issue.

Since this is the 9th issue that you have posted to this repository in a short time, I would like to kindly ask you to do some basic research and troubleshooting before you post again.

We have a small group of core contributors who answer questions on this tracker on a voluntary basis. I believe that it's important to show value for their time by only asking well-researched questions which are specific to this project.
