### ISSUE TITLE
How can i make a website connect directly to a local printer? so that it can print out the orders directly in my local printer

### ISSUE THREAD

**Issue by raghurajsingh** [mike42/escpos-php#38]
Please visit this link and help me regarding printer issues.  http://strikerinfotech.com/project/orderonline/update/

**Comment by mike42** [comment]
Hello,

Unfortunately, you haven't provided any information about what the issues are, so I'm just sending back some questions to find out what your use case is.

Probably best to start with:

- Make & model of printer ([list of tested printers](https://github.com/mike42/escpos-php#interfaces-and-operating-systems)).
- What platform the server runs, and how you expect it to speak to the receipt printer (USB, ethernet, serial, Windows share?) -- [list of tested interfaces & platforms](https://github.com/mike42/escpos-php#interfaces-and-operating-systems).
- An indication of whether you've already been able to print [the "Hello World" example](https://github.com/mike42/escpos-php#basic-usage) from the target machine.

If you have the "Hello World" receipt working on the target machines, please post a bit about what you're attempting (user story or draw a receipt), how you're trying to use escpos-php for it (code snippet), and what happens when you try to run it (error message, scanned receipt, or some other unexpected output).

**Comment by dumshi** [comment]
The idea of having your printer exposed to the world is just too unsafe.
It invites a lot of problem. One only needs to port scan your IP and find all open ports for attackers to start messing around.

You can successfully make your Receipt Printer "LIVE" online for your application.
But again, why do that and risk security? And who in their right mind would buy your product?

You need to think of a workaround. Perhaps a medium through which you can print safely.

**Comment by mike42** [comment]
This is a PHP receipt printer driver, so the computer hosting PHP and the printer need to be able to speak to each-other through a supported interface. The standard work-around for connecting networks over the internet is of course VPN, 


Please try to provide the [requested information about your setup](https://github.com/mike42/escpos-php/issues/38#issuecomment-120858977) if you are interested in a proper response, as there isn't enough information here to write up code snippets or examples.

**Comment by deep97** [comment]
Hi mike, I am willing to do same thing. What I am doing. keeping whole folder of escpos on my local computer C:\wamp\www\escpos-php-master. and trying to call C:\wamp\www\escpos-php-master\Escpos.php from online file. like adding below to my online file on server. I am using windows.

require_once(dirname(__FILE__) . "/escpos/Escpos.php");
	$connector = new WindowsPrintConnector("Receipt Printer");
	$printer = new Escpos($connector);

But getting error saying

Warning: copy(\\Front\Receipt Printer): failed to open stream: No such file or directory in C:\wamp\www\escpos\src\WindowsPrintConnector.php on line 339

if I change file location to
require_once("C:/wamp/www/escpos/Escpos.php");

it give error
Warning: require_once(C:/wamp/www/escpos/Escpos.php): failed to open stream


Thanks

**Comment by mike42** [comment]
Closing this off as it's become out of date, see #121 for the most recent suggestions on printing across networks.

**Comment by srram070** [comment]
Hello Mike,

I am working to fix this issue for last two days, i am getting tired to fix this, i had seen some solution but not yet get output.

- I am Developing web application for pos billing using php, i have to provide the pos bill to the customer, i have installed (xprinter, xp-80c) in my pc, it working good in my localhost, there is no issue in my local.

- But whenever i put it on live i had received the following error !

- Couldn't print to this printer: Failed to print. Command "smbclient '//node2.indservers.co.in/xp-80c' -c 'print -' -N -m SMB2" failed with exit code 127: sh: smbclient: command not found

**TRIED SOLUTIONS**

- This is my printer connection in local system which is working good
$connector = new WindowsPrintConnector("xp-80c");

- I had tried the first solution with computername Like
\\%COMPUTERNAME%\Receipt Printer

- So i just tried with my computer name (\\DESKTOP-B55P4FG)
$connector = new WindowsPrintConnector("\\DESKTOP-B55P4FG\xp-80c");
Failed again 
ERROR : Couldn't print to this printer: Printer '\DESKTOP-B55P4FG\xp-80c' is not a valid printer name. Use local port (LPT1, COM1, etc) or smb://computer/printer notation.

- Second i tried with share port name Like (USB001) 
$connector = new WindowsPrintConnector("\\DESKTOP-B55P4FG\USB001\xp-80c");
Failed again 
ERROR : Couldn't print to this printer: Printer '\DESKTOP-B55P4FG\USB001\xp-80c' is not a valid printer name. Use local port (LPT1, COM1, etc) or smb://computer/printer notation.

-Finally i tried with another solution its about Extension from server to local printer in(#121 )
in that page you mention to add a plugin called "Raw Printer Connecter" but after installing it shows the same error, So Can You Please Help For This.

My Full Code On Local ( Working Perfect) : 

<?php
/* Change to the correct path if you copy this example! */
require __DIR__ . '/escpos/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;

/**
 * Install the printer using USB printing support, and the "Generic / Text Only" driver,
 * then share it (you can use a firewall so that it can only be seen locally).
 *
 * Use a WindowsPrintConnector with the share name to print.
 *
 * Troubleshooting: Fire up a command prompt, and ensure that (if your printer is shared as
 * "Receipt Printer), the following commands work:
 *
 *  echo "Hello World" > testfile
 *  copy testfile "\\%COMPUTERNAME%\Receipt Printer"
 *  del testfile
 */

//echo "<pre>";print_r($info);echo"</pre>";
function addSpaces($string = '', $valid_string_length = 0) {
    if (strlen($string) < $valid_string_length) {
        $spaces = $valid_string_length - strlen($string);
        for ($index1 = 1; $index1 <= $spaces; $index1++) {
            $string = $string . ' ';
        }
    }

    return $string;
  }
try {
    // Enter the share name for your USB printer here
    //$connector = null;
    $connector = new WindowsPrintConnector("xp-80c");

    /* Print a "Hello world" receipt" */
    $printer = new Printer($connector);    
    $printer->setJustification(Printer::JUSTIFY_CENTER);
    $printer -> setTextSize(2, 1);
    $printer -> text("CASH BILL\n");
    $printer -> text("ALL DATA\n");
    $printer -> cut();
    
    /* Close printer */
    $printer -> close();

} catch (Exception $e) {
    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}

//Local Code End


//Full code on online Start - ERROR (Couldn't print to this printer: Printer '\DESKTOP-B55P4FG\xp-80c' is not a valid printer name. Use local port (LPT1, COM1, etc) or smb://computer/printer notation.)

<?php
/* Change to the correct path if you copy this example! */
require __DIR__ . '/escpos/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;

/**
 * Install the printer using USB printing support, and the "Generic / Text Only" driver,
 * then share it (you can use a firewall so that it can only be seen locally).
 *
 * Use a WindowsPrintConnector with the share name to print.
 *
 * Troubleshooting: Fire up a command prompt, and ensure that (if your printer is shared as
 * "Receipt Printer), the following commands work:
 *
 *  echo "Hello World" > testfile
 *  copy testfile "\\%COMPUTERNAME%\Receipt Printer"
 *  del testfile
 */

//echo "<pre>";print_r($info);echo"</pre>";
function addSpaces($string = '', $valid_string_length = 0) {
    if (strlen($string) < $valid_string_length) {
        $spaces = $valid_string_length - strlen($string);
        for ($index1 = 1; $index1 <= $spaces; $index1++) {
            $string = $string . ' ';
        }
    }

    return $string;
  }
try {
    // Enter the share name for your USB printer here
    //$connector = null;
    $connector = new WindowsPrintConnector("\\DESKTOP-B55P4FG\xp-80c");

    /* Print a "Hello world" receipt" */
    $printer = new Printer($connector);    
    $printer->setJustification(Printer::JUSTIFY_CENTER);
    $printer -> setTextSize(2, 1);
    $printer -> text("CASH BILL\n");
    $printer -> text("ALL DATA\n");
    $printer -> cut();
    
    /* Close printer */
    $printer -> close();

} catch (Exception $e) {
    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}

//Error : Couldn't print to this printer: Printer '\DESKTOP-B55P4FG\xp-80c' is not a valid printer name. Use local port (LPT1, COM1, etc) or smb://computer/printer notation.

**Comment by vstarkx** [comment]
@srram070   hi hello have you solved the problem?

**Comment by ejie13** [comment]
@mike42 is there possible way for you to work with it and give us a price to buy it?

**Comment by srram070** [comment]
Hi ejie, yes I have solved it, but not connected directly as well because we can't point the local printer from server, because of security reason it will not allow to connect with local printer, but I found a solution with other way

**Comment by srram070** [comment]
1. Where are you calling from?
2. are you a developer? 

3. Which domain do you used for develop the software ? 

4. Do you need a full system or need a code level support? 

5. You looking for full time supporter or for solve this issue only?
