### ISSUE TITLE
WindowsPrintConnector: Permission denied when printing to LPT1 

### ISSUE THREAD

**Issue by fanhur82** [mike42/escpos-php#380]
I'm trying to print from my computer which connected the printer directly (LPT1)
But when I'm trying to print from the web page I get this error : "Warning: file_put_contents(LPT1): failed to open stream: Permission denied in C:\xampp\htdocs\POS\src\Mike42\Escpos\PrintConnectors\WindowsPrintConnector.php on line 384 Couldn't print to this printer: Failed to write file to printer at LPT1 "
i try to use this code
![php](https://user-images.githubusercontent.com/29400661/27078820-659d4f24-505f-11e7-93b1-3cc8b39984fa.PNG)

**Comment by Stenerson** [comment]
Hi @fanhur82! I'm unable to help with your specific issue due to lack of experience on your platform but I just want to make sure you've seen the [FAQ](https://github.com/mike42/escpos-php/blob/development/doc/FAQ.md#why-do-i-get-this-error-when-i-try-to-print). Often times the answers here may help point you in the right direction if you haven't already looked it over.

This in particular *may* be helpful in your case:

> Lastly, you may run in to the final common trap:
> Your PHP is not running with the same sort of permissions as your login account. Again, no amount of PHP code can fix this. For example, on LAMP, your www-data user needs to be in the lp group, while on WAMP, Local Service account may run in to problems. SELinux and firewalls are also worth a look.

If this doesn't help, can you list out any troubleshooting steps you have taken?

**Comment by mike42** [comment]
Assuming this is abandoned, closing.
