### ISSUE TITLE
Trying to print the euro symbol

### ISSUE THREAD

**Issue by LorenzoLa** [mike42/escpos-php#385]
What should I do to print the euro symbol using escpos-php v1.5.1?

So far I have tried: $printer -> text("€");

I'm using the Epson TM-T88IV printer and get in stead of the euro symbol the character "ç".

**Comment by mike42** [comment]
Hi, could you please post a complete snippet so that I can see how you are setting up the printer as well?

**Comment by LorenzoLa** [comment]
Hi, thx for replying ! The code I use:

<?php

require __DIR__ . '/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;

try {
	// Enter the share name for your USB printer here
	$connector = new WindowsPrintConnector("Receipt Printer");
	$printer = new Printer($connector);

	/* Printing Pound Symbol: */
	/* Result: Able To Print The Pound Symbol - ASCII Code For Pound Symbol: 156 */ 
	$printer -> text(chr(156));
	$printer -> feed();
	
	/* Printing Euro Symbol: */
	/* Result: Not Able To Print The Euro Symbol */ 	
	$printer -> text("€");
	$printer -> feed();
	
	$printer -> text("\xE2\x82\xAc");
	$printer -> feed();
	
	$printer -> text(chr(128));	
	$printer -> feed();
		
	$printer -> cut();
	
	/* Close printer */
	$printer -> close();
} catch(Exception $e) {
	echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}

**Comment by LorenzoLa** [comment]
![eurosymbol_printing](https://user-images.githubusercontent.com/29844733/27790966-c1cccfd2-5fea-11e7-8c76-e2559be12536.PNG)

**Comment by LorenzoLa** [comment]
Any inspiration folks?

**Comment by LorenzoLa** [comment]
Working with the example: "https://github.com/mike42/escpos-php/blob/development/example/character-tables.php".
How should I print with code page "CP1252", which is supported by my printer?

**Comment by mike42** [comment]
The driver can do the encoding for this printer, but the Epson TM-T88IV needs a printer profile made in the `escpos-printer-db` which lists the correct encodings.

Check out this URL for details:

- https://github.com/receipt-print-hq/escpos-printer-db/blob/master/doc/add-your-printer.md

### Background

If you want some detail on what is going on, the symbol works on the TM-T20II:

```php
<?php
require __DIR__ . '/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;

$connector = new FilePrintConnector("php://stdout");
$printer = new Printer($connector);

$printer -> text("€\n");

$printer -> cut();
$printer -> close();
```

It does these commands:

Initialise:

```
1b 40
```

Switch to code page `0x0f` (numbers are printer-specific!):

```
1b 74 0f
```

Euro sign (0xa4 in whatever code-page this is plus newline):

```
a4  0a
```

Cut

```
1d 56 41 03
```

It looks like sign `0xa4` in code page `0x0f` is a ç.

### Real solution

The solution is to **add a new profile to the printer database**, so that you can set up the printer like so:

```php
...
$profile = CapabilityProfile::load("TM-T88IV")
$printer = new Printer($connector, $profile);
...
```

### Workaround

As a hack, you can send bytes directly to the `$connector` to print a Euro on this specific printer, but please don't complain about the driver output if you are using the wrong profile *and* setting the printer state outside of the driver, since you can kind of expect to have problems :)

```php
$printer -> text("LALALA ");
$connector -> write("\x1b" . "t" . chr(16) . chr(128));
$printer -> text("\n");
```

**Comment by CodeNinja1337** [comment]
> ### Real solution
> The solution is to **add a new profile to the printer database**, so that you can set up the printer like so:
> 
> ```
> ...
> $profile = CapabilityProfile::load("TM-T88IV")
> $printer = new Printer($connector, $profile);
> ...
> ```

This worked perfect for me ( Bixolon SRP-350plus||| )
Thanks!
