### ISSUE TITLE
setTextSize doesn't work

### ISSUE THREAD

**Issue by andreaschrist27** [mike42/escpos-php#389]
here's my code : 
```php
<?php
require __DIR__ . '/vendor/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
try {
	// Enter the share name for your USB printer here
	$connector = new WindowsPrintConnector("Antrian");
	$printer = new Printer($connector);

	/* Print some bold text */
	$printer -> setEmphasis(true);
	$printer -> setTextSize(7, 7);
	$printer -> text("FOO CORP Ltd.\n");
	$printer -> setEmphasis(false);
	$printer -> feed();
	$printer -> text("Receipt for whatever\n");
	$printer -> feed(4);

	/* Bar-code at the end */
	$printer -> setJustification(Printer::JUSTIFY_CENTER);
	$printer -> barcode("987654321");

	/* Close printer */
	$printer -> close();
} catch(Exception $e) {
	echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}
```

**Comment by mike42** [comment]
Could you share some information about your setup and what you are trying to print? Eg.

- The printer make/model.
- Whether other ESC/POS commands have been successful so far.
- A description of what happens when you run this code, and how this differs from what you are expecting.

We have demonstrations at `text-size.php` and `demo.php`, which you should try out in the first instance- There is also a possibility that your printer cannot render text this large (7x7 is huge!).

**Comment by asepmaryana** [comment]
Hi Mike, 
I want to print like this (text bold and big "**C 014**"), can you give me sample code.
Thanks.

![WhatsApp Image 2019-11-18 at 19 57 52](https://user-images.githubusercontent.com/4230394/69110383-2b484d00-0aad-11ea-8bd3-ec244f29dc54.jpeg)
