### ISSUE TITLE
failed to open stream: Permission denied

### ISSUE THREAD

**Issue by roro1981** [mike42/escpos-php#404]
Hi, When trying to print from server to shared printer(LPT1), iI get the following error:  "failed to open stream: Permission denied" mi code is:

$connector = new WindowsPrintConnector("smb://SUBTERRANEO-PC/EPSON TM-T88III RECEIPT");

Could you help me please?

**Comment by Stenerson** [comment]
Hi @roro1981. This is usually due to the php process not having the same permissions as your user account. There are quite a few issues here already with that error message. Could you [search through](https://github.com/mike42/escpos-php/search?q=Permission+denied&type=Issues&utf8=%E2%9C%93) previous issues (#395, #380, #377, #65 just to list a few) and the [FAQ](https://github.com/mike42/escpos-php/blob/development/doc/FAQ.md#why-do-i-get-this-error-when-i-try-to-print) to see if you can find answers that have helped others?

If these don't help, can you list out any troubleshooting steps you have taken? Thanks!
