### ISSUE TITLE
Does it support Traditional Chinese in Epson TM-P20?

### ISSUE THREAD

**Issue by ngkung** [mike42/escpos-php#423]
Dear Mike,

It is great that I find TM-P20 really working perfectly with ESCPOS except it cannot print out traditional Chinese (double-byte characters). It is UTF-8 already. I know you have already made textChinese and it seems it works for GB (actually, I cannot work it out for GB). 

I have checked https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=338. It supports Kanji which is Japanese Chinese characters. In the textChinese function, I know you have already used Kanji. Do you mean that there must be traditional Chinese character font in the printer to print out Chinese characters? Any other way to work it out? I mean print out Chinese characters.

Howard

**Comment by mike42** [comment]
Chinese output will not currently work on that model of printer.

- The `textChinese` function sends GBK wrapped with a few control commands, for the ZJ-5890. I think that printer renders it as simplified Chinese (the documentation for that printer is not available on the web).
- The TM-P20 printer has a simplified Chinese model, but I can't see any documentation available online for on how to use it. This driver will render "???" because it doesn't know how to send them.
- The Kanji is represented by Shift-JIS endoding and some Kanji commands, available only on Japanese models. This driver does not implement that either.

If you do a search on the issue tracker for "ImagePrintBuffer", you will see some examples where we have rendered text to small images to work around this issue in other scripts.

So, I'm going to close this off as answered. I'm open to reviewing pull requests that implement this feature, but with no documentation, use, or way to test, I am not likely to add it to the driver myself. 

See also https://reference.epson-biz.com/modules/ref_charcode_en/index.php?content_id=110

**Comment by ngkung** [comment]
No problem. I have already made update on the firmware and made a simple change of the textChinese to support traditional chinese. It works fine now. Thank you so much.

**Comment by JefferyHus** [comment]
Would  you like to share what you did because I am stuck with Japanese.

**Comment by ngkung** [comment]
Dear Jeffery,

         Actually we found that the machine was not preloaded with
Traditional Chinese. Then, we returned it to the vendor and got it updated
with traditional Chinese. It works. Of course, there was characters
encoding issue. It is easy to sort out. I don't think it is going to do
with your issue.
         The way we found out it was not preloaded with Chinese characters
was simply using the javascript epos-2.3.0.js provided by EPSON. It was
easy to use.
         Thank you so much.

Howard
