### ISSUE TITLE
Star m-POP

### ISSUE THREAD

**Issue by febridev** [mike42/escpos-php#427]
hi, 
This library has support Star m-POP ? with Bluetooth Connection ? 
http://star-emea.com/products/mpop/

Thanks

**Comment by mike42** [comment]
Please have a read of the FAQ entry [I have Printer X. Can I use this driver?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#i-have-printer-x-can-i-use-this-driver).

Regarding bluetooth, I currently don't [list it as compatible](https://github.com/mike42/escpos-php/blob/9bbc67365261af11a0ab6340e88e25cd4d8bd087/README.md#compatibility), simply because it hasn't been tested. I would expect that on Linux, you could use a `FilePrintConnector` to connect with a bluetooth device file, but I'm not sure how I would attempt it on other platforms.
