### ISSUE TITLE
Working in Localhost not in server

### ISSUE THREAD

**Issue by selvakmr160** [mike42/escpos-php#428]
Hi,
Thanks for the code,,
I am using your code for thermal printing and it is working fine in localhost..
(windows7+xampp+php).and after I uploaded in my linux server it is not working it says ,,

> Couldn't print to this printer: Failed to print. Command "smbclient '//cs1008.webhostbox.net/Receipt Printer' -c 'print -' -N" failed with exit code 127: sh: smbclient: command not found

And I found i must install samba in my linux server,But i am using cloud hosting(sampa-smbclient allow only VPS and Dedicative server).Please confirm If i install smbclient(samba) will it work without any issue..

> $connector = new WindowsPrintConnector("Receipt Printer");
> 	$printer = new Printer($connector);
> $printer -> initialize();
> $printer -> setJustification( Printer::JUSTIFY_CENTER );
> $printer -> selectPrintMode( Printer::MODE_DOUBLE_WIDTH | Printer::MODE_DOUBLE_HEIGHT );
> $widthMultiplier=1;$heightMultiplier=2;
> $printer ->setTextSize($widthMultiplier, $heightMultiplier);
> 	/* Print a "Hello world" receipt" */
> 	$printer -> text("Order ID : ".$orderid."\n");
> 	$printer -> text("Employee ID : ".$empid."\n");
> 	$printer -> text("Dish Name : ".$dishname."\n");
> 	$printer -> text("thanks for Ordering...\n");
> 	$printer -> cut();
> 	$autofoc='';
> 	$expr='Print Successful';$errors1="Loading Please Wait....";
> 	/* Close printer */
> 	$printer -> close();
> } catch(Exception $e) {
> 	echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
> }

This is the code i am using,Please tell me IS there any setting I need to do after install smbclient.
after install smbclient what should i write in 
$connector = new WindowsPrintConnector("Receipt Printer");

**Comment by madivad** [comment]
You obviously have a samba share locally or the printer is installed locally, hence it works. You are (almost) never going to have a samba share for your printer on the internet and hence your cloud server is not going to be able to connect to it. If you are wanting to connect a cloud service to your local printer it is going to have to be available to that service (and hence just about everyone on the internet unless you have some form of authentication). 

Installing samba on the cloud is not the issue, so don't do that. I'm not sure how you are securely going to allow the service to connect to your printer, but my guess is you are going to have to run another service locally that will provide authentication and interconnectivity between the two. Something that is beyond my skillset. Good luck!

(I'm just passing thru, I am not the author or in any way connected to this project and as such I may not see your responses in future. Again, good luck).

**Comment by mike42** [comment]
Yes, there is no quick fix.

There are some thoughts on this at [Can I print from my server on the Internet?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#can-i-print-from-my-server-on-the-internet).

**Comment by mutiemule** [comment]
Printing on local will work well with this package.

However, to print online, you will need to develop a desktop service which has to be installed on the local computer where you need printing to be done.  This is because PHP is a server-side scripting language, so once you put this online, it won't be able to communicate to the local printer. Thus, you need a client service running on the local machine and this is where electron js and node js come into play.

I resolved this by developing an electron js service based on [node-escpos package](https://www.npmjs.com/package/escpos) which can receive commands from the online print command and then communicate those commands to the printer through USB. 

Operating System does not matter in this case, you can be hosting on Linux based server and printing on a windows server. This desktop service interfaces between the online service and the local service. 

You can check out the [node-escpos printer driver package ](https://github.com/song940/node-escpos) for some inspiration on how to go about this.

Check the [FAQs on how to print online](https://github.com/mike42/escpos-php/blob/fe9350e61fb5e38416ec6243873c37fa65f34eb5/doc/FAQ.md#can-i-print-from-my-server-on-the-internet) to have some pointers too.
