### ISSUE TITLE
How it Works With Black Copper BC-85AC?

### ISSUE THREAD

**Issue by alisharafat123** [mike42/escpos-php#431]
I have Installed Black Copper BC-85AC but no printing happens kindly help.

**Comment by mike42** [comment]
Hello,

There is not enough information to get you a good answer. Your printer is [not been reported to work yet](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#i-have-printer-x-can-i-use-this-driver), so you are in experimental territory.

Could you please briefly describe a few things?

- **your setup:** operating system, PHP version, interface (USB, serial?), how you have set up the printer and verified that you can send it raw data in the command-line.
- **what you are trying to achieve:** eg, printing a "Hello world" receipt to your printer over a LAN. Include a [minimal but self-contained](https://en.wikipedia.org/wiki/Minimal_Working_Example) PHP snippet showing how you are attempting to use the driver.
- **what goes wrong:** explain what happens when you run it (include any error messages or a picture of the output if it's not correct). Remember to enable and check the PHP error log.
