### ISSUE TITLE
Please add  Zebra GT800 printer

### ISSUE THREAD

**Issue by nu1ww** [mike42/escpos-php#433]
Could you add Zebra GT800 DESKTOP printer?

**Comment by Stenerson** [comment]
Sorry @nu1ww, this printer (and Zebra Printers in general) support a different language (ZPL) and do not support Epson's ESC-POS language. 

There _may_ some Zebras that support ESC-POS but I looked through the spec sheets on the GT800 and it is not listed.

Since this library is specific to ESC-POS I'm going to close this request.
