### ISSUE TITLE
Working on Localhost but not working on server

### ISSUE THREAD

**Issue by younas-bangash** [mike42/escpos-php#437]
I am using below code which is working fine on the localhost

```
try {
    $connector = null;
    $profile = CapabilityProfile::load("SP2000");
    $connector =  new WindowsPrintConnector("smb://ComputerName/PrinterName"); 
    $printer = new Printer($connector, $profile);
    $printer -> text("Hello World!\n");
    $printer -> cut();
    $printer -> close();
} catch (Exception $e) {
    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}
```

When I run the same code on server I face the below error

`Couldn't print to this printer: Failed to print. Command "smbclient '//ComputerName/PrinterName' -c 'print -' -N" failed with exit code 1: WARNING: The "syslog" option is deprecatedConnection to AppcomSolutions failed (Error **NT_STATUS_UNSUCCESSFUL**)`

**Comment by mike42** [comment]
You need to verify your transport on the command-line before you try to use PHP code to print. See these FAQ entries: 
- [Why do I get this error when I try to print?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#why-do-i-get-this-error-when-i-try-to-print)
- [Can I print from my server on the Internet?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#can-i-print-from-my-server-on-the-internet)

I'm going to close this question off since it's in the FAQ. I get this question a lot, so if you think we can improve the documentation to help users to better understand the limitations of server-side printing, then please open a fresh issue or pull request with any suggestions.

**Comment by mutiemule** [comment]
Printing on local will work well with this package.

However, to print online, you will need to develop a desktop service which has to be installed on the local computer where you need printing to be done.  This is because PHP is a server-side scripting language, so once you put this online, it won't be able to communicate to the local printer. Thus, you need a client service running on the local machine and this is where electron js and node js come into play.

I resolved this by developing an electron js service based on [node-escpos package](https://www.npmjs.com/package/escpos) which can receive commands from the online print command and then communicate those commands to the printer through USB. 

Operating System does not matter in this case, you can be hosting on Linux based server and printing on a windows server. This desktop service interfaces between the online service and the local service. 

You can check out the [node-escpos printer driver package ](https://github.com/song940/node-escpos) for some inspiration on how to go about this.

Check the [FAQs on how to print online](https://github.com/mike42/escpos-php/blob/fe9350e61fb5e38416ec6243873c37fa65f34eb5/doc/FAQ.md#can-i-print-from-my-server-on-the-internet) to have some pointers too.
