### ISSUE TITLE
Custom vkp80

### ISSUE THREAD

**Issue by hasanenalbana** [mike42/escpos-php#440]
Hello,
I tried the PHP library with Custom VK80ii [Link](http://www.custom.biz/self-service-industrial/solutions-for-self-service-kiosks/kiosk-printers/vkp80ii-sx). Most of the printing is working, however printing images wider than 270px doesn't work in both modes (bitmap & raster).
Is there anything I can do to the library to make it work?
Thanks for the great effort you put into this project.

**Comment by mike42** [comment]
I'm not able to answer this, other than to say that there is no limitation at 270px width in the library or protocol, so this may be a printer limitation.

Test image (modified from [placeholder.com](https://placeholder.com/))-

![500x100](https://user-images.githubusercontent.com/2080552/32133520-54a93a5c-bc25-11e7-8e8f-dd1e2957d6c3.png)

Code-

```php
<?php
require __DIR__ . '/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\EscposImage;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;

$connector = new FilePrintConnector("php://stdout");
$printer = new Printer($connector);
$box = EscposImage::load("500x100.png", false);

$printer -> graphics($box);
$printer -> feed();

$printer -> bitImage($box);
$printer -> feed();

$printer -> bitImageColumnFormat($box);
$printer -> feed();

$printer -> cut();

$printer -> close();
```

Result on Epson TM-T20-

![outp](https://user-images.githubusercontent.com/2080552/32133592-a3844364-bc26-11e7-827f-b4b3a50c49d6.png)

If the vendor has a programming guide published online which shows that the printer will do wider images with ESC/POS, then please link it here so that it can be tracked and implemented.

**Comment by hasanenalbana** [comment]
Thank you very much. I did some tests and it worked using Graphics Command
with width =< 590px. Anything higher than 590 causes the printer to print
rubbish.
So your library is working just fine. The vendor did not mention any limit
in the product manual.

Regards,
Hasanen.

**Comment by mike42** [comment]
Garbage output can occur if the image has too many pixels for the printer's buffer, see #206. If this issue affects you, you may be able to go wider than 590px if you reduce the height as well.

Best of luck!
