### ISSUE TITLE
setTextSize not working

### ISSUE THREAD

**Issue by Ram111028** [mike42/escpos-php#441]
settextsize not working for me.I am using star tsp700II printer and my code is given below 

<?php
require __DIR__ . '/../autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\EscposImage;
$connector = new WindowsPrintConnector("testprinter");
$printer = new Printer($connector);
/* Initialize */
$printer -> initialize();
$printer -> setEmphasis(true);
$printer -> setTextSize(8, 8);
$printer -> text("\n\n FOO CORP Ltd.\n");
$printer -> setEmphasis(false);
$printer -> cut();
$printer -> close();
?>

**Comment by mike42** [comment]
May be the same issue as #450.

Can you verify that your printer is in ESC/POS emulation mode and share a link to the ESC/POS command reference for your printer if it's available online?

Your printer is not understanding the `GS ! n` command, so we need to see whether there is a similar command that can be used instead.

**Comment by Ram111028** [comment]
setEmphasis(true);  
Give bold to my text if my printer is not understanding the GS ! n command,then setEmphasis should not work for me but its work fine for me

**Comment by Ram111028** [comment]
i found another issue i.e printing is working in local but not working in server like this
PHP Fatal error:  Uncaught exception 'Exception' with message 'Failed to print. Command "smbclient '//ip-10-0-0-16/test1' -c 'print -' -N" failed with exit code 1: OS=[Windows 6.1] Server=[Samba 4.6.2]Anonymous login successful
tree connect failed: NT_STATUS_BAD_NETWORK_NAME' in /home/agscinemasapp/public_html/escpos/src/Mike42/Escpos/PrintConnectors/WindowsPrintConnector.php:236
Stack trace:
#0 /home/agscinemasapp/public_html/escpos/src/Mike42/Escpos/PrintConnectors/WindowsPrintConnector.php(181): Mike42\Escpos\PrintConnectors\WindowsPrintConnector->finalizeLinux('\e@\e@\n         F...')
#1 /home/agscinemasapp/public_html/escpos/src/Mike42/Escpos/Printer.php(503): Mike42\Escpos\PrintConnectors\WindowsPrintConnector->finalize()
#2 /home/agscinemasapp/public_html/escpos/example/testprint.php(177): Mike42\Escpos\Printer->close()
#3 {main}
  thrown in /home/agscinemasapp/public_html/escpos/src/Mike42/Escpos/PrintConnectors/WindowsPrintConnector.php on line 236

**Comment by mike42** [comment]
That's not correct.

The `setEmphasis()` command sends ` ESC E` in `escpos-php`, you can check the code for that one: https://github.com/mike42/escpos-php/blob/61dc270de7b78ce9be0d49e69163db5500f22cc9/src/Mike42/Escpos/Printer.php#L842

So the next step to solving your issue was in my original reply-

> Can you verify that your printer is in ESC/POS emulation mode and share a link to the ESC/POS command reference for your printer if it's available online?
> 
> Your printer is not understanding the GS ! n command, so we need to see whether there is a similar command that can be used instead.

For the transport issue, check the FAQ entry [Can I print from my server on the Internet?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#can-i-print-from-my-server-on-the-internet). We get this question a lot, so if you think we can improve the documentation to help users to better understand the limitations of server-side printing, then please open a fresh issue or pull request with any suggestions.

I'm going to close this off since there isn't enough info for anyone here to tell you why the text size command is not being understood by your printer, or to suggest an alternative.
