### ISSUE TITLE
WindowsPrintConnector Failed to copy file to printer

### ISSUE THREAD

**Issue by awarak** [mike42/escpos-php#468]
Warning: copy(\\Amar-PC\Receipt Printer) [function.copy]: failed to open stream: No such file or directory in C:\wamp\www\escpos-php-development\escpos-php-development\src\Mike42\Escpos\PrintConnectors\WindowsPrintConnector.php on line 372
Couldn't print to this printer: Failed to copy file to printer

what can i do please ?

**Comment by jecorrales3** [comment]
@awarak: 

**Warning:** copy(\\JOHAN-ROTUMARK\DYMOLabelWriter450Turbso): failed to open stream: No such file or directory in C:\xampp\htdocs\Prueba\php_mike42\ticket\src\Mike42\Escpos\PrintConnectors\WindowsPrintConnector.php on line 372

I've tried with that for a few days ago, and this error is for your printer is not shared for you or the name of your printer isn't equal, you need to go to: 

ControlPanel/Printers/YourPrinter/Administrate/PropertiesForYourPrinter/

1. Change the name of your printer, without spaces --> MyPrinterIS-HP
2. Go to Share in the same place, Properties, and select the checkbox "Share my printer" and put the name of your printer(THE SAME), generally, it does alone, if doesn't, you have to do it.
3. And, finally , save your changes, and tell me if it works for you or not!

**Comment by mike42** [comment]
Good tips @jecorrales3, thanks for sharing.

Especially for Windows shared printers, I think it's important to [start with the command-line](https://github.com/mike42/escpos-php/blob/v1.6/example/interface/smb.php) when debugging basic connectivity.

```php
/*
 * Windows: (use an appropriate "net use" command if you need authentication)
 *  echo "Hello World" > testfile
 *  ## If you need authentication, use "net use" to hook up the printer:
 *  # net use "\\computername\Receipt Printer" /user:Guest
 *  # net use "\\computername\Receipt Printer" /user:Bob secret
 *  # net use "\\computername\Receipt Printer" /user:workgroup\Bob secret
 *  copy testfile "\\computername\Receipt Printer"
 *  del testfile
 */
```

The print driver does this in the background, so all that matters is that the path is correct, and nothing like firewalls or group policy obstruct it.

Commands like "net use" can map printers for you if you need credentials.

**Comment by joseormubra** [comment]
Hello,First Thanks a lot for this project.
 I have the same problem in windows XP.
Using windows 7 I solve the problem following the "jecorrales3 commented on 20 Nov 2017" steps
I did the same for XP but it dont solve the problem.
If you have any clue I apreciate it
Thanks

**Comment by vincentckk** [comment]
![image](https://user-images.githubusercontent.com/26475848/36669984-b20c7176-1b31-11e8-98b6-6344ad8ffcce.png)

Fire up in command line works fine...
I've got the same problem and opened a new issue #520 with detail explained.

**Comment by mike42** [comment]
Closing this issue off since the original question is answered, one issue per thread please. [Why do I get this error when I try to print?](https://github.com/mike42/escpos-php/blob/61dc270de7b78ce9be0d49e69163db5500f22cc9/doc/FAQ.md#why-do-i-get-this-error-when-i-try-to-print) is also an FAQ item.

Specifically, for Windows-Windows authenticated shared printers, the WindowsPrintConnector is going to run the `net use` command, followed by `copy(.., '\\computer\printername');`, which will absolutely give you errors if your Webserver user can't transport raw data like that on your setup.

I'm open to suggestions if we can improve the implementation, error message or documentation to reduce the amount of issue tracker traffic that we get from users trying out the `WindowsPrintConnector`.
