### ISSUE TITLE
Can I use it with TVS RP1350 STAR and TSC244?

### ISSUE THREAD

**Issue by zainulabd786** [mike42/escpos-php#471]
I'm using printers that are not listed in the supported printers, How can I use TVS RP1350 and TSC244 printers with ecspos-php

**Comment by mike42** [comment]
To borrow from [the FAQ](https://github.com/mike42/escpos-php/blob/v1.6/doc/FAQ.md#i-have-printer-x-can-i-use-this-driver)-  If the printer understands ESC/POS, and you know how to get raw binary data to it, then you can use it with escpos-php. Otherwise, you can't.

Once you have verified with the vendor docs that you have an ESC/POS printer, start from "The 'Hello World' receipt" section of the README, it also applies to untested printers.

**Comment by zainulabd786** [comment]
Hello Michael, Thanks for your reply.
still, I,m having trouble in getting a print from the Thermal printer,
Neither I'm getting the printout nor any error.
could you please help me with this, I'll be really grateful to you.
