### ISSUE TITLE
Establish oldest supported version of driver

### ISSUE THREAD

**Issue by webnapier** [mike42/escpos-php#48]
Fatal error: Call to undefined function gzdecode() in C:\Apache2.2\htdocs\metropolis\src\EscposPrintBuffer.php on line 173

**Comment by mike42** [comment]
Hello,

The fastest way to fix this is to keep upgrading. It appears you are using PHP 5.3, but this function was not available until PHP 5.4, released 2012.

See http://php.net/releases/

Setting COMPRESS_CACHE = false in EscposPrintBuffer.php will also bypass this particular issue. Other compatibility issues due to old PHP versions may appear, so be prepared to debug if you do go down this path.

Testing has not been performed on old releases (mainly because PHPUnit needs something relatively new), so getting the most recent stable release for your platform is highly suggested.

**Comment by mike42** [comment]
Marking this as a bug, because an "earliest supported version" needs to be identified. See also #34

**Comment by mike42** [comment]
Link for further info: [PHP Supported Versions](http://php.net/supported-versions.php)

**Comment by mike42** [comment]
Closing this, the new travis CI builds now show supported PHP setups on Linux: https://travis-ci.org/mike42/escpos-php
