### ISSUE TITLE
Can i print barcode in barcode printer...???

### ISSUE THREAD

**Issue by Subhasish10** [mike42/escpos-php#482]
escpos-php work smoothly in POS Thermal printer...

But i want to print barcode in Barcode Label printer(Like: TSC TE244 Printer.)
Any suggestion ??

**Comment by mike42** [comment]
The TSC TE244 printer appears to accept a vendor language named TSPL/TSPL2, rather than ESC/POS, so the output generated by this library will not be understood by your printer.

You will either need another library. I haven't had to use a TSPL printer before, so I can't offer any suggestions.

We've had other TSC printer users post before, see also #293 and #495.
