### ISSUE TITLE
Fatal error when "php esc2html.php receipt-with-logo.bin > receipt-with-logo.htm" is called

### ISSUE THREAD

**Issue by abhayjb** [mike42/escpos-php#484]
> Fatal error: Uncaught Error: Class 'Imagick' not found in /Users/abhaybhat/projects/Github_abhayjb/escpos-tools/src/Parser/Command/StoreRasterFmtDataToPrintBufferGraphicsSubCmd.php:80 Stack trace: #0 /Users/abhaybhat/projects/Github_abhayjb/escpos-tools/esc2html.php(59): ReceiptPrintHq\EscposTools\Parser\Command\StoreRasterFmtDataToPrintBufferGraphicsSubCmd->asPng() #1 {main} thrown in /Users/abhaybhat/projects/Github_abhayjb/escpos-tools/src/Parser/Command/StoreRasterFmtDataToPrintBufferGraphicsSubCmd.php on line 80

I installed all dependencies from composer.phar, not sure why 'Imagick' class is not found

**Comment by mike42** [comment]
I'm going to close this off. You have the wrong project, that command is from https://github.com/receipt-print-hq/escpos-tools

Also, a quick Google search for `Imagick` should turn up installation instructions for your platform, but I've raised a bug receipt-print-hq/escpos-tools#44 because the dependency is not correctly recorded.
