### ISSUE TITLE
Some time my REST API throw this response

### ISSUE THREAD

**Issue by rifthyahmed** [mike42/escpos-php#485]
`{"status":"failed","message":"Cannot initialise Network Print Connector: No connection could be made because the target machine actively refused it.\r\n"}`

But most of the time it print perfectly.

**Comment by mike42** [comment]
Your printer is refusing your connection sometimes, maybe it's busy.

You can add the printer to CUPS and access it via a `CupsPrintConnector` (introduces a slight delay) as an alternative. This allows PHP to success when the job is added to the queue, instead of failing because it cannot be printed immediately.
