### ISSUE TITLE
Printing from Terminal works but not Webbrowser

### ISSUE THREAD

**Issue by ferhattelci** [mike42/escpos-php#491]
I'm trying to print from the client over the web browser with the address: 192.168.X.X/printer/example/linux_example.php but then I get this error "Couldn't print to this printer: Cannot initialise FilePrintConnector". 

If I run the php file over the terminal on the pi directly it works .. 

The printer is connected via USB on the pi

**Comment by JacquesLG** [comment]
Hey, 
I have exactly the same problem :)

**Comment by JacquesLG** [comment]
Hey I had the same problem found a quick fix though, I just ran this:

`chmod -R 777 /dev/usb`

I think it's very unsecure so be careful :)

**Comment by ferhattelci** [comment]
Oh thanks a lot for your reply! I have found the same solution but as you said this is very unsecure.. it must be an other solution there..

**Comment by dampfklon** [comment]
The reason is that your user is allowed to access /dev/usb and the user running the web-server is not. 
The solution is to grant the user the permission to access the device. The command above allows all users the access.

on debian flavored distributions the command `sudo usermod -a -G groupname www-data `should fix the problem. groupname has to be replaced by the name in the fourth column of ls -lA /dev/usb.

I can't tell which as i don't have a usb-printer at hand.

**Comment by mike42** [comment]
Yep, the group is called `lp` on Debian, and if the `www-data` user is in there, you can write to `/dev/usb/lpX` from PHP running under Apache.

See note on permissions-

- https://mike42.me/blog/2015-03-getting-a-usb-receipt-printer-working-on-linux

**Comment by mutiemule** [comment]
Printing on local will work well with this package.

However, to print online, you will need to develop a desktop service which has to be installed on the local computer where you need printing to be done.  This is because PHP is a server-side scripting language, so once you put this online, it won't be able to communicate to the local printer. Thus, you need a client service running on the local machine and this is where electron js and node js come into play.

I resolved this by developing an electron js service based on [node-escpos package](https://www.npmjs.com/package/escpos) which can receive commands from the online print command and then communicate those commands to the printer through USB. 

Operating System does not matter in this case, you can be hosting on Linux based server and printing on a windows server. This desktop service interfaces between the online service and the local service. 

You can check out the [node-escpos printer driver package ](https://github.com/song940/node-escpos) for some inspiration on how to go about this.

Check the [FAQs on how to print online](https://github.com/mike42/escpos-php/blob/fe9350e61fb5e38416ec6243873c37fa65f34eb5/doc/FAQ.md#can-i-print-from-my-server-on-the-internet) to have some pointers too.
