### ISSUE TITLE
Please Provide TSC TC 244 Printer Solution

### ISSUE THREAD

**Issue by abhati38** [mike42/escpos-php#495]
Please Provide TSC TC 244 Printer Solution

**Comment by mike42** [comment]
The TSC TC 244 printer accepts a vendor language named TSPL/TSPL2, rather than ESC/POS, so the output generated by this library will not be understood by your printer.

While this project is not in a position to support other printing languages, I'm open to reviewing pull requests which improve compatibility for other printers if it can be done without breaking the ESC/POS output.

This was also asked at #293 and #482.

**Comment by pureche** [comment]
@mike42 is it possible to have a connector method to connect to a TSC TTP-244 Pro, a TSLP2 printer? I have the manual of commands for the printer, and if a connector is available, I suppose I can submit a pull request to have the feature for supporting TSLP2 printers added to it.

I've looked around, and there's nothing related to PHP-TSLP2 on the internet.
