### ISSUE TITLE
"Failed to open stream: Invalid argument" on Windows Server 2016, but not Windows 7

### ISSUE THREAD

**Issue by r4llproject** [mike42/escpos-php#497]
Hi All,
I use this code : 
        $profile = CapabilityProfile::load("simple");
        $connector = new WindowsPrintConnector("smb://172.17.4.11/printertiket");
        $printer = new Printer($connector);
on Windows 7 as a Xampp server. And its work.

But, when i use Windows Server 2016 as Xampp Server, it have an error : "copy(\\172.17.4.61\printerphp): failed to open stream: Invalid argument"

Any solution for this?
Thank you before..

**Comment by mike42** [comment]
Tagging this as a bug, it sure sounds like something is different between Windows 7 and Windows Server 2016 that we may need to account for.

Can you confirm whether the printer is added as generic / text only printer in both cases?

**Comment by mike42** [comment]
#474 may be related.

**Comment by mike42** [comment]
Closing this off as I think this is now fully duplicated by other tickets.

We have an open bug relating to over-riding the SMB protocol version which can be solved at #575, and a feature request that would work around this issue by providing local system printing at #474.

**Comment by GabrielAlvarezSw** [comment]
Hi! first  , thanks you Mike42 for your excellent work! :) You've saved us countless amount of hours with your library. I'm having right now the same issue on my production server, I'm attaching my server log. 

It's a Windows Server 2012 R2 and the printer is running on  a Raspberry Pi 3 with a SMB server running. And it's an intermitent error that gets "fixed" when I restart the raspy. Any update with this issue ? I don't think it's related to #575 as the error message is quite different, same goes for #474 as I can't really use local printing because I depend on a network printer server.

Thanks for your time and work 👍  
![image](https://user-images.githubusercontent.com/50641016/61229137-fe022180-a6fd-11e9-8768-6fe35b4ee244.png)
