### ISSUE TITLE
BIXOLON SRP 770II

### ISSUE THREAD

**Issue by froberti** [mike42/escpos-php#498]
How can i do to print on bixolon SRP 770II, i have a Epson TM-T20II and print ok, then i change to BIXOLON and don´t print

**Comment by mike42** [comment]
Hello,

Would you mind sharing the code you are using to print, and a picture or description of what happens when it runs?

**Comment by froberti** [comment]
The same code is used for a POS-80C thermal printer and it worked correctly. But for the printer BOXILON SRP770II and EPSON TMU220A (FISCAL PRINT ESC/POS) has not worked.

Thanks !!!
Code:
-------

<?php


require __DIR__ . '/escpos/autoload.php'; //Nota: si renombraste la carpeta a algo diferente de "ticket" cambia el nombre en esta línea
use Mike42\Escpos\Printer;
use Mike42\Escpos\EscposImage;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
 

 //-Find name to print setting in table.- This name is the same from Pinters and Scanners on Windwos 10 and all printers are "Shared"
$nombre = Buscar_id("puestos", "ip", $ip, "comandera_nombre"); 
if ($nombre=="") { $nombre=""; $notificacion="Por favor, ingrese el nombre de la impresora a enviar los datos segun windows y recuerde que debe estar compartida"; return; }
$nombre_impresora = "$nombre"; echo "Enviando ticket a ".$nombre_impresora."...";
//-



$connector = new WindowsPrintConnector($nombre_impresora);
$printer = new Printer($connector); //comandera

//$printer = new Escpos($connector);


$printer -> setPrintLeftMargin(20);
$printer -> setTextSize(1,1);

$printer->setEmphasis(true);
$printer -> setJustification(Printer::JUSTIFY_CENTER);
$printer->selectPrintMode(Printer::MODE_DOUBLE_HEIGHT | Printer::MODE_DOUBLE_WIDTH);
$printer->text("$comanda_negocio");
$printer -> setJustification();
$printer->selectPrintMode();
$printer->text("$comanda_cabecera");
$printer->text("$comanda_comprobante \n");
$printer->setBarcodeHeight(48);
//$printer->barcode($id_comprobante, Printer::BARCODE_CODE39);
$printer->setEmphasis(false);

$printer -> setTextSize(1, 1);
$printer->text("$comanda_items");

$printer -> setTextSize(1, 1);
$printer->text("$comanda_pie");

$printer->feed();

$printer->cut();

$printer->pulse();

$printer->close();         
                              
?>

**Comment by mike42** [comment]
This code is not self-contained. For example, I don't see where `comanda_pie` is set, so I don't know if it contains UTF-8 or a newline, and I also don't know id there is bad output when it prints.

- You are generally going to need to use different printer profiles, or the `simple` profile to disable features that don't work outside of the Epson printers, such as QR codes.
- You can also try debugging by beginning with a Hello World receipt and building from there. That should print the same everywhere, so if it doesn't, then you either don't have ESC/POS printers, or something else is wrong.

I'm going to close this off since it's an old issue. We can re-open it if there's a minumum working example and you're still debugging it.
