### ISSUE TITLE
this library not work by internet

### ISSUE THREAD

**Issue by javacomtech1** [mike42/escpos-php#502]
i hosted only this library. it is not working.  please tell me how do solve this problem. 
error:

A PHP Error was encountered

Severity: Warning

Message: copy(\\USER-HOME\reciept): failed to open stream: No such file or directory

Filename: PrintConnectors/WindowsPrintConnector.php

Line Number: 372
Couldn't print to this printer: Failed to copy file to printer

**Comment by mdestafadilah** [comment]
please tell that OS, Printer and Connected each all.

**Comment by javacomtech1** [comment]
windows 7 and 8 OS

**Comment by mdestafadilah** [comment]
may you can use this: 
```
$ip = 127.0.0.1;   
$connector = new PrintConnectors\WindowsPrintConnector("smb://{$ip}"); 
```

**Comment by javacomtech1** [comment]
i hosted my application online. so What ip address enter?
hosted ip address or local ip address?

**Comment by mdestafadilah** [comment]
Yes you can put your "public ip" address.. which connected to printer ...

**Comment by javacomtech1** [comment]
$connector = new WindowsPrintConnector("smb://USER-HOME/receipt");

**Comment by javacomtech1** [comment]
$connector = new WindowsPrintConnector("smb://182.111.66.115/receipt"); it is correct or wrong?

**Comment by mdestafadilah** [comment]
> $connector = new WindowsPrintConnector("smb://182.111.66.115/receipt"); it is correct or wrong?

Yes, but must organized by CUPS if server using GNU/Linux, and do with PHP-ESCPOS setup for client application ...

**Comment by mike42** [comment]
You need to be able to get raw data to your printer to use this library. This is addressed in the FAQ- [Can I print from my server on the Internet?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#can-i-print-from-my-server-on-the-internet). This is a common question, so please post any suggestions to the FAQ as pull requests if you

Try to verify what you are attempting to do on the command-line. On Windows, this is done via `net use` and `copy`, which wont work over the Internet without a tunnel or VPN back to your LAN. Find a way to connect up your data first, since it's not in scope of this project to architect your network, security, and print system.

Once you can 'copy' a text file on to your printer from the server that runs PHP, you are ready to use `WindowsPrintConnector`.

Personally, I run the server on the LAN to avoid the issue, or deploy [receipt-print-hq/chrome-raw-print](https://github.com/receipt-print-hq/chrome-raw-print).

**Comment by mutiemule** [comment]
Printing on local will work well with this package.

However, to print online, you will need to develop a desktop service which has to be installed on the local computer where you need printing to be done.  This is because PHP is a server-side scripting language, so once you put this online, it won't be able to communicate to the local printer. Thus, you need a client service running on the local machine and this is where electron js and node js come into play.

I resolved this by developing an electron js service based on [node-escpos package](https://www.npmjs.com/package/escpos) which can receive commands from the online print command and then communicate those commands to the printer through USB. 

Operating System does not matter in this case, you can be hosting on Linux based server and printing on a windows server. This desktop service interfaces between the online service and the local service. 

You can check out the [node-escpos printer driver package ](https://github.com/song940/node-escpos) for some inspiration on how to go about this.

Check the [FAQs on how to print online](https://github.com/mike42/escpos-php/blob/fe9350e61fb5e38416ec6243873c37fa65f34eb5/doc/FAQ.md#can-i-print-from-my-server-on-the-internet) to have some pointers too.

**Comment by mdestafadilah** [comment]
> developing an electron js service

may you can share with other your script.
