### ISSUE TITLE
Help needed TSP143III LAN/Linux

### ISSUE THREAD

**Issue by MiDoTr** [mike42/escpos-php#509]
Hi,

I have a problem getting our Star TSP1000 ("TSP143IIILAN Cutter") to work.

Scenario:
- device is set to ESC/POS (as descibed [here](http://www.starmicronics.com/absolutefm/absolutefm/attachments/72/1203a_StarMicronics_ESCPOS_TSP100.pdf))
- device has a fixed IP address
- Server: Debian
- can print sample page from CUPS (on this server), also can "lp..." a regular plain text file from console
- piping to nc does not work:

`echo "Hello world" | nc 192.168.22.187 9100`

It results in a newline with a "#" and a unreadable character (see attached file)
![echonc](https://user-images.githubusercontent.com/35928982/35520845-849b8724-0518-11e8-9741-343b91ba3f1a.jpg)

- a textfile generated by your library (sample php) does not print with "lp", no reaction whatsoever, no error messages
- This does not work either:

`$connector = new NetworkPrintConnector("192.168.22.187", "9100");
$printer = new Printer($connector);
$printer -> text("Hello World!\n");
$printer -> cut();
$printer -> close();`

- Tried it without CapabilityProfile, with "simple" and with "SP2000", no change.

Any help to point me into the right direction how to get it to work would be very much appreciated, thank You

Mike.

**Comment by mdestafadilah** [comment]
are your client GNU/Linux or Windows? does the printer connected from client?

**Comment by MiDoTr** [comment]
Both, the problems are on Linux (Debian) only though. On Windows it connects and prints. On Debian it only prints via cups driver, no raw commands or those sent by this library work

**Comment by mdestafadilah** [comment]
hem... i'm using Linux Lite.. Debian base. and work, i'm recognized client windows printer with cups ... ping the ip then print via command line for testing. Aha, i remember, we must add printer name as we see in cups, then send it via CupsPrintConnector(); checkout this mike [interface](https://github.com/mike42/escpos-php/blob/development/example/interface/cups.php), very elegant.

**Comment by mike42** [comment]
@MiDoTr - I'm assuming that this printer is not understanding the ESC/POS cut command that we are sending. You are following the correct debug steps, and the SP2000 profile is the closest one to use.

Most previous reports of cutter issues on STAR printers have related to ESC/POS emulation mode, which I see you've enabled. Is there a programming guide online that shows the supported commands for this printer, so that I can compare it to our `cut()` function?

**Comment by mike42** [comment]
Assuming this issue has been abandoned, so I'll leave it there.

Ensuring you are using raw printing & ESC/POS emulation are the general things to check, if you do decide to try to debug this again in future.

**Comment by nchankov** [comment]
I have exactly the same issue. when I pipe netcat I got that wired:
`#? `
line and nothing has been printed. I've tried both using NetworkPrintConnector and piping it via nc. I doubt it's your library Mike, as if I try to make
nc {ip} 9100 it return the same symbol, as well as if I make telnet connection to the printer it's the same.

I can connect to the printer via Ubuntu and I can print, but not with command line. The printer is Star TSP100iii futurePrint. It was printing ok if I use Star android apps as well, just not been able to make it work via terminal.

Also tried Compatibility profiles, but didn't make any difference since it's not even work with nc
