### ISSUE TITLE
How to Connect Remote Printer, Application Hosted some where else?

### ISSUE THREAD

**Issue by hamza-younas94** [mike42/escpos-php#513]
HI,
i was thinking to connect printer remotely via application any idea.

i.e Application hosted WebServer - Internet 1
Printer - Internet 2

Both Internet are from differently ISP 

i know about the Port forwarding  but dont want to use

**Comment by Stenerson** [comment]
As far as I know, port forwarding or setting up a VPN are your only two straightforward options.

Another, slightly more complicated solution (or possibly much more complicated?) would be to create a daemon php application on  Internet 2 (i.e. the same LAN as the printer) that reaches out to your web server to see if there are any jobs it should print. When it found something to print, it would connect to the printer via LAN (or CUPS or something else) to print locally.

This avoids the need for a port forward since the daemon is initializing the contact but it may be more trouble than it's worth.

I've found that port forwarding works pretty well. Most modern firewalls can accept inbound traffic from an IP range (your web server) and ignore anything else which makes the port forwarding solution pretty "secure". Or at least not susceptible to port scanning attacks. VPN would be better but there are also complexities with that option.

**Comment by mutiemule** [comment]
Printing on local will work well with this package.

However, to print online, you will need to develop a desktop service which has to be installed on the local computer where you need printing to be done.  This is because PHP is a server-side scripting language, so once you put this online, it won't be able to communicate to the local printer. Thus, you need a client service running on the local machine and this is where electron js and node js come into play.

I resolved this by developing an electron js service based on [node-escpos package](https://www.npmjs.com/package/escpos) which can receive commands from the online print command and then communicate those commands to the printer through USB. 

Operating System does not matter in this case, you can be hosting on Linux based server and printing on a windows server. This desktop service interfaces between the online service and the local service. 

You can check out the [node-escpos printer driver package ](https://github.com/song940/node-escpos) for some inspiration on how to go about this.

Check the [FAQs on how to print online](https://github.com/mike42/escpos-php/blob/fe9350e61fb5e38416ec6243873c37fa65f34eb5/doc/FAQ.md#can-i-print-from-my-server-on-the-internet) to have some pointers too.
