### ISSUE TITLE
Not able to print file using javascript

### ISSUE THREAD

**Issue by amitsharma27sept** [mike42/escpos-php#515]
Can you provide a guide to get printable content from your code in a file and print the same using javascript. I am using Epson - TM - T88IV.

**Comment by mdestafadilah** [comment]
are your print from file or your data grab from js?

**Comment by amitsharma27sept** [comment]
I use you code to print data on file. Then put into HTML page, then I print
that page.

On Feb 13, 2018 1:48 PM, "Mr. D" <notifications@github.com> wrote:

are your print from file or your data grab from js?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mike42/escpos-php/issues/515#issuecomment-365183515>,
or mute the thread

**Comment by mike42** [comment]
This project implements server-side printing from PHP. It's not possible to directly send raw data to a printer from a web browser, so I'm not going to be writing a guide any time soon.

I've previously put time into writing a chrome app for users who hos their apps on the Internet and need to access raw printer devices over USB- ([link](https://github.com/receipt-print-hq/chrome-raw-print)), but I'm closing down that project because Chrome apps are being discontinued.

![example](https://user-images.githubusercontent.com/2080552/36140111-324f117e-10f4-11e8-84be-0b16277467df.png)

There are commercial products which do approximately the same thing (DYOR), or you could implement your own. My initial use case for this library was to print over the LAN, which is also an option.

A lot of the information in "Can I print from my server on the Internet?" on [the FAQ](https://github.com/mike42/escpos-php/blob/development/doc/FAQ.md) is relevant to your setup. We do get questions about client-side printing a lot, and I'm open to suggestions if we can make the fact that this is a server-side printing library any clearer in the documentation.

**Comment by amitsharma27sept** [comment]
I grab data from file and then try to print using js

**Comment by amitsharma27sept** [comment]
I used demo.php and write on a file.
Then I get this file data on my page and print using JavaScript window.print

**Comment by mike42** [comment]
Closing this off, I think I've answered it.

Aside, `window.print` uses the driver in your OS print system, which is not part of this project.
