### ISSUE TITLE
Method setJustification() not working for Image printing

### ISSUE THREAD

**Issue by ssamnotr** [mike42/escpos-php#519]
Hello  @mike42 ,
I am using EOM-200 printer(80mm Thermal printer).
function `setJustification() `in printer.php is not working with options JUSTIFY_CENTER and JUSTIFY_RIGHT for aligning the Images while printing.
I looked at the existing issues and the FAQ but could not find anything there.
Could you please suggest what could be the problem here?
I am attaching the generated output and code file (piece of code which I'm working on).
![output](https://user-images.githubusercontent.com/29039227/36640936-ec17c256-1a4d-11e8-8254-aebe7c4a69a6.jpg)

`<?php
/* Call this file 'hello-world.php' */
require __DIR__ . '/../autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\EscposImage;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
try {
    $printerName = "myPrinter";
    $connector = new WindowsPrintConnector($printerName);
    $printer = new Printer($connector);
    $Mode = 0;
    $printer -> selectPrintMode($mode);
    $tux = EscposImage::load('tux.png', false);
    
    $printer -> setJustification(Printer::JUSTIFY_CENTER);
    $printer -> bitImage($tux);
    $printer -> feed();
    
    $printer -> setJustification(Printer::JUSTIFY_RIGHT);
    $printer -> bitImage($tux);
    $printer -> feed();
    
    $printer -> cut(Printer::CUT_PARTIAL);
    /* Close printer */
    $printer ->  close();
}   
    catch(Exception $e) {
    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
    }
?>`

**Comment by mike42** [comment]
It's known that some printers have this limitation, see #96 #260. Text justification just does not affect image positioning on some printers.

You can try `bitImageColumnFormat`, or left-padding the image with whitespace before printing it. Since the library has no way of positioning the image through a native ESC/POS command, this difference in output is not likely to be resolved.

I'm open to reviewing any pull requests if you have any suggestions for how we can express this better in the documentation.

**Comment by supercent008** [comment]
justification center is not working on text. why?
