### ISSUE TITLE
Can this pos library adapt to work with LaserJet?

### ISSUE THREAD

**Issue by saadeenaa** [mike42/escpos-php#525]
Hi, Mike
My project work on Ubuntu server 16.04 with local printer : HP LaserJet P1006 
I want to print a pdf file through the LAN with LaserJet on my graduation project, then I try to work with your library , interface with CUPS.php but it can not print. in my opinion ,It can connected to printer because of  the job can be add to printer's list ,and the state of job is processing but the printer do nothing, and Finally the state be complete. 
i try to test on this code with name of CUPS printer such as (WEB is my printer's name)
`$connector = new CupsPrintConnector("WEB")`
but it have nothing , then I create a printer class name : WEBTEST and try it again like 
`$connector = new CupsPrintConnector("WEBTEST")`
but the result be the same before, which both way the print job added to the printer's list.
Can be solve its?

**Comment by mike42** [comment]
No, this library is only useful for ESC/POS printers.

We generate ESC/POS code and print using raw modes (CUPS is only used as transport here). The HP LaserJet is not an ESC/POS printer, so it's a bad idea to send it ESC/POS code.

CUPS supports PDF input and HP LaserJet output through its system of drivers, so you have no need for an additional library. A web search for "How to print PDF with CUPS command-line" followed by "How to run command from PHP" would probably give you the most direct answer.

Once you've researched it, feel free to take a copy of `CupsPrintConnector.php` and adapt it to print a PDF file instead of raw data from a variable.

**Comment by saadeenaa** [comment]
Thank a lot for your suggestion.
