### ISSUE TITLE
print-from-html.php  /tmp issue?

### ISSUE THREAD

**Issue by Linus-007** [mike42/escpos-php#53]
Hello,
I am trying to use the print-from-html.php example and I am seeing an error regarding the file in /tmp/

Here is the error
Command wkhtmltoimage -n -q --width '550' 'http://en.m.wikipedia.org/wiki/ESC/P' '/tmp/escposZDsgxD.png' failed: PHP Notice:  Print connector was not finalized. Did you forget to close the printer? in /usr/bin/escpos-php-master/src/FilePrintConnector.php on line 52

In the /tmp folder, I am finding the file without an extension.
Could this be the issue?

**Comment by mike42** [comment]
Hi. Can you report your `wkhtmltoimage` version, and also what the 'problem command' does when run manually?

```bash
$ wkhtmltoimage --version
wkhtmltoimage 0.12.1
````

Snippets which should display the article as an image using ImageMagick `display`-

````
wkhtmltoimage -n -q --width '550' 'http://en.m.wikipedia.org/wiki/ESC/P' - | display -
wkhtmltoimage -n -q --width '550' 'http://en.m.wikipedia.org/wiki/ESC/P' '/tmp/escposZDsgxD.png' && display '/tmp/escposZDsgxD.png' && rm '/tmp/escposZDsgxD.png'
````

----

Background: The error is generated when the output file does not appear at the requested location. I'm not sure why that is, but it's between PHP and `wkhtmltoimage`. If you're running on a webserver, check SELinux audit logs.

(I have no idea how the printer-not-closed NOTICE could be generated in this case- the first error throws before the `Escpos` object is created)

````php
try {
	/* Set up command */
	$source = "http://en.m.wikipedia.org/wiki/ESC/P";
	$width = 550;
	$dest = tempnam(sys_get_temp_dir(), 'escpos') . ".png";
	$cmd = sprintf("wkhtmltoimage -n -q --width %s %s %s",
		escapeshellarg($width),
		escapeshellarg($source),
		escapeshellarg($dest));
	
	/* Run wkhtmltoimage */
	ob_start();
	system($cmd); // Can also use popen() for better control of process
	$outp = ob_get_contents();
	ob_end_clean();
	if(!file_exists($dest)) {
		throw new Exception("Command $cmd failed: $outp");
	}
//... the PNG image is printed next...
} catch(Exception $e) {
	echo $e -> getMessage();
}
````

**Comment by Linus-007** [comment]
My version is 'wkhtmltoimage 0.12.0 final'.
Thanks

**Comment by mike42** [comment]
Versions aren't too different. The PHP wrapping around the `wkhtmltoimage` call is very simple- Chances are it's error-ing out for a simple reason but the PHP script isn't picking up why.

What happens when you run those two commands from the previous post manually?

Generate & display:

    wkhtmltoimage -n -q --width '550' 'http://en.m.wikipedia.org/wiki/ESC/P' - | display -

Generate & display via tmp file:

    wkhtmltoimage -n -q --width '550' 'http://en.m.wikipedia.org/wiki/ESC/P' '/tmp/escposZDsgxD.png' && display '/tmp/escposZDsgxD.png' && rm '/tmp/escposZDsgxD.png'

Of course the PHP example really just illustrates how slow it is to generate the raster data in native PHP. If you intend to render HTML to PNG for a real system, feed it to a dedicated PNG-to-escpos program. The output of [mike42/png2escpos](https://github.com/mike42/png2escpos) is identical to escpos-php's `bitImage()`, but written in C, while [petrkutalek/png2pos](https://github.com/petrkutalek/png2pos) is a more sophisticated program.

**Comment by Linus-007** [comment]
I cannot run these commands because of the following error: "cannot connect to X server"

I am running the server in text only mode.

**Comment by mike42** [comment]
Looks like you've found the problem. A quick google search for "wkhtmltoimage no x server" turned up[this](https://github.com/JazzCore/python-pdfkit/wiki/Using-wkhtmltopdf-without-X-server).

Closing this issue because it can't be fixed in `escpos-php`.
