### ISSUE TITLE
Graphics side by side

### ISSUE THREAD

**Issue by Linus-007** [mike42/escpos-php#54]
Printing graphics is pretty easy. Is it possible to print them side by side rather than graphic1, next line, graphic2?

I am hoping to print graphic1 graphic2 then the line feed. Is this possible?

**Comment by mike42** [comment]
I can't think of any way this can be done at the moment. I think your best bet is to just edit the graphics together. If you need to automate it, ImageMagick's `convert` or `montage`  ([example usage](http://stackoverflow.com/questions/20737061/merge-images-side-by-sidehorizontally)) will do the trick.

Other things to note-
- Alignment commands do work on images.
- You can probably achieve this in ESC/POS page mode, but you would need to shop around for a different driver (it may be added to escpos-php in future if there is the demand & resources for it)

**Comment by Linus-007** [comment]
Thanks. The montage command works well outside of PHP. I am having problems making it work within PHP.

Do you have an example of the image montage within php?

**Comment by mike42** [comment]
I haven't used the imagick extension for this before, but wrapping the working command with an exec() call seems to be the accepted work-around, [example here of somebody with a similar issue](http://community.sitepoint.com/t/joining-2-or-more-images-side-by-side-with-imagick/68646/2).

**Comment by Linus-007** [comment]
So far no luck. The command is not creating a file.

Small sample of code ...

exec ('convert $HighThermometer $LowThermometer +append $ImagePath."test.png"');
$Concatenated = new EscposImage($ImagePath."test.png");
$printer -> graphics($Concatenated);
$printer -> feed();

**Comment by mike42** [comment]
Tagging this with 'example'. I'll mock up something and upload it to the repo, as calling 'convert' from PHP is something other developers will need to know.

**Comment by mike42** [comment]
Hi,

Just put up a [new example](https://github.com/mike42/escpos-php/blob/master/example/specific/54-gfx-sidebyside.php) showing how to do this.

Some key things for others who want to run external commands from a receipt printing script are noted below, so that you get an idea of why this example is *so long*.

a. Escape your command-line arguments with escapeshellarg.

````php
	$cmd = sprintf ("convert %s %s +append %s",
			escapeshellarg ( $img1_path ),
			escapeshellarg ( $img2_path ),
			escapeshellarg ( $imgCombined_path ));
	exec($cmd, $outp, $retval);
````

b. Close the printer (even if there is an error). You can make use of the fact that escpos-php will throw an `Exception` when things go wrong. Eg, I've updated [this receipt](https://github.com/mike42/Auth/commit/3c73fb9f6a26a9dc6dab06271c8f86da9750798a) to catch exceptions from the image handling, printing without images instead of crashing.

````php
	// Run the actual print
	$printer = new Escpos ( $connector, $profile );
	try {
		...
	} finally {
		// Always close the connection
		$printer -> close();
	}
````
c. Delete any temp files. Using proper temp files guarantees unique names, which prevents concurrency issues (when your app is used to trigger two receipts at once), and you should wrap them in a `try { } finally {}` as so that crashes don't leave files around.

````php
	$tmpf_path = tempnam ( sys_get_temp_dir (), 'escpos-php' );
	$imgCombined_path = $tmpf_path . ".png";
	
	try {
		...
	} finally {
		unlink ( $imgCombined_path );
		unlink ( $tmpf_path );
	}
````

d. Detect and handle external command failure. A "file not found" error over a temp file is harder to debug than a "command failed" error with persistent files as input.

````php
	exec($cmd, $outp, $retval);
	if($retval != 0) {
		// Detect and handle command failure
		throw new Exception("Command \"$cmd\" returned $retval." . implode("\n", $outp));
	}
````

Hopefully this answers your question. I'd be interested to see what you end up with.
