### ISSUE TITLE
add new letters in capabilities.yml , encoding.yml , capabilities.json 

### ISSUE THREAD

**Issue by brankotasevski** [mike42/escpos-php#542]
hi i like to add a new letters.
how to add a few more letters to capabilities.yml in profile 3012
this is a profile data in capabilities.yml and encoding.yml
 CP3012:
    data:
      - "АБВГДЕЖЗИЙКЛМНОП"
      - "РСТУФХЦЧШЩЪЫЬЭЮЯ"
      - "ЃЅЈЉЊЌЏ" ---------------------------------------- a like to add this letters in this profile
      - "абвгдежзийклмноп"
      - "░▒▓│┤Ā╢ņ╕╣║╗╝Ō╛┐"
      - "└┴┬├─┼ā╟╚╔╩╦╠═╬╧"
      - "Š╤čČ╘╒ģĪī┘┌█▄ūŪ▀"
      - "рстуфхцчшщъыьэюя"
      - "ĒēĢķĶļĻžŽ∙·√Ņš■ "
    name: "CP3012 Cyrillic"

and add \u0403\u0405\u0408\u0409\u040A\u040C\u040F this letters in capabilities.json

**Comment by mike42** [comment]
Hey,

Two things-

- Different project, same people. You want to file a pull request against [receipt-print-hq/escpos-printer-db](https://github.com/receipt-print-hq/escpos-printer-db) with any suggested changes, and these get included here with each minor release.
- The `capabilities.json` file describes what printers can do, but can't enhance it. To improve the profile on your printer, you are going to need to start by opening an issue upstream which identifies your printer and what it can do (look for a file called `add-your-printer.md` in the repo). Since you are looking at encoding issues, if we have an  **encoding number** (0-255) understood by your specific printer, and you're prepared to run some test prints and upload scans of them to verify, we can match these up to an encoding in iconv or type them out. It's painstaking, but this is the data we use to make drivers which can convert UTF-8 into ESC/POS.
