### ISSUE TITLE
Printer blocked

### ISSUE THREAD

**Issue by shreeram143** [mike42/escpos-php#547]
Hi mike42,
I have downloaded your library file and implemneted in my project
Whenever customer purchase order I am sending receipt to printer and receipt will be taken successfully. But sometime, printer is blocked and it throw an error like below
""**Fatal error: Uncaught exception 'Exception' with message 'Cannot initialise NetworkPrintConnector: Connection timed out' in /var/www/html/uncleleo/library/escpos_php_development/src/Mike42/Escpos/PrintConnectors/NetworkPrintConnector.php:38 Stack trace: #0 /var/www/html/uncleleo/library/escpos_php_development/printer/receipt-with-logo.php(46): Mike42\Escpos\PrintConnectors\NetworkPrintConnector->__construct('printer ip') #1 {main} thrown in /var/www/html/uncleleo/library/escpos_php_development/src/Mike42/Escpos/PrintConnectors/NetworkPrintConnector.php on line 38**"
Not sure why printer is blocked automatically. Client claims that code is sending something to printer, so printer is blocked.

I am using this approach 
**use Mike42\Escpos\PrintConnectors\NetworkPrintConnector;
use Mike42\Escpos\Printer;
$connector = new NetworkPrintConnector("10.x.x.x", 9100);
$printer = new Printer($connector);
try {
    // ... Print stuff
} finally {
    $printer -> close();
}**

Any idea what may be the reason why printer is blocked automatically?
Any help would be appriciated, thanks

**Comment by mike42** [comment]
Hey, I don't know why your printer sometimes ignores connections. I've had an Epson Ethernet printer that would refuse connections if it was already printing, but it was rarely an issue, because it prints quite quickly.

From the perspective of this library, an error is being detected because the printer is not responding to the TCP port you are using, so an exception is being thrown, which is the correct behaviour.

You can either debug this as a printer/network issue (you should be able to replicate the problem without PHP), or assume that your printer is not always online an queue the prints somehow.

For queueing, you could either retry from PHP, or put your printer behind a print server like CUPS, which will introduce a short delay, but will reliably hold the jobs in a queue until they can be delivered.

Either way it's not a library issue, so while I hope this helps you to find a workaround for your issue, I'll close this off to keep the issue tracker on-topic.
