### ISSUE TITLE
Error in password with special characters smbclient

### ISSUE THREAD

**Issue by Stenfrank** [mike42/escpos-php#556]
WindowsPrintConnector generates error with special characters in the password:

`$connector = new WindowsPrintConnector("smb://user:Asd123?Asd123!@computername/Receipt Printer");`

**Comment by mike42** [comment]
Hi,

The range of characters is limited intentionally, since it is used to construct a command-line where shell escaping is not quite sufficient to prevent the library from being hijacked to write arbitrary files if the URL is user supplied.

This is a limitation of the implementation, so while we can include specific characters which are safe in our usage (put on a security hat and read the 'net use' and 'smbclient' calls in WindowsPrintConnector.php), the fact that we filter  input is not itself a bug.

I'm also open to reviewing a re-write of the current connector which passes credentials via some other means (such as a file or environment variable), if you have a way to lift this limitation.
