### ISSUE TITLE
redirect issue 

### ISSUE THREAD

**Issue by Khodour** [mike42/escpos-php#559]
Hello thanks for this great script 

i am having redirect issue , when i excute it from function inside a class its redirect me to index.php 

$connector = new FilePrintConnector("php://stdout");
		$printer = new Printer($connector);
		if ($printer)
		{
		$printer -> text("Hello World!\n");
		$printer -> cut();
		$printer -> close();	
		}

any idea why ?

**Comment by mike42** [comment]
Our code never redirects, that's your framework, so I don't have a specific answer for you.

I would suggest that you should:

- Start on the command-line (try to send text to your printer - without PHP)
- Build a self-contained script that you execute on the command-line (which will involve selecting a `PrintConnector` which matches the way that you were printing manually)
- Last, run the same code from your app, and find out how your framework handles and logs errors, because you will need that for debugging.

I say this because also have two issues with your code -

- `new FilePrintConnector("php://stdout")` does not work from the web. 
- `if($printer)` is not valid, you want `try {} catch {}` to pick up on errors.

Don't fix this in-place, you need to know how you are communicating with your printer before you start writing PHP code.

**Comment by Khodour** [comment]
alright i get it , so i can't print out because the printer is not connected to the server , i should use css and html to normal print
