### ISSUE TITLE
does client needs printer driver to print to AppSocket port 9100

### ISSUE THREAD

**Issue by teaone** [mike42/escpos-php#577]
I am sorry for this silly question, does client needs printer driver installed prior to print to AppSocket port 9100 ?

I want to print from FreeBSD client to Linux host where escpos-php installed. The printer has Linux driver. But the Star TSP100 do not provide driver for FreeBSD.

Thank you for your support.

**Comment by mike42** [comment]
So "no" is the short answer to that. This library is implemented in PHP (which runs server-side), and generates its own ESC/POS binary. It does not interact with vendor drivers at all.

**Comment by mike42** [comment]
I think you are solving the wrong problem.

Your setup seems to involve multiple platforms, drivers and print protocols, and you are asking if you need to add another. I think the answer is "no", but also, it sounds like your transport is not working at all, and transport problems have nothing to do with this library.

You are the one who is responsible for providing raw transport to an ESC/POS printer. As a small tip, you have an Ethernet printer and a server-side library for generating binary, so you should be on the Webserver, trying to drop off raw prints off with something like `netcat`. You need 0 vendor drivers to do it.

I would expect that a question that showed a verified setup like yours would look very similar to this:

---

I have a Star TSP100 which is configured to use its ESC/POS emulation mode. It is visible on the LAN via port 9100 (because it's an Ethernet printer), and I have a Linux/FreeBSD Webserver with PHP 7.2 which is serving up my web app for clients.

The server can't see the printer directly, but I set up a persistent, local tunnel using SSH, and I can send the words "Hello World" to the printer on the command-line like this:

    echo "hello world" | netcat 127.0.0.1 9988

This works on the computer running PHP, so the `NetworkedPrintConnector` to the example in the README to print.

    $connector = new NetworkedPrintConnector("127.0.0.1", 9988);
    $printer = new Printer($connector);
    $printer -> text("Hello World!\n");
    $printer -> cut();
    $printer -> close();
 
I tried to add the `SP2000` profile, which is a Star printer that supports similar instructions to mine.

    $profile = CapabilityProfile::load("SP2000")
    $printer = new Printer($connector, $profile);

Now, when I attempt to ABC with the snippet below, I expected the printer to do XYZ, but instead, it shows this output ( ... etc ... etc ... )

---

So verify setup, then use this library, in that order. Good luck!
