### ISSUE TITLE
Xprinter XP-N160I Print one time, turn off/on to print again

### ISSUE THREAD

**Issue by fullbackup** [mike42/escpos-php#579]
Hi, tested this printer on Ubuntu 16.04. working good if I print from text editor, but if I print from the script with the Cups processor using plain text It just print once and should be reseted to print again.

Any help? Thank you..

**Comment by fullbackup** [comment]
Now is printing two copies of the same job...but still has to be reseted after each job

**Comment by mike42** [comment]
Could you share some more information about how you have verified your setup?

- Try printing text raw from the command-line, not a text editor What is the command that works?
- What type of connection does your printer have? LAN? USB? CUPS is probably overkill, and you need to be sure you are getting raw data to the printer (ie, no vendor drivers).

**Comment by fullbackup** [comment]
Printer is working fine now after rebooting the computer..

**Comment by dannybrunomontecinos** [comment]
Hi fulbackup,
What profile you used for Xprinter printer?

**Comment by fullbackup** [comment]
I'm using "simple" now, using cups on linux. The only problem I have is if I turn on the printer, send the first job prints fine, second job it start printing from the 3rd line...

**Comment by fullbackup** [comment]
It seems that if I use some symbols like "-", ":", "/" while printing text, the second job and following comes out with a missing part... I took out all those symbols from the receipt and now everything is normal with text but I still couldn't print images...

**Comment by fullbackup** [comment]
After my last post I still got the same error. I made my way to print to /dev/usb/lp0 from terminal using cat and avoid CUPS and now is working fine, I'm closing this thread and open a new one as I'm getting other problems.

**Comment by mike42** [comment]
Good to hear.

For future readers, the only suggested use of CUPS is as an entry-point to more complex shared printer setups. Since you can already see your printer as a file, you don't need it.

If you must use CUPS with this library, remember to set up the printer with the `Generic / Text only` driver to avoid interaction with existing printer drivers. We already generate ESC/POS, so we have no need for vendor drivers. Running two drivers together is not helpful for debugging, don't do this.
