### ISSUE TITLE
Unable to give a print from web hosting server.

### ISSUE THREAD

**Issue by ankit1212** [mike42/escpos-php#588]
Hi, 
I have developed a web based inventory management project for myself using PHP and hosted it on BlueHost Linux shared hosting server.

I have implemented the Mike42 ESC-POS api using WindowsPrintConnector also tried with NetworkPrintConnector.
It works great on my local machine, when I run the project on my local machine, I can give print command and it prints great.

But when I deploy files on Web hosting server it gives error, it does not find printer because printer is connected on my local system. and I am giving a print from my website.

I am trying since 10 days but still did not get success, please guide me to achieve  my target.

I connect my thermal printer from USB to my laptop, I do not have router.

If it is possible to do from USB connection then please guide, if it is only achievable from router and LAN connection then I will purchase the same.

Printer:
Pegasus PR8021 (Purchase from Amazon.in)

**Comment by ankit1212** [comment]
I know this question has been asked too many times.
But still after looking into all answers, and FAQ answer, I did not get clear picture, what exactly I need to do to make it possible.

Please guide me.

**Comment by mike42** [comment]
Hello! Yes, this is a server-side library, which has its limitations. I normally just link people who are attempting to print from a shared web host to [the FAQ](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#can-i-print-from-my-server-on-the-internet), but it sounds like you've already read it.

I'm not really sure what I can add, other than to confirm that you need an architectural fix, not a code fix. The README does say-

> To make use of this driver, your server (where PHP is installed) must be able to communicate with your printer.

The README goes on to describe how you should be using the command-line **on the server** to verify your transport. Each possible approach to making this work this across the Internet has implications for things like cost, security, and reliability, among other things. You might, for example, consider:

- Moving to a cloud VM, where you have administrative access. You can then deploy a VPN server and PHP, and deploy a VPN client on the printer terminals, allowing everything to work as if it's all on the same LAN.
- Running your whole app on XAMPP on `localhost`, or from a raspberry pi on the same network
- Using client-side Javascript to pass data to a local print agent like `qz` (if you don't mind the complexity).

I'm going to close this issue off, because choosing one of these and making it work is not directly related to this library. I really don't mind whether you move the server, move the printer, add some plumbing, or use a different library entirely, the data transport in your application is for you to solve.

I am happy to take suggestions if you think there is any way to better clarify all of this in the project's documentation!

Best of luck with your app.

**Comment by 0l1v3r5** [comment]
> Hi,
> I have developed a web based inventory management project for myself using PHP and hosted it on BlueHost Linux shared hosting server.
> 
> I have implemented the Mike42 ESC-POS api using WindowsPrintConnector also tried with NetworkPrintConnector.
> It works great on my local machine, when I run the project on my local machine, I can give print command and it prints great.
> 
> But when I deploy files on Web hosting server it gives error, it does not find printer because printer is connected on my local system. and I am giving a print from my website.
> 
> I am trying since 10 days but still did not get success, please guide me to achieve my target.
> 
> I connect my thermal printer from USB to my laptop, I do not have router.
> 
> If it is possible to do from USB connection then please guide, if it is only achievable from router and LAN connection then I will purchase the same.
> 
> Printer:
> Pegasus PR8021 (Purchase from Amazon.in)

did you finally find a solution? if yes which one ? thank you.
