### ISSUE TITLE
Font Size and examples are not working

### ISSUE THREAD

**Issue by mandeepmavi** [mike42/escpos-php#61]
Hi friends, I was playing with this escpos-php, I am able to use ESCPOS.php But only if I put receipt file in same folder. I files in example folder are not working. giving error.

Also for Font I am able to go bigger, but not able to print small fonts.
Any suggestion
Regards

**Comment by mike42** [comment]
First up, yes, the font sizes given to `setTextSize()` are integer multipliers of height and width, so you can't go smaller (protocol limitation). FONT_B might help you out though- on all printers I've used, it's been slightly smaller than FONT_A.

This snippet is from `examples/demo.php`:
```php
/* Fonts (many printers do not have a 'Font C') */
$fonts = array(
	Escpos::FONT_A,
	Escpos::FONT_B,
	Escpos::FONT_C);
for($i = 0; $i < count($fonts); $i++) {
	$printer -> setFont($fonts[$i]);
	$printer -> text("The quick brown fox jumps over the lazy dog\n");
}
$printer -> setFont(); // Reset
$printer -> cut();
```

Now your issue with the examples is strange, because they 'work for me'. Can I get more info about your setup? This would let me determine whether there is some bug or documentation gap here.

- OS
- PHP version
- Printer make, model, interface (eg. a FooBar 3000 on Ethernet)
- How are you running the examples? They are designed for command-line, so this would be the folder you're in and command you're running.
