### ISSUE TITLE
ESCPOS NOT SUPPORTED PRINTER

### ISSUE THREAD

**Issue by Linneaus16** [mike42/escpos-php#627]
Have a problem using Receipt Printer with the Manufacturer of POSTECH and model of PT-RP-T88VMP

**Comment by mike42** [comment]
Could you clarify whether this printer is marketed as understanding ESC/POS, and if so, what the problem is?

I think the best way to show an issue is to include a PHP code snippet showing how you are using the printer, a description of what you expected, and a picture of the corresponding (printed) output showing what is actually printing.

**Comment by Linneaus16** [comment]
I am sorry for my statement. What I mean is the API does not support this kind of printer. The POSTECH printer is not included to the supported printer of Escpos

**Comment by mike42** [comment]
It is not clear to me whether the POSTECH PT-RP-T88VMP understands ESC/POS. We only include it in the list if somebody tests it and finds that it works.

If you have one, can you try to do a raw print of [any of these files](https://github.com/mike42/escpos-php/tree/development/test/integration/resources/output) and report back what the output looks like?
