### ISSUE TITLE
Installation steps

### ISSUE THREAD

**Issue by Karumaj** [mike42/escpos-php#633]
Hello,  have tried to follow much of the set up information available on this driver beginning with the blog [blog](https://mike42.me/blog/2015-03-getting-a-usb-receipt-printer-working-on-linux) but getting to install a Hoin HOP-H58 therma printer (ESC/POS compatible) on Ubuntu 18.04 is still problematic. I wish there could be a step-by-step guide especially for those very new to Linux & php and Linux installations in general. For this install I am not sure if the way is to download the link given on the blog page or if is to use github and what are the steps involved for each. 

Please assist

**Comment by mike42** [comment]
@Karumaj - 

I suggest using the install steps in the README use `composer` to add `escpos-php` to your project. If you're new to PHP, one of my favourite bookmarks is [phptherightway.com](https://phptherightway.com/), which includes a section on package management.

From your question, I'm not sure whether you ever got raw printing working (eg. `echo hello > /dev/usb/lp1`). Plainly, you need to research raw printing and get it working before you attempt to use this package, since we can't solve data transport issues from PHP.
