### ISSUE TITLE
WindowsPrintConnector Issue

### ISSUE THREAD

**Issue by asjado** [mike42/escpos-php#637]
Hey, I've rendered HTML in my Controller, how can I pass that HTML to print, I couldn't find any method in you library. If I pass as text so it prints the same HTML code.
I also tried with PDF but it gives error of Imagick extension even this extension already installed in my php version.
I'm using Larvel 5.4 and PHP 7.1.11
@mike42

**Comment by mike42** [comment]
There are two issues here. 

For HTML input, we don't support it. This library exposes an API for accessing a whole lot of ESC/POS printer features directly, and that is the way it's intended to be used.

If you are determined to use HTML, then you can use existing tools to convert HTML to an image (I use wkhtmltoimage), and then print the image. Just be aware that since images involve a lot of data, this will typically make your prints take much longer.

For your `imagick` issue, please check your assumptions by reading the extension list in `<?php phpinfo() ?>`. The test before we run `imagick` ([link](https://github.com/mike42/escpos-php/blob/ec9c539c31a81076d64446ae78bb36f4908b9309/src/Mike42/Escpos/EscposImage.php#L396)) is quite idiomatic, so if you get an error saying that `loadPdf` requires `imagick`, it most likely means that the extension is not loaded in your setup.

```
public static function isImagickLoaded()
{
    return extension_loaded('imagick');
}
```
