### ISSUE TITLE
Print Server

### ISSUE THREAD

**Issue by olkotz** [mike42/escpos-php#654]
Hello Mike!! I have an issue with a Ethernet POS Printer... i developed a system for my Fathers wife Pizzeria, in the system i have a XAMPP server Apache with MySQL (i planed buy a new server and install Linux on it), a POS Printer via USB installed over the server and onother Ethernet POS Printer installed on the kitchen. Sometimes, the cashier on front desk sends an a kitchen command (print job) for the the kitchen with a pizza order, and at the same time onother employee send other kitchen command taken telephone way... both php pages try to send the print job via Mike42 classes, but only one of the print jobs is printed.... Is there any way that can i manage the print jobs?

Thank you for your Time and obiusly for your work!!! Rocks man!!!

Thank you so so much!!!

**Comment by mike42** [comment]
Hm, are these both being printed through the same XAMPP server?

Maybe you could use a print server to queue everything (CUPS on Raspberry Pi is a worthwhile setup to evaluate), but if these are all coming from the same server, then it would be simpler to [lock a file while you print](http://php.net/manual/en/function.flock.php), so that only one request can access the printer at the same time.
