### ISSUE TITLE
Printer loses default character table

### ISSUE THREAD

**Issue by zstergios** [mike42/escpos-php#658]
I have an Thermal Printer "Alpha Team" 80mm using Ethernet.

Using the default codePage and clicking on "Print Codepage Char" it prints normaly the greek chars. 
http://prntscr.com/lfsnrn

After that I print a reciept via escpos library and greeks are not displayed correctly.
After that I re-click the '"Print Codepage Char" and greeks are NOT displayed correctly.

If turn off/on the printer, then the default settings starts working again until I print via escos-library

I'm  100% sure it means the library changes the default codepage.
i tried programmatically to switch it to CP737 (found the 14 table, via character-table.php example) 
$printer ->selectCharacterTable(255);
$printer->selectCharacterTable(14); //CP737

All PHP files are UTF-8 encoded and texts are UTF-8.

```
$connector = new NetworkPrintConnector('0.0.0.0',9100);
$profile = DefaultCapabilityProfile::getInstance();
$printer = new Printer($connector,$profile);
$printer ->initialize(); //resets based on comments, I tried with & without
$printer ->selectCharacterTable(255);
$printer->selectCharacterTable(14);
$printer->setJustification(Printer::JUSTIFY_CENTER);
$printer->text($_POST['data']['text1']);
$printer->feed(2);
$printer->text($_POST['data']['text2']);
$printer->feed(2);
$printer->cut();
$printer->pulse();
$printer->close();
```

**Any suggestions?**

**Comment by mike42** [comment]
I find this tricky to answer because it looks like you are configuring vendor driver settings *and* using escpos-php. Both of these are independently speaking to the printer. So first up, please set the default code page back to 0, then you should uninstall the printer from your computer and take out that as a variable.

The `escpos-php` library accepts UTF-8 input when you call `text()`, and will automatically convert it to the correct code page in the background (it calls `selectCharacterTable()` as needed). It needs to use the correct `CapabilityProfile` to know which code pages are available, but your printer has no profile yet! See [here](https://github.com/receipt-print-hq/escpos-printer-db/blob/master/doc/add-your-printer.md) if you have documentation about available code pages, and then we can hopefully improve on this next part for future users.

To do character encoding manually as CP737 at code page 14, you would set the code page to 14 from PHP, manually call `iconv` or `mb_convert_encoding` to convert from UTF-8 to CP737, and then `textRaw` to send this text to the printer (in your case, don't use `text()`: on the `default` profile it will encode text for an Epson printer, which probably has different code pages to yours).

I have not run this code, but completely manual character encoding should look something like this:

```php
$connector = new NetworkPrintConnector("10.x.y.z", 9100);
$profile = CapabilityProfile::load('default');
$printer = new Printer($connector,$profile);
$printer->selectCharacterTable(14);
$printer->textRaw(mb_convert_encoding("Γειά σου Κόσμε\n",  "CP737", "UTF-8"));
$printer->feed(2);
$printer->cut();
$printer->close();
```

Best of luck!

**Comment by zstergios** [comment]
I just come here to tell you that I found solution and you found it before I write!
Nice!!
Yes this is the solution, but I use icov

`function encode($txt,$enc='CP737')
{
	return iconv("UTF-8",$enc."//TRANSLIT//IGNORE",$txt);
}`

**Comment by zstergios** [comment]
You can mark it as solved, this may help some other people
