### ISSUE TITLE
WindowsPrintConnector.php Line 145 pregmatch condition, perhaps too strict, " Printer 'Receipt' is not a valid printer name" 

### ISSUE THREAD

**Issue by 3dr14n** [mike42/escpos-php#66]
When I run the code, it always return "Couldn't print to this printer: Printer 'Receipt' is not a valid printer name. Use local port (LPT1, COM1, etc) or smb://computer/printer notation." error. The command line is fine, it prints. So I guess the rules in preg_match is too strict so I made a little work around in the code, though I think it's not right, but it works for now as I'm making the layout for my receipt using EPSON TM-T88IV. This is the code: "else if(preg_match(self::REGEX_PRINTERNAME, $dest) == 1) {" i changed it to "else if($dest == "Receipt") {" where "Receipt" is the name of my printer.

**Comment by mike42** [comment]
Good spot- You found a bug that I introduced while working on #64. I've fixed the regex and added some extra test cases around it now.

The regexes are quite strict, so that the library can't be tricked into writing data to arbitrary file or network paths. In your case, it will happily copy the file to \\localhost\Receipt (Windows), or doing a `smbclient` print command to smb://localhost/Receipt (Linux).

**Comment by 3dr14n** [comment]
It's working now. Thank you so much!

**Comment by velizupll** [comment]
How do I add a thermal printer that connects via USB?

**Comment by alfian1998** [comment]
Couldn't print to this printer: Printer 'DESKTOP-MG3459I/POS-58' is not a valid printer name. Use local port (LPT1, COM1, etc) or smb://computer/printer notation.
