### ISSUE TITLE
Dot matrix printer support

### ISSUE THREAD

**Issue by rajitha-bandara** [mike42/escpos-php#666]
Can this library be used with dot matrix printers? It's a Epson lq310.

It looks like Esc/p2 commands. 

btw, your library worked well for me in thermal printers. thanks a lot.

**Comment by mike42** [comment]
So generally, yes ESC/POS dot matrix printers are fine. I have an Epson U220B (dot matrix receipt printer) which I use with this library with great success.

The problem is that you do not have an ESC/POS printer. They sound similar to us, but ESC/POS and ESC/P2 are incompatible page description languages, so your ESC/P2 printer will be very confused by the output of this library.

Take a look at the ESC/P2 output of CUPS though, I think that other software will be more useful to you here.

**Comment by rajitha-bandara** [comment]
Thanks @mike42 
It's a good news for me that Epson U220B is working fine. I may try this also.
