### ISSUE TITLE
Add Feature

### ISSUE THREAD

**Issue by mdestafadilah** [mike42/escpos-php#668]
Hi Mike, 

Impreseive your library... :+1: 

have you add this [https://github.com/mike42/png2escpos](https://github.com/mike42/png2escpos) to your escpos-php ?

Thanks mike!

**Comment by mike42** [comment]
Apologies for slow response. It would be interesting, and I appreciate the suggestion, but I'm not considering it as an option.

I have previously thought that `png2escpos` had the potential to speed up image processing for us, or to be used as a fallback when the gd/imagick extensions are not present, but I think we have these under control:

- The `ImagickEscposImage` class has been performance-optimized, and is used automatically if `imagick` is present. The conversion to ESC/POS image format from PNG is probably not a bottleneck if `imagick` is available.
- You currently require either `imagick` or `gd` to print images, but these will soon be optional. I have written a native PHP image processing library, which can read PNG files. This will be introduced as a dependency of a future release, making gd and imagemagick optional extras. Check out [mike42/gfx-php](https://github.com/mike42/gfx-php) if interested.

A third, fairly niche reason to use a native program might be to provide higher quality quantization, but 'png2escpos' does not provide this.

The `png2escpos` program itself does not implement the complete suite of image output formats and commands that `escpos-php` already outputs, and it would be a distraction to duplicate that effort in C just so that we can call it from PHP code.

There are lastly the issue of distribution and installation for our users, but I don't think there's a need to solve that at this point: our users are PHP programmers, and we have already got this covered within the PHP eco-system.
