### ISSUE TITLE
No Printing with Hp laser jet

### ISSUE THREAD

**Issue by mohamedhassan1** [mike42/escpos-php#676]
```
<?php
require __DIR__ . '/../../autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
try {
    //$connector = 'HP LaserJet Professional P1102';
    $connector = new WindowsPrintConnector("HP LaserJet Professional P1102");
    /* Print a "Hello world" receipt" */
    $printer = new Printer($connector);
    $printer ->initialize();
    $printer ->text("Hello World!\n");
    $printer -> feed(2);
    $printer ->cut();
    $printer -> pulse();
    $printer -> close();
} catch (Exception $e) {
    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}

```

**Comment by mike42** [comment]
HP LaserJet printers do not understand ESC/POS. This driver will not be useful on that hardware, since we only target ESC/POS printers.

See also [I have a printer that does not understand ESC/POS. Can I use this driver?](https://github.com/mike42/escpos-php/blob/0659800298f4843d51b5e0413263a8e62727c732/doc/FAQ.md#i-have-a-printer-that-does-not-understand-escpos-can-i-use-this-driver) in the FAQ.

**Comment by mohamedhassan1** [comment]
Okay,thanks for your reply
Can you recommend me a printer to use?!
i will use this in a uploaded web application

**Comment by Stenerson** [comment]
Check out the [supported printer list on the readme](https://github.com/mike42/escpos-php#printers).
