### ISSUE TITLE
please add new printer 

### ISSUE THREAD

**Issue by Xatta-Trone** [mike42/escpos-php#677]
printer model sato ws4  series

**Comment by mike42** [comment]
Please see the FAQ entry [Can you add support for Printer X?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#can-you-add-support-for-printer-x).

We take reports of "this printer works" / "these features work" to create the list of printers for the README, and also collaborate on a database of ESC/POS printers to record which features work. Without somebody who owns this type of printer volunteering test it out, this issue cannot be completed.

If you want to try it out yourself, remember to check the vendor documentation for ESC/POS support, and to use the "simple" `CapabilityProfile` - check the README for how to create a `Printer` with a profile. Then, report back if you get good output, so that I can add it to the list. :)
