### ISSUE TITLE
add printer xprinter XPN-160II

### ISSUE THREAD

**Issue by sebitas0623** [mike42/escpos-php#680]
Hello !!!!

I have a printer xprinter XPN-160II, could you add this model to the library?

thank you

**Comment by mike42** [comment]
Hi,

It may already work, but there is no way to know without trying. We actually have an FAQ entry for [Can you add support for Printer X?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#can-you-add-support-for-printer-x).

We take reports of "this printer works" / "these features work" to create the list of printers for the README, and also collaborate on a database of ESC/POS printers to record which features work. Without somebody who owns this type of printer volunteering test it out, this issue cannot be completed.

If you want to try it out yourself, remember to check the vendor documentation for ESC/POS support, and to use the "simple" `CapabilityProfile` - check the README for how to create a `Printer` with a profile. Then, report back if you get good output, so that I can add it to the list. :)
