### ISSUE TITLE
Working with toRasterFormat()

### ISSUE THREAD

**Issue by alanleyva** [mike42/escpos-php#681]
Hi Mike.

I manage to make a working connection with the Chrome [Bluetooth devices on the Web](https://developers.google.com/web/updates/2015/07/interact-with-ble-devices-on-the-web) feature to a Bluetooth Printer.

I'm trying to print the company logo on the recipt using your libray.
I do not need to connect to the printer but just to create the image to ESC/POS "ready"
I try using the `$img -> toRasterFormat()` function but the output does not seem to work for me.

It certantly does something, but I'm not sure how to make it work.
When I send that data to printer here is what it gets:

![img_3919](https://user-images.githubusercontent.com/26827563/50938643-5d713300-1436-11e9-81be-95f87f25c237.JPG)

What function do I need to use to generate the "code string" to use?
My intention is to save this code string to use it any time it is needed.

Thanks!

**Comment by mike42** [comment]
I don't believe your usage includes any actual print commands. I should be able to point you at the best examples to use if you can clarify the I/O and compatibility constraints that you're working with.

Would you mind sharing the model of printer you are using, and the PHP code you've come up with so far?

**Comment by mike42** [comment]
This project is all PHP. [Here is an image printing example to start with](https://github.com/mike42/escpos-php/blob/0659800298f4843d51b5e0413263a8e62727c732/example/bit-image.php). Try also `bitImageColumnFormat`, and change `php://stdout` to something like `foo.bin` to write to a file.

It's still not clear to me what type of binary data your printer is going to understand (does it have image printing commands at all? Does it know the ESC/POS image commands? which ones?), or how you are taking the output of this library and sending it to your printer without mangling it.

I think that these are basic pieces of information to start your troubleshooting. Contact your vendor if you need clarification on the supported commands, as trial and error can take a lot of paper :)

**Comment by alanleyva** [comment]
Hi Mike.
Sorry for taking too long to respond, I've been stuck with a lot of changes lately

I'm back to trying to make the logo work on the tickets.

Okay so, the printers I'm using do accept ESC/POS image commands, [here](http://www.zjiang.com/en/init.php/product/index?id=34) is the page of the manufacturer.

Now, what I'm trying to accomplish is to save all the logo 'code' inside a table row on my DB
And send that to the printer via Javascript.

I'm pretty sure that what I need to use is:
```
$tux = EscposImage::load("resources/tux.png", false);
$printer -> bitImage($tux);
```

But instead of sending the print commando to the priner, I need it to be return, something like:
```
$image = $printer -> bitImage($tux);
```
Then I can use that response to send it to the printer via Javascript.

Is it posisble?

**Comment by alanleyva** [comment]
Okay, I think we're getting closer.
Using `$tux->toColumnFormat() ` i got this response:
![screen shot 2019-03-04 at 17 44 05](https://user-images.githubusercontent.com/26827563/53772813-230b9b80-3ea5-11e9-9671-b1971714660b.png)

And this is my logo .png
![foo_icon](https://user-images.githubusercontent.com/26827563/53772881-5c440b80-3ea5-11e9-8b3a-186eae7bfd97.png)

**Comment by mike42** [comment]
You are not quite on the right track, so here is some more detail. Just remember you are solving three unrelated problems:

- Command compatibility with printer
- Transport out of PHP
- Eventual delivery to printer (from Javascript?), which I wont be talking about

Firstly, you really do need to call an image printing command on a `Printer` object to print an `EscposImage`, that is just how this API works. :)

Try printing to a file so that you have the binary data. You can then try printing this raw, serving it up (or use `echo file_get_contents("test.bin")`) to send that to the browser, or otherwise making sure that you can get these commands to your printer, and that they are understood.

As always, if you get gibberish, then eliminate variables as possible, because many things will modify binary output on the way to the printer if you let them.

```php
<?php
require __DIR__ . '/vendor/autoload.php';

use Mike42\Escpos\EscposImage;
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;

$logo = EscposImage::load("logo.png");

$connector = new FilePrintConnector("test.bin");
$printer = new Printer($connector);
$printer->bitImageColumnFormat($logo);

$printer->cut();
$printer->close();
```

If I `cat test.bin > /dev/usb/lp0`, I then get this output:

![image](https://user-images.githubusercontent.com/2080552/54083927-4be8d080-437e-11e9-9f6f-19b4fdd889eb.png)

That is your column format data, spread through some line-spacing and image-related commands, followed by a cut. Most receipt printers are pure black-and-white, and you will get better results if you convert your image manually to black and white.

Next, use a `DummyPrintConnector` so that you can avoid writing to a file. This is based on an example in the repository called `281-get-data.php`.

```php
<?php
require __DIR__ . '/vendor/autoload.php';

use Mike42\Escpos\EscposImage;
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\DummyPrintConnector;

$logo = EscposImage::load("logo.png");

$connector = new DummyPrintConnector();
$printer = new Printer($connector);
$printer->bitImageColumnFormat($logo);

$printer->cut();

// Get the data out as a string
$data = $connector -> getData();
$printer->close();

// Return it however you like
header('Content-type: application/octet-stream');
header('Content-Length: '.strlen($data));
echo $data;
```

You seem to know what you want to do with regards to transport, so the rest is up to you. You can remove `cut()` at the end, but the `ESC @` (initialize) command will always be sent at the start of a receipt from this library, since we track the state of the printer between commands.
