### ISSUE TITLE
Ethernet security

### ISSUE THREAD

**Issue by zstergios** [mike42/escpos-php#693]
Hi, I am using the public IP of network that printer is installed and I have opened the 9100 port. 

My concerns is how I can secure this communication.  On that way everyone will print if discovers the IP.

Any thoughts?

My app is an web app running on webserver and client can send their prints to the "local" printer

**Comment by mike42** [comment]
Your printer exposes port 9100 for LAN printing, and making that visible on the Internet is indeed a bad idea.

We have a fairly extensive [FAQ](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#can-i-print-from-my-server-on-the-internet) entry about internet printing, because a lot of developers seem surprised that PHP can't see their printer once they deploy.

I personally use a simpler setup, and just run PHP on the LAN, since it's quite reliable. To modify your current setup, you could look into either:

- Using an authenticated tunnel of some sort. VPN is the standard way to let a host on the internet see your LAN without letting anybody else in, but `stunnel` (TLS) and plain SSH port forwarding work as well.
- Send print jobs from within the LAN. Users have had success doing a POST from Javascript to an app (PHP or otherwise) running on localhost, which can pass information to the printer on the LAN. This works best as you add more clients, since you don't need to know about all of the printers.

Whatever you choose, you will need to be prepared to do some independent research and debugging. This library will only generate binary and pass it on by writing to a socket, file, or running a command to print: The details of how this gets to your printer are up to you.
