### ISSUE TITLE
Execute Script from Other Computer

### ISSUE THREAD

**Issue by habibridho** [mike42/escpos-php#71]
I successfully run your examples using the server computer. However, when I execute the scripts from another computer, I got no result (no error and the printer is not printing). Is it possible to execute your example by sending a GET request to, for example, `192.x.x.x/escpos/example/receipt-with-logo.php`?

The reason why I did this and not using the network interface is, the client I used is a tablet. So I think it is easier to put the scripts in a server (in my case a raspberry) which is connected to a printer via USB.

**Comment by mike42** [comment]
Hi- This is basically the use case that the driver is created for, so you can certainly do it ([example](https://github.com/mike42/Auth/blob/master/lib/misc/ReceiptPrinter.php), [more complex example](https://github.com/Dolibarr/dolibarr)).

The `receipt-with-logo.php` example is printing to standard output, which is only available on command-line PHP, so your webserver may be logging errors somewhere that you aren't checking, such as `/var/log/apache2/error_log` for Apache.

See links in [this table](https://github.com/mike42/escpos-php#interfaces-and-operating-systems) as the proper reference, but you need to set up your printer at the top of the script with a `PrintConnector` suitable for USB printing on your platform. For the Raspberry Pi, it would be something like replacing this line in `receipt-with-logo.php`:

`````php
$printer = new Escpos();
`````

With this:

`````php
$connector = new FilePrintConnector("/dev/usb/lp0");
$printer = new Escpos($connector);
`````

Three things to check if you need to post any follow-up questions-
- Assuming you can print from the command prompt, put the correct device file in place of `/dev/usb/lp0` above!
- Research PHP logging- If you see no errors displayed, your PHP is set to a production setup, not a development one. Adjust this to get more information.
- The web user, `www-data` will need to be in the `lp` group [see link](http://mike.bitrevision.com/blog/2015-03-getting-a-usb-receipt-printer-working-on-linux), so `sudo -u www-data bash` for all your testing, so that permission issues are visible.
