### ISSUE TITLE
Redmon/GS/PDF/ESC

### ISSUE THREAD

**Issue by mrbrowni** [mike42/escpos-php#717]
I have set up Redmon and GS to print a receipt from POS software into PDF. Then I feed the PDF to escpos to manipulate and append something. (The reason for PDF as intermediary is because if Epson TM20II is used, it prints ESC bitmap format which I lose sight into the text on receipt (and I am not a big fan of tesseract)).

The problem I encounter is the PDF format is different from what it would directly print to Epson printer. I've tried to limit the width (in GS) to 3.125", but the fonts and layout and spacing in PDF still looks like it was intended for a A4 paper.

Mike, any experience in:
1) how can I force the print file to be esc text (as opposed to esc bitmap)?
2) or, how do I generate a PDF that's formatted to the receipt paper size?

Thanks a lot!

**Comment by mrbrowni** [comment]
I solved (2). There is a setting on Ghostscript Printer (or any printer driver) to specify paper sizes.

Still need some help on (1) if possible. My receipts are all text (from ERPLY POS). Why would the Epson driver create bitmap ESC rather than text? Is there an option to force it to be text at all?

**Comment by mike42** [comment]
@mrbrowni - Is there any way you can boil this down to a question about `escpos-php` only?

We are here to build a receipt printing library for PHP apps, but I think your question is about how to use other software first, which would not be something that you will get help with here.

I am also not sure how you arrived at a setup with so many conversions, could you explain a bit more what the actual problem is that you're trying to solve?

**Comment by mrbrowni** [comment]
Got it. I have another escpos printing PDF question, which I will open a different issue. Thanks.
