### ISSUE TITLE
Problem in using EscposImage

### ISSUE THREAD

**Issue by geydson** [mike42/escpos-php#725]
Could you help me, I'm facing the problem below, when trying to print a logo

Erro:
Parse error: syntax error, unexpected 'load' (T_STRING), expecting variable (T_VARIABLE) or '$' in C:\xampp\htdocs\hamanaPDV\controllers\salesController.php on line 190

Code:
$img = BASE_URL."/assets/images/logo.jpg";
$printer = new Mike42\Escpos\Printer($connect);
$logo    = new Mike42\Escpos\EscposImage::load($img, false);

I'm using an unlisted printer, Print-iD model of the Control iD brand, all the functionalities work well, however the only problem is the printing of the logo, which presents this error mentioned above, using another system I can print the logo normally.

**Comment by mike42** [comment]
Please compare your code to [a syntactically correct example from the repository](https://github.com/mike42/escpos-php/blob/5e904fed73704dcf22c4c4db2f31b329fb7a0b5f/example/graphics.php#L13) so that you can see the error for yourself.

You may also consider bookmarking "[PHP parse/syntax errors; and how to solve them?](https://stackoverflow.com/questions/18050071/php-parse-syntax-errors-and-how-to-solve-them)".

**Comment by geydson** [comment]
I believe that this is not the problem, because if I remove the line to load the image, it does not occur the problem and I can print, when adding the line the error occurs again.
