### ISSUE TITLE
TM-U220D issues

### ISSUE THREAD

**Issue by Neobugu** [mike42/escpos-php#737]
while using #339 it does resolve the part of text size but it completely ignores function cut, also is there a way to check what kind of printer is? so it can switch between function/workarounds?

Thanks in advance

Current code:

    $connector = new WindowsPrintConnector("barra1");
        $profile = CapabilityProfile::load("TM-U220");
        //$connector = new WindowsPrintConnector("smb://Guest@DELLNICOLAS/ticket");
        $printer = new Printer($connector,$profile);
        $printer -> setJustification(Printer::JUSTIFY_CENTER);	
        $printer -> setTextSize(1, 2);
        $printer -> selectPrintMode(Printer::MODE_DOUBLE_WIDTH);
        $printer -> text("Orden # $comanda\n");
        $printer -> selectPrintMode();//Which doesnt resets
        $printer -> setTextSize(1, 1);
        $printer -> text("$aaa : $num\n");
        $printer -> setTextSize(1, 2);
        $printer -> setTextSize(1, 1);
        $printer -> text("Comanda: $comanda\n");
        $printer -> text("Mesero: $r_todo[3]\n");
        $printer -> text("MESA   $r_todo[4]  MESERO    $r_todo[2] PERSONAS    $r_todo[5] \n");
        $printer -> text("Servicio: Comedor           $fecha\n");
        $printer -> setJustification(Printer::JUSTIFY_LEFT);
        $printer -> setTextSize(1, 1);
    $printer -> text("----------------------------------------\n");
    $printer -> text("$imprimir");        
    $printer -> text("----------------------------------------\n");
    $printer -> text("                                $hora\n");
    $printer -> feed();
    $printer -> cut();//ignores
    $printer -> close();

**Comment by Neobugu** [comment]
any advice to make a function to print a character to the whole width? kinda like for surpressing

    $printer -> text("----------------------------------------\n");

**Comment by mike42** [comment]
There are a few questions here, so I'll be brief.

For cutting, I can't test an alternative command, since my TM-U220 has no cutter. Do you know the binary command to cut on your printer? You can pass any binary to `$printer -> getPrintConnector() -> write(...)` as a work-around, you just need to know what to send.

You do need to specify a profile so that this library knows how to switch things, we don't ask the printer to identify itself. You can use `$printer -> getPrinterCapabilityProfile() -> getId()` to identify which profile is being used from your own code.

For repeating characters, no there is no feature for that. In theory this is possible to calculate, but I would suggest just using `str_repeat("-", 40) . "\n"` if you need to be able to make variable-width rules.

I would also test trying to replace "-" with some characters from [CP437](https://en.wikipedia.org/wiki/Code_page_437), such as '─' or '═', to avoid the plain-text look.

**Comment by Neobugu** [comment]
Just a doubt, while sending to print, it doesnt send texts with * at the beggining, is there any issue or a workaround to send it? FE: * TEXT TO PRINT;
