### ISSUE TITLE
print from html to image failed

### ISSUE THREAD

**Issue by gbhaskar590** [mike42/escpos-php#74]
hell,
 I am using print from html to image from example but i am getting following error

Command wkhtmltoimage -n -q --width '40' 'http://en.m.wikipedia.org/wiki/ESC/P' '/tmp/escposhKuqej.png' failed:

I am not understanding why this error comming.

**Comment by mike42** [comment]
Marked as a bug because the error messages given by this example could be clearer.

The example shows that HTML must be rendered to an image before it can be printed. I'd suggest attempting the same command on the command-line, which will give you more information about why the tool is not working-

    wkhtmltoimage -n -q --width '40' 'http://en.m.wikipedia.org/wiki/ESC/P' '/tmp/escposhKuqej.png' 

It's often either not installed, or is running without an X server (which has a [standard workaround](https://www.google.com.au/webhp?q=wkhtmltopdf%20xvfb)).
