### ISSUE TITLE
 Printer not working on hosting site but works on localhost

### ISSUE THREAD

**Issue by YandryHN** [mike42/escpos-php#753]
Hello I am going to you as a last resort since I am trying to send a ticket for printing from my accommodation 1 and 1 a thermal printer brand "aqprox" which is connected to my PC.

It's all very strange when I do the tests on my localhost print the ticket to the first, without delay or delay but when I upload it to the server it gives me this error:

("smbclient '// infong-es180 / POS' -c 'print -' -N" failed with exit code 127: sh: 1: smbclient: not found).

Any possible idea or solution ???. then I leave the code written in PHP.

```
<?php


require __DIR__ . '/ticket/autoload.php'; //Nota: si renombraste la carpeta a algo diferente de "ticket" cambia el nombre en esta línea
use Mike42\Escpos\Printer;
use Mike42\Escpos\EscposImage;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;

/*
	Este ejemplo imprime un
	ticket de venta desde una impresora térmica
*/


/*
    Aquí, en lugar de "POS" (que es el nombre de mi impresora)
	escribe el nombre de la tuya. Recuerda que debes compartirla
	desde el panel de control
*/

$nombre_impresora = "POS"; 


$connector = new WindowsPrintConnector($nombre_impresora);
$printer = new Printer($connector);
#Mando un numero de respuesta para saber que se conecto correctamente.
echo 1;
/*
	Vamos a imprimir un logotipo
	opcional. Recuerda que esto
	no funcionará en todas las
	impresoras

	Pequeña nota: Es recomendable que la imagen no sea
	transparente (aunque sea png hay que quitar el canal alfa)
	y que tenga una resolución baja. En mi caso
	la imagen que uso es de 250 x 250
*/
/* Initialize */
$printer -> initialize();



# Vamos a alinear al centro lo próximo que imprimamos
$printer->setJustification(Printer::JUSTIFY_CENTER);

/*
	Intentaremos cargar e imprimir el logo
*/
try{
	$logo = EscposImage::load("geek.png", false);
    $printer->bitImage($logo);
}catch(Exception $e){/*No hacemos nada si hay error*/}

/*
	Ahora vamos a imprimir un encabezado
*/

$printer->text("\n"."CRIL SL - CENTRE DE REHABILITACIÓ I LLENGUATGE" . "\n");

date_default_timezone_set("Europe/Madrid");
$printer->text(date("\n"."d-m-Y H:i") . "\n");
$printer->text("------------------------------------------------");
/*
	Ahora vamos a imprimir los
	productos
*/
	/*Alinear a la izquierda para la cantidad y el nombre*/
	$printer->setJustification(Printer::JUSTIFY_CENTER);
	$printer->text("SI US PLAU ESTIGUI PENDENT DE LA PANTALLA"."\n");

    
/*
	Terminamos de imprimir
	los productos, ahora va el total
*/
$printer->text("------------------------------------------------");
 
/*
	Podemos poner también un pie de página
*/
class Producto{
 
	public function __construct($n_tickets){
		$this->n_tickets = $n_tickets;
		
	}
}
 


$printer->setJustification(Printer::JUSTIFY_CENTER);
$printer -> setTextSize(2, 2);
$printer->text("\n"."EL SEU NÚMERO ÉS"."\n");
$printer -> setTextSize(5, 5);
$printer->text("\n". $_POST['n_tickets'] ."\n");
$printer -> setTextSize(1, 1);
$printer->text("------------------------------------------------");
$printer -> setTextSize(1, 1);
$printer->text("\n"."AQUEST NÚMERO NO IDENTIFICA UN ORDRE , LA VISITA ESTÀ CONDICIONADA PER L'HORA ASSIGNADA"."\n");
$printer->text("------------------------------------------------");
$printer->setJustification(Printer::JUSTIFY_CENTER);
$printer->text("\n"." PER A QUALSEVOL DUBTE O CONSULTA SI US PLAU CONTACTI AMB ATENCIÓ A L'USUARI TELF:934 25 53 54"."\n");
$printer->text("------------------------------------------------");


/*Alimentamos el papel 3 veces*/
$printer->feed(3);

/*
	Cortamos el papel. Si nuestra impresora
	no tiene soporte para ello, no generará
	ningún error
*/
$printer->cut();

/*
	Por medio de la impresora mandamos un pulso.
	Esto es útil cuando la tenemos conectada
	por ejemplo a un cajón
*/
$printer->pulse();

/*
	Para imprimir realmente, tenemos que "cerrar"
	la conexión con la impresora. Recuerda incluir esto al final de todos los archivos
*/
$printer->close();

header('Location: listado-pacientes.php');
?>
```

**Comment by YandryHN** [comment]
@mike42  
**Any idea how to fix it ?**

**Comment by mike42** [comment]
You are trying to print from your server, which doesn't have the necessary software to print, and most likely can't see your printer anyway.

There are many possible work-arounds discussed in [the FAQ](https://github.com/mike42/escpos-php/blob/5e904fed73704dcf22c4c4db2f31b329fb7a0b5f/doc/FAQ.md#can-i-print-from-my-server-on-the-internet), but if you have the option to, then it is simplest to host the app on your LAN instead.

**Comment by mutiemule** [comment]
Printing on local will work well with this package.

However, to print online, you will need to develop a desktop service which has to be installed on the local computer where you need printing to be done.  This is because PHP is a server-side scripting language, so once you put this online, it won't be able to communicate to the local printer. Thus, you need a client service running on the local machine and this is where electron js and node js come into play.

I resolved this by developing an electron js service based on [node-escpos package](https://www.npmjs.com/package/escpos) which can receive commands from the online print command and then communicate those commands to the printer through USB. 

Operating System does not matter in this case, you can be hosting on Linux based server and printing on a windows server. This desktop service interfaces between the online service and the local service. 

You can check out the [node-escpos printer driver package ](https://github.com/song940/node-escpos) for some inspiration on how to go about this.

Check the [FAQs on how to print online](https://github.com/mike42/escpos-php/blob/development/doc/FAQ.md) to have some pointers too.
