### ISSUE TITLE
Printer PDF via WindowsPrintConnector error text

### ISSUE THREAD

**Issue by nuonveyo** [mike42/escpos-php#754]
i have try to print a PDF file via WindowsPrintConnector, unfortunately the result is different from  PDF file, bellow is my example code.

`$pdf = 'C:/wamp64/www/escpos-php/example/Untitleddocument.pdf';
$connector = new WindowsPrintConnector("smb://localhost/POS-80");
$printer = new Printer($connector);
try {
    $pages = ImagickEscposImage::loadPdf($pdf);
    foreach ($pages as $page) {
        $printer->graphics($page);
    }
    $printer->cut();
} catch (Exception $e) {
    /*
	 * loadPdf() throws exceptions if files or not found, or you don't have the
	 * imagick extension to read PDF's
	 */
    echo $e->getMessage() . "\n";

} finally {
    $printer->close();
}`

This is my PDF will form:
![Capture](https://user-images.githubusercontent.com/14009685/59154846-e3f17580-8aa5-11e9-92fa-0159b7e991d1.PNG)

This is my result after print:
![photo_2019-06-09_11-05-44](https://user-images.githubusercontent.com/14009685/59154881-8dd10200-8aa6-11e9-906a-1a013c105f07.jpg)

Help me please,

**Comment by mike42** [comment]
Hi @nuonveyo-

This command usually only works for Epson printers:

```php
$printer->graphics($page);
```

Try `$printer->bitImage()` or `$printer->bitImageColumnFormat()`. Also check your printer manual for the number of dots on a line, since you will also want to adjust the width of the image to match.

```php
$pages = ImagickEscposImage::loadPdf($pdf, 300);
```

The default is currently 550, which may be too wide or too narrow for your printer!
