### ISSUE TITLE
How it implement in laravel?

### ISSUE THREAD

**Issue by rahulwayanad** [mike42/escpos-php#756]
Is it possible to implement in laravel?

**Comment by mike42** [comment]
Yes. I'm not using this with Lavavel myself, but `escpos-php` is distributed as a `composer` package, and most modern PHP frameworks have a supported way of adding `composer` dependencies to use from your code.

Because we are a totally framework-agnostic library, we don't ship with any specific documentation or examples. I will assume that you already know how to get new PHP code running under your framework, so you'll need to make sure that you can `use Mike42\Escpos\Printer;`, and then the contents of the README apply all the same.

If you encounter any issues, then it would be appreciated if you can create a minimal example which can be run outside of Lavavel (eg. a command-line script), since it would be more applicable to the wider user-base.

**Comment by rahulwayanad** [comment]
Thanks michael. It's working in laravel

**Comment by gilson-reis** [comment]
@rahulwayanad 

Could you please explain how you implemented?

Thank you in advanced
