### ISSUE TITLE
thermal print using php

### ISSUE THREAD

**Issue by aleenaelizabethantony** [mike42/escpos-php#758]
I have already a pdf print .. how can I can it to thermal print?

**Comment by mike42** [comment]
PDF printing is not a good use case for this driver, since other tools can already work with that format. Instead, we provide a programmatic interface directly to the printer.

However, we do have a PDF printing example [here](https://github.com/mike42/escpos-php/blob/083f92d1dc0c808df42c6c5cd562f9f7d3a0d104/example/print-from-pdf.php), which uses ImageMagick in the background.

Best of luck!
