### ISSUE TITLE
Windows Server at Data Center, is there possible print receipt at client windows workstation printer?

### ISSUE THREAD

**Issue by gilbertlow** [mike42/escpos-php#76]
Hi,

Good day,

If our windows server is located at Data Center, is there a possibly to print receipt at client window workstation printer?

Thank you.

Regards
Gilbert

**Comment by mike42** [comment]
Hi,

Generally the server that is running `escpos-php` will need to be able to talk to the printer somehow.

Depending on how much control you have over the network and end-points, you may be able to set up a VPN or other secure tunnel so that your server can securely send data to the POS computers/printers on the client site.

Printing from the client side is possible with other drivers, such as [qz](https://qz.io), which seems to use a Java plugin to allow javascript code to print.
