### ISSUE TITLE
How to support on Zjiang 5802 Version?

### ISSUE THREAD

**Issue by hmstudio-developer** [mike42/escpos-php#776]
Thanks for code,
i want to ask, i use Zjiang mobile bluetooth printer 5802, and how to add my printer to this library? and how can step by step to use it?

thanks :)

**Comment by mike42** [comment]
Hi @hmstudio-developer, I'm not sure what you've tried at this stage, but the README is our best introductory document for the PHP side of things. We also have a 'POS-5890' [profile](https://github.com/mike42/escpos-php#using-a-capabilityprofile) which you can load, which was made for a different 58mm printer from this manufacturer.

We don't have any specific support for bluetooth, so _you will still need to find a way to get data to your printer_. On Linux, I would be aiming to access a bluetooth printer as a file, or add it to CUPS, so that either `FilePrintConnector` or `CupsPrintConnector` would be used to talk to the printer from PHP.
