### ISSUE TITLE
Hi, can it works with a tablet?

### ISSUE THREAD

**Issue by leonidelweb** [mike42/escpos-php#777]
I have to use a web app with google chrome app in the tablet. I want to know if I can configura printer POS wireless and to print from web page tablet.

Thanks :)

**Comment by juanPao** [comment]
Yes - it will work using your API.
No - if your printer is wireless/bluetooth.

**Comment by mike42** [comment]
Generally this library does not care whether the client is a tablet, a laptop, or a POS terminal. Since this is a PHP printing library, what matters most is **that you are running PHP somewhere which can see your printer**. It's not clear to me whether you are in fact developing a PHP app, so this may not help you, but may be useful for readers who may find this question from Google.

If you are a beginner, then start with a simple raw printing setup:

- Run PHP on the same LAN for LAN printers.
- Run it on localhost for USB/serial printers, or
- Run it on a Raspberry Pi within range of the device for bluetooth printers, etc.

With one of these setups, you can access your web app from any client, and this library can get data to your printer in a simple way (eg. via TCP, a file handle, or a print command on the PHP server), which is generally straightforward enough to debug.

There are also many possible setups for routing raw print jobs from the PHP server to the printer via intermediaries, but these can be quite fragile, and I generally don't recommend them because they generate a disproportinate amount of bug tracker traffic compared to the intended use of the library. Some such setups are listed [here](https://github.com/mike42/escpos-php/blob/5e904fed73704dcf22c4c4db2f31b329fb7a0b5f/doc/FAQ.md#can-i-print-from-my-server-on-the-internet).

PS: keep in mind that Chrome apps are being discontinued! (eg. I clossed [this printing project](https://github.com/receipt-print-hq/chrome-raw-print))

**Comment by leonidelweb** [comment]
> Generally this library does not care whether the client is a tablet, a laptop, or a POS terminal. Since this is a PHP printing library, what matters most is **that you are running PHP somewhere which can see your printer**. It's not clear to me whether you are in fact developing a PHP app, so this may not help you, but may be useful for readers who may find this question from Google.
> 
> If you are a beginner, then start with a simple raw printing setup:
> 
> * Run PHP on the same LAN for LAN printers.
> * Run it on localhost for USB/serial printers, or
> * Run it on a Raspberry Pi within range of the device for bluetooth printers, etc.
> 
> With one of these setups, you can access your web app from any client, and this library can get data to your printer in a simple way (eg. via TCP, a file handle, or a print command on the PHP server), which is generally straightforward enough to debug.
> 
> There are also many possible setups for routing raw print jobs from the PHP server to the printer via intermediaries, but these can be quite fragile, and I generally don't recommend them because they generate a disproportinate amount of bug tracker traffic compared to the intended use of the library. Some such setups are listed [here](https://github.com/mike42/escpos-php/blob/5e904fed73704dcf22c4c4db2f31b329fb7a0b5f/doc/FAQ.md#can-i-print-from-my-server-on-the-internet).
> 
> PS: keep in mind that Chrome apps are being discontinued! (eg. I clossed [this printing project](https://github.com/receipt-print-hq/chrome-raw-print))

Thanks so much for your answer. Have a nice day :)
