### ISSUE TITLE
Send Hexadecimal commands...

### ISSUE THREAD

**Issue by x1250** [mike42/escpos-php#78]
Hello Mike,

I just have a little question, I hope that you can help me. We have an Epson manual that has the HEX values to send to the printer for it to perform all sorts of different things. For example, the Epson manual says that the HEX values to use for cutting paper are: HEX: 07 02. How could I send this values to the printer using HEX?

Note: I know there is a method for cutting in your library, but actually we need to send HEX values for other commands.

Thank you for your time in responding.

**Comment by mike42** [comment]
Hey,

To send your own binary data to the printer, you would hook straight in to the `PrintConnector`.

Here's how the `Escpos` class generates the standard cut command-

````php
	const GS = "\x1d";
...
	/**
	 * Cut the paper.
	 *
	 * @param int $mode Cut mode, either Escpos::CUT_FULL or Escpos::CUT_PARTIAL. If not specified, `Escpos::CUT_FULL` will be used.
	 * @param int $lines Number of lines to feed
	 */
	function cut($mode = self::CUT_FULL, $lines = 3) {
		// TODO validation on cut() inputs
		$this -> connector -> write(self::GS . "V" . chr($mode) . chr($lines));
	}
````

So to send hex values 07 02 to a printer, you could do something like this-

````php
// Generate string using hex values for the characters:
$myCoolCommand = "\x07\x02";
// Alternatively..
$myCoolCommand = chr(0x07) . chr(0x02);

// Send it off
$connector = new NetworkPrintConnector("10.x.x.x", 9100);
$printer = new Escpos($connector);
$printer -> text("Hello World!\n");
$connector -> write($myCoolCommand);
$printer -> close();
````

If you implement commands that work on common printers, then please send a code snippet or pull request so that they can be included in the main project.
