### ISSUE TITLE
Printer ZJ-8330

### ISSUE THREAD

**Issue by 87rohit** [mike42/escpos-php#782]
Hello Mike
I have a printer ZJ-8330 can you please add this printer in your code.
Here is the full detail of the printer: http://www.zjiang.com/en/init.php/product/index?id=42

Thanks
Rohit

**Comment by mike42** [comment]
You should be able to work with this printer already by loading either the `simple` or `POS-5980` [CapabilityProfile](https://github.com/mike42/escpos-php/tree/5e904fed73704dcf22c4c4db2f31b329fb7a0b5f#using-a-capabilityprofile). However, nobody has tested it yet, which is why it's not listed in the README.

For some more detail, take a look at ["I have Printer X. Can I use this driver?"](https://github.com/mike42/escpos-php/blob/5e904fed73704dcf22c4c4db2f31b329fb7a0b5f/doc/FAQ.md#i-have-printer-x-can-i-use-this-driver) in the FAQ.
