### ISSUE TITLE
Issues to print from Online POS website in my local server

### ISSUE THREAD

**Issue by awais33** [mike42/escpos-php#784]
I want a guidance to help me in setting up the mike42/escpos-php library with online POS website without printer

can any one help me to solve the issue in php. I have Point of sale website in online server. I connect the print recipt code which is in my local server with this point of sale. but print is not working. I used the mike42/escpos-php library from github https://github.com/mike42/escpos-php.

The following errors occoured whrn i click on print button.

1: Warning: copy(\\DESKTOP-L48VCRS\EPSON TM-U220 CAJA): failed to open stream: No such file or directory in C:\wamp64\www\sistema\src\Mike42\Escpos\PrintConnectors\WindowsPrintConnector.php on line 372

2: Fatal error: Uncaught Exception: Failed to copy file to printer in C:\wamp64\www\sistema\src\Mike42\Escpos\PrintConnectors\WindowsPrintConnector.php on line 291

3: Exception: Failed to copy file to printer in C:\wamp64\www\sistema\src\Mike42\Escpos\PrintConnectors\WindowsPrintConnector.php on line 291

The online website or POS url is

http://dfathers.es

Please any one help me to solve the issues.

thanks

**Comment by WilsonicX** [comment]
Amigo cual es tu problema? veo que estas colocando una direccion fisica de windows veo que tu sitio esta en español cualquier cosa me escribes

**Comment by mike42** [comment]
@awais33 - PHP must be able to see your printer for this to work. If it can't connect and print, then this library will not be useful to you.

Luckily, this can be tested without PHP, have you tried troubleshooting on the command-line? This is mentioned in `windows-usb.php` [here](https://github.com/mike42/escpos-php/blob/10b1230ba6875ac189f1f79b9e2de91a633c06b3/example/interface/windows-usb.php#L13-L18), and I have a longer blog post [here](https://mike42.me/blog/2015-04-getting-a-usb-receipt-printer-working-on-windows).

**Comment by Okiki2016** [comment]
I had a similar problem before. If you have not found a solution get back we can help you on a work arround. But basically you have to make sure the printer works normally before using Mike42 library

**Comment by mike42** [comment]
Issue seems to be abandoned, closing it off.

**Comment by mutiemule** [comment]
Printing on local will work well with this package.

However, to print online, you will need to develop a desktop service which has to be installed on the local computer where you need printing to be done.  This is because PHP is a server-side scripting language, so once you put this online, it won't be able to communicate to the local printer. Thus, you need a client service running on the local machine and this is where electron js and node js come into play.

I resolved this by developing an electron js service based on [node-escpos package](https://www.npmjs.com/package/escpos) which can receive commands from the online print command and then communicate those commands to the printer through USB. 

Operating System does not matter in this case, you can be hosting on Linux based server and printing on a windows server. This desktop service interfaces between the online service and the local service. 

You can check out the [node-escpos printer driver package ](https://github.com/song940/node-escpos) for some inspiration on how to go about this.

Check the [FAQs on how to print online](https://github.com/mike42/escpos-php/blob/development/doc/FAQ.md) to have some pointers too.
