### ISSUE TITLE
BitImage Slow

### ISSUE THREAD

**Issue by caydenliew** [mike42/escpos-php#8]
Hi Mike,

Thanks for sharing the code, it works well except i'm having issue when printing image with bitImage. The image can be printed out nicely but very slow, can i know is there anyway to speed up the printing, any adjustment need to be done on the image?

**Comment by mike42** [comment]
Hello,

Glad to hear it works So that I can answer this better, could you add some extra info about your setup?
- What model printer are you using?
- How is it connected? (USB/Ethernet/Parallel/Serial)
- What is the resolution of the image? (so check it against memory limits for your printer)
- Is the delay before it is printing, or while it is printing? (A video of the printer running bit-image.php would answer this)
- Is graphics() supported on your printer, and does it have the same effect?

There are three phases to printing: arranging the binary data in PHP (CPU bound), sending it to the machine (I/O bound), and then the actual printing (Print speed bound). With the information above, we may be able to figure out which one is slowing your printing down here.

**Comment by caydenliew** [comment]
Hi Mike,

1. The model is Partner-Tech RP-320 thermal printer. Printing speed 200mm/sec in text printing ; 160mm/sec in graphic printing.
2. The printer is connected using SerialPort
3. Resolution of image is 500x260 px, 72dpi
4. The delay is during printing. The printing started and the paper come out slowly while printing image, then speed up when printing text. (https://youtu.be/C9GhRSsOI_s)
5. graphics() not supported on my printer. Funny characters printed out when use graphics().

Thanks.

**Comment by mike42** [comment]
Hm. This is different print behaviour to what I've seen on tests connected over faster links - it seems to be printing the data as it comes in- I suspect the bottleneck is the serial I/O.

The first thing I would do is roughly halve the image dimensions in both directions, down to a _height which is a multiple of 24_ (500x260 px -> 246x128 px), and then print using the double-size. This results in 75% less data to process, at the cost of a more pixellated image.

From  `bit-image.php`:

    $printer -> bitImage($tux, Escpos::IMG_DOUBLE_WIDTH | Escpos::IMG_DOUBLE_HEIGHT);

Some planned future commands, named "download bit image" and "NV bit image" will allow you to upload a picture and then re-use it, so that it doesn't need to be sent each time- I suspect that your 160mm/sec is based on NV graphics, as it's generally the speediest graphics source.

I'll be experimenting with these more again after UTF-8 input is added (the current task), but my last implementation wasn't useful enough for inclusion in the driver.

**Comment by mike42** [comment]
Closing this one, I don't think any other tips can be added until NV graphics are available.
