### ISSUE TITLE
sending raw data in json

### ISSUE THREAD

**Issue by ahmedali5530** [mike42/escpos-php#827]
Hello!
I want the raw data for printing from javascript, i need the raw binary data from escpos files (i already made with escpos-php), how can i send it back to my javascript page because json_encode is not working here.
Any solutions?

**Comment by Muraveiko** [comment]
https://rawbt.ru/mike42/example_rawbt/ - Solution from me.
You may take only idea with base64 encode

**Comment by ahmedali5530** [comment]
> https://rawbt.ru/mike42/example_rawbt/ - Solution from me.
> You may take only idea with base64 encode

Thanks
It is working fine, but i m getting some garbage data (commas, spaces) along with raw data, how to prevent that data from coming?

**Comment by Muraveiko** [comment]
https://github.com/mike42/escpos-php/blob/development/src/Mike42/Escpos/PrintConnectors/RawbtPrintConnector.php#L55

This command resets garbage that might get into the output from the program code due to errors. Those. Further, only data added by you specifically for output is encoded.
If there is garbage in the data, then it arose already in javoscripts.
I wonder how you send data from javoscript to the device. I do not know simple ways without intermediary programs.

**Comment by ahmedali5530** [comment]
> https://github.com/mike42/escpos-php/blob/development/src/Mike42/Escpos/PrintConnectors/RawbtPrintConnector.php#L55
> 
> This command resets garbage that might get into the output from the program code due to errors. Those. Further, only data added by you specifically for output is encoded.
> If there is garbage in the data, then it arose already in javoscripts.
> I wonder how you send data from javoscript to the device. I do not know simple ways without intermediary programs.

I am using websockify

1. made a binary from [novnc/websockify](https://github.com/novnc/websockify)
2. created a local socket server using `websockify.exe someport --token-plugin TokenFile --token-source /path-to-tokens-directory/`
3. then in javascript i made a new connection of `WebSocket('ws://localhost:someport/?target=some-target-specified-in-targets-file', ['base64'])`
4. then sending base64 encoded data to printer

All is working fine

**Comment by ahmedali5530** [comment]
> https://github.com/mike42/escpos-php/blob/development/src/Mike42/Escpos/PrintConnectors/RawbtPrintConnector.php#L55
> 
> This command resets garbage that might get into the output from the program code due to errors. Those. Further, only data added by you specifically for output is encoded.
> If there is garbage in the data, then it arose already in javoscripts.
> I wonder how you send data from javoscript to the device. I do not know simple ways without intermediary programs.

`return_data.replace('\\', '')` does the job.
It removes the garbage data from response.

**Comment by mike42** [comment]
@ahmedali5530 - I think if there is a find/replace in there, then it sounds very suspect.

If you might consider an alternative implementation, I used socat + websockify on Linux to prototype this about 2 years ago.

The idea was to `GET` the binary data from the server over HTTP, then throw it down a (binary) websocket which has some agent which can pass it to the printer.

- Blog post: [How to communicate with USB and networked devices from in-browser Javascript](https://mike42.me/blog/2018-04-how-to-communicate-with-usb-and-networked-devices-from-in-browser-javascript).
- Client-side code: [mike42/escpos-snippets](https://github.com/mike42/escpos-snippets/tree/master/js-binary-websocket-demo).

The server side you just need to send a file. Borrowing from some earlier examples on the issue tracker, it's something like this-

```php
<?php
require __DIR__ . '/../vendor/autoload.php';

use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\DummyPrintConnector;

$connector = new DummyPrintConnector();
$printer = new Printer($connector);
$printer -> text("Hello World\n");
$data = $connector -> getData();
$printer -> close();

// If no exceptions have been thrown, then output
header('Content-type: application/octet-stream');
header('Content-Length: '.strlen($data));
echo $data;
?>
```

Note:

- No JSON or base64 involved.
- I would suggest you look into converting warnings to exceptions if you are worried about output, since you can pick them up and return a `5xx` HTTP response to indicate a problem. `ob_` is a bit of a blunt instrument, and you will have a hard time debugging if you are actively suppressing throwing away errors. 

On the client side, you need to get the response as an `arraybuffer`

```js
var req = new XMLHttpRequest();
req.open("GET", "/foobar.php", true);
req.responseType = "arraybuffer";
req.onload = function (oEvent) {
  var arrayBuffer = req.response; // Note: not req.responseText
  // TODO check the response code, use the data
};
// TODO some error handling is always a good idea
req.send(null);
```

**Comment by Muraveiko** [comment]
https://github.com/402d/rawbt_ws_server
Yesterday did. There is a problem with the documentation, since I do not know English well. Console application. One phar file & one json config. 
For exchange uses base64 encoding.

**Comment by ahmedali5530** [comment]
> @ahmedali5530 - I think if there is a find/replace in there, then it sounds very suspect.
> 
> If you might consider an alternative implementation, I used socat + websockify on Linux to prototype this about 2 years ago.
> 
> The idea was to `GET` the binary data from the server over HTTP, then throw it down a (binary) websocket which has some agent which can pass it to the printer.
> 
> * Blog post: [How to communicate with USB and networked devices from in-browser Javascript](https://mike42.me/blog/2018-04-how-to-communicate-with-usb-and-networked-devices-from-in-browser-javascript).
> * Client-side code: [mike42/escpos-snippets](https://github.com/mike42/escpos-snippets/tree/master/js-binary-websocket-demo).
> 
> The server side you just need to send a file. Borrowing from some earlier examples on the issue tracker, it's something like this-
> 
> ```
> <?php
> require __DIR__ . '/../vendor/autoload.php';
> 
> use Mike42\Escpos\Printer;
> use Mike42\Escpos\PrintConnectors\DummyPrintConnector;
> 
> $connector = new DummyPrintConnector();
> $printer = new Printer($connector);
> $printer -> text("Hello World\n");
> $data = $connector -> getData();
> $printer -> close();
> 
> // If no exceptions have been thrown, then output
> header('Content-type: application/octet-stream');
> header('Content-Length: '.strlen($data));
> echo $data;
> ?>
> ```
> 
> Note:
> 
> * No JSON or base64 involved.
> * I would suggest you look into converting warnings to exceptions if you are worried about output, since you can pick them up and return a `5xx` HTTP response to indicate a problem. `ob_` is a bit of a blunt instrument, and you will have a hard time debugging if you are actively suppressing throwing away errors.
> 
> On the client side, you need to get the response as an `arraybuffer`
> 
> ```js
> var req = new XMLHttpRequest();
> req.open("GET", "/foobar.php", true);
> req.responseType = "arraybuffer";
> req.onload = function (oEvent) {
>   var arrayBuffer = req.response; // Note: not req.responseText
>   // TODO check the response code, use the data
> };
> // TODO some error handling is always a good idea
> req.send(null);
> ```

Hi @mike42 i am using `DummyPrintConnector` and modified the code to get the output according to my requirement
`
public function getData() {
    ob_start();
    echo implode(',', $this->buffer);
    $contents = ob_get_contents(); 
    ob_end_clean();

    return str_replace([','], '', $contents);
}
`
this way i can get the clean output and the using `base64_encode` after that i can return as normal `json`. Everything(text, spacing, images) is working fine.

**Comment by Muraveiko** [comment]
It was enough
return base64_encode(implode($this -> buffer));

**Comment by ahmedali5530** [comment]
> It was enough
> return base64_encode(implode($this -> buffer));

I tried that, but as i mentioned earlier this includes some garbage data with original data, so i get the data from output buffering and removed commas.
