### ISSUE TITLE
Can not print logo with start printer

### ISSUE THREAD

**Issue by BaiMaoLi** [mike42/escpos-php#828]
I've purchased start printer and tried to print receipt with logo.
But it is not working.
If i print logo, then it is printing really stranging charset.
Please help me if anyone have idea.

**Comment by mike42** [comment]
Hi, could you please share the exact brand/model of printer?

We need to firstly check that it understands ESC/POS, and then select a `CapabilityProfile` exists which might allow the library to avoid the issue.

You might also like to try replacing `$printer -> graphics()` with `$printer -> bitImage()` in the example and try again -- `graphics()` only works with Epson ESC/POS printers, and the library assumes that you have an Epson printer unless you tell it otherwise.
