### ISSUE TITLE
PRINTING FROM ANDROID HANDHELD E-POS DEVICE

### ISSUE THREAD

**Issue by Okiki2016** [mike42/escpos-php#831]
Hi Mike,

Thank you for the wonderful script. I have been able to print from web to a local ESC/POS USB thermal printer connected on windows. **But I have an issue here that I need assistance;**

I have an iMachine EPos Android thermal printer. I am trying to print directly from the web. The printer works just fine with normal print but, I am wondering whether there is a way I can print like in the usb print environment.

Also if Anyone has done this please respond to my rescue.

**Comment by mike42** [comment]
It's a bit far-removed from this library, but you may like to see if `rawbt` works in your setup. One of the developers contributed a connector and example ([link](https://github.com/mike42/escpos-php/blob/be3027977e6a333c56727b5dfba383adc79f7beb/example/rawbt-receipt.php)) so that it can be used from PHP. It posts data to an android app via an 'intent' (called from a web page), which then passes it to the printer, since apps can access bluetooth etc.

Disclaimer: This is a third-party product, and I cannot vouch for it's quality.
