### ISSUE TITLE
Print php code instead data

### ISSUE THREAD

**Issue by jerrydomm** [mike42/escpos-php#836]
Hi, print from web only send php code:

![print](https://user-images.githubusercontent.com/13666536/68730584-b51a8680-0592-11ea-9d4f-738e81ee40f3.jpeg)

How covert php code to real data?

Thank's for the help!

**Comment by mike42** [comment]
That text is PostScript, not PHP. This library does not produce PostScript, so it's safe to say that this output is not being produced by `escpos-php`.

In order to use this library, then the server running PHP must be able to see your printer, and it will send ESC/POS data to it. This is often known as "raw printing". Transport mechanisms which can be used from PHP are listed in [the README](https://github.com/mike42/escpos-php/blob/development/README.md).

I can most likely point you in the right direction if you can explain your setup, including the operating systems involved, and _how you have verified that the server running PHP can get raw data to your printer_. If PHP can't perform raw printing in your setup, then this library is unlikely to be useful to you.
