### ISSUE TITLE
(request fix) Imagick trim blank space on footer

### ISSUE THREAD

**Issue by mean-cj** [mike42/escpos-php#839]
Hello , thank you for your great project

when i print the pdf , if any pdf is empty footer  then printer print empty space.

please fix Imagick by trim method
mike42\escpos-php\src\Mike42\Escpos\ImagickEscposImage.php

```
  public function readImageFromImagick(Imagick $im)
  {
    /* Strip transparency */
    $im = self::alphaRemove($im);
    /* Threshold */
    $im->setImageType(Imagick::IMGTYPE_TRUECOLOR); // Remove transparency (good for PDF's)
    $max = $im->getQuantumRange();
    $max = $max["quantumRangeLong"];
    $im->thresholdImage(0.5 * $max);

    $dimmensions = $im->getImageGeometry();
    $height = $dimmensions['height'];
    if ($im->trimImage($max * 0.1)) {
      $im->borderImage('#ffffff', 0, $height * 0.05); // add white border with 5% of offset
    }
   ...
```

I will test is ok

![20191120_015227](https://user-images.githubusercontent.com/1191385/69176832-0dc0c500-0b39-11ea-863b-161c9d0469bb.jpg)

**Comment by mike42** [comment]
I did some testing on how margins are treated currently, and while I appreciate the suggestion, I won't be applying this change.

It looks like the library already respects the spacing of the PDF, then scales the page horizontally and drops it on the receipt in black & white quite well.

I have a preference not to second-guess the developer when they try to print a file with a lot of whitespace, because it keeps things simple and flexible on our end. For example, this change would cause some difficulty for users in ticket printing scenarios, because tickets should all be the same size regardless of content.

### Test 1: Files with no whitespace

I created a small PDF ([testing.pdf](https://github.com/mike42/escpos-php/files/3953701/testing.pdf)) in LibreOffice which looks like this:

![image](https://user-images.githubusercontent.com/2080552/70680817-6e34c380-1ced-11ea-8b04-2eccd9b25acf.png)

I then printed it out and converted it back to HTML with escpos-tools:

```php
<?php
require __DIR__ . '/vendor/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\ImagickEscposImage;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;

$connector = new FilePrintConnector("php://stdout");
$printer = new Printer($connector);
$pages = ImagickEscposImage::loadPdf("testing.pdf");
foreach ($pages as $page) {
    $printer -> graphics($page);
}
$printer -> cut();
$printer -> close();
```

```bash
php pdf-spacing.php  > testing.bin
php ../escpos-tools/esc2html.php testing.bin  > testing.html
```

And a HTML inspect shows that we got the whitespace correct around the image.

![bitimage](https://user-images.githubusercontent.com/2080552/70680937-c53a9880-1ced-11ea-8878-601c4091d3ff.png)

### Test 2: Files with whitespace

If you have an image with whitespace, then it will be preserved too. Eg. the same procedure with a taller PDF file ([link](https://github.com/mike42/escpos-php/files/3953723/testing2.pdf)):

![image](https://user-images.githubusercontent.com/2080552/70681389-4d6d6d80-1cef-11ea-9475-a4d95502621f.png)

This is the output we would see on the printer:

![Screenshot from 2019-12-12 14-53-18](https://user-images.githubusercontent.com/2080552/70681333-2a42be00-1cef-11ea-9d89-e5ce8577b2c5.png)
