### ISSUE TITLE
autoload.php missing for examples

### ISSUE THREAD

**Issue by kingdg25** [mike42/escpos-php#847]
no /../../vendor/autoload.php in examples

**Comment by liammizrahi** [comment]
You must download the vendor with composer

**Comment by mike42** [comment]
Since version 3, [composer](https://getcomposer.org/) must be used to install `escpos-php`.

The path is correct for users who do this:

```bash
git clone git@github.com:mike42/escpos-php.git
cd escpos-php
composer install
```

The `composer install` command produces the file which you are missing.

To run the examples from your own project, you will need to copy in the example and adjust the path.
