### ISSUE TITLE
Cash drawer on ZJ-5890T

### ISSUE THREAD

**Issue by mcules** [mike42/escpos-php#88]
Hi,

i tried to open a cash drawer connected to a ZJ-5890T.
After some testing, i cant get it to work. Anyone has this setup working?

**Comment by mike42** [comment]
Hi,

Can you share which arguments you've tried on `pulse()`, and a link to any online documentation which I can use to see which commands are supported on your printer?

- Here is a C code snippet which claims to be able to open cash drawers on a similar printer, which issues commands to pins identified as 0 and 1, rather than 48, 49 as in `escpos-php`. See https://github.com/klirichek/zj-58/blob/master/rastertozj.c
- I've almost made this change before, and I can put it through if you'd like to test the change-set. See issue #2.

**Comment by mcules** [comment]
Hi mike42 and thank you for your'e answer.
I'm checking this later and give a reply.

**Comment by mcules** [comment]
Here is a link to the documentation: https://www.dropbox.com/s/9crmevyfgfqovow/58MMPrinter%20Programmer%20Manual-20150312.pdf?dl=0

**Comment by mcules** [comment]
Okay, tryed it with:

$fp = new FilePrintConnector('/dev/usb/lp0');
$printer = new Escpos($fp);
$printer->pulse();
$printer->pulse(1);
$printer->pulse(0, 100, 100);
$printer->pulse(0, 300, 300);
$printer->pulse(1, 100, 100);
$printer->pulse(1, 300, 300);

but the drawer didn't opened :(
I'm already using the driver from https://github.com/klirichek/zj-58

**Comment by mike42** [comment]
I've updated command in the `88-pulse-pins` branch, it may be worth re-testing. The documentation you linked to says that both are supported, so I'm not expecting a difference. Have you got all other commands working (formatting, text output etc)?

````
composer require mike42/escpos-php:dev-88-pulse-pins
OR
git clone -b 88-pulse-pins https://github.com/mike42/escpos-php
````

Your printer also implements a real-time pulse command. See what happens if you run this:

````
<?php
require __DIR__ . '/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;
$connector = new FilePrintConnector('/dev/usb/lp0');
$printer = new Printer($connector);

// Regular pulse
$printer->text("Regular pulse...\n");
$printer->pulse();
sleep(1);
$printer->pulse(1);
sleep(1);
$printer->pulse(0, 100, 100);
sleep(1);
$printer->pulse(0, 300, 300);
sleep(1);
$printer->pulse(1, 100, 100);
sleep(1);
$printer->pulse(1, 300, 300);
sleep(1);

// See what 'real-time pulse' does??
$printer->text("Real-time pulse!\n");
foreach(range(0, 1) as $m) {
	foreach(range(1,8) as $t) {
		$n = 1;
		$printer->text("\$m: $m, \$t: $t\n");
		$connector->write(Printer::DLE . "\x14" . chr($n) . chr($m) . chr($t));
		sleep(1);
	}
}

$printer->text("Done\n");
$printer->close();
````

**Comment by mcules** [comment]
Your code opens the drawer one time, and then not again.
I have to restart the system to open again.

Im just confused ^^

**Comment by mike42** [comment]
That snippet sends 14 different pulses.
- Which one works?
- If you send some `text("\n")` and a working pulse only, wait a moment, and some more `text("\n")` and a working pulse, then can you open the drawer twice?

**Comment by ksidibe** [comment]
I'm running into a similar problem with the ZJ 5890T POS thermal printer. The drawer is not opening at all. I ran the test script you provided earlier. But it did not work.
Any suggestions?
Thanks.

**Comment by tahelromero** [comment]
I have an Hasar 250 and the Drawer do not open also
