### ISSUE TITLE
Zebra iMZ320

### ISSUE THREAD

**Issue by JkoEntrepreneur** [mike42/escpos-php#884]
Tener en cuenta esta impresora.
Muchas gracias por tus paortes.

Saludos

**Comment by mike42** [comment]
I don't speak Spanish, but there is Google Translate. :)

Somebody recently asked for Zebra ZT230 support at #905, and it is the same story with the Zebra iMZ320. The output of this library is ESC/POS, which is not compatible with these printers.

I would encourage you to search for PHP projects which produce ZPL (compatible with Zebra printers) as an alternative, because I am not currently planning to expand the scope of this project to include other print languages.
