### ISSUE TITLE
Error NT_STATUS_UNSUCCESSFUL

### ISSUE THREAD

**Issue by potawas** [mike42/escpos-php#908]
Hello,

I can easily connect to my xprinter in localhost and also from nginx with      
       $connector = new WindowsPrintConnector("smb://MYLAPTOP/MYPRINTER");

But with my new Linux VPS I have this error : 
Connection to MYLAPTOP failed (Error NT_STATUS_UNSUCCESSFUL)

Does anyone know why ?

**Comment by mike42** [comment]
Hello,

Most likely your Linux server cannot see your laptop, because of NAT'ing and firewalls and other such things (all of which are there for good reasons).

This library is designed for situations where your server (where PHP runs) can see your printer. Common solutions are to bring printing inside your LAN (eg. dropping a Raspberry Pi on the same network as your printer and running a web server on it), or extending your LAN to include the server (via VPN or similar).

There is a [section of the FAQ](https://github.com/mike42/escpos-php/blob/5e904fed73704dcf22c4c4db2f31b329fb7a0b5f/doc/FAQ.md#can-i-print-from-my-server-on-the-internet) which covers this issue, as it's quite a common trap for new users.
