### ISSUE TITLE
How do I print from Android browser?

### ISSUE THREAD

**Issue by omkaruthale** [mike42/escpos-php#91]
Hello Mike,

I am developing a Web POS solution which will run over android browser. I need to print receipt from that web solution but I am not intending to use any PC for it.

Will it be possible to do so?

Regards,
Omkar

**Comment by mike42** [comment]
Hi,

To use this print driver in your web app, you would need PHP running on a computer someplace, and that computer must be able to communicate with the receipt printer (ie, Android won't do the printing, it will just sent a HTTP request off to a server which will do the printing)

The details of how you connect this up will depend on what sort of equipment you have, but you might consider-
- An app hosted internally, connecting to printers over ethernet.
- An app hosted on the public internet, with a VPN or tunnel to access a print server on the inside
- An app which provides an API out in public internet, but a web-page displayed locally (hosted on a Raspberry Pi or embedded PC), so that data is shared between stores but printing is always done locally.
