### ISSUE TITLE
Equal IT80-002 doesn't align or resize images

### ISSUE THREAD

**Issue by franvera** [mike42/escpos-php#96]
setJustification ignored when printing Images. Double width and hight images only print the first half of the image.

It ignores the next command after printing an image unless \n is sent, that could be a sign of something?
Using bitImage() as graphics() and qr() print random text.

```php
require_once(dirname(__FILE__) . "/vendor/autoload.php");

use Mike42\Escpos\Printer;
use Mike42\Escpos\EscposImage;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;

$connector = new FilePrintConnector(exec("ls /dev/usb/lp*"));
$printer = new Printer($connector);

/* Initialize */
$printer -> initialize();

$printer -> setJustification(Printer::JUSTIFY_LEFT);
$printer -> text("Left\n");
$logo = new EscposImage(dirname(__FILE__) . "/center.jpg");
$printer -> bitImage( $logo );

$printer -> setJustification(Printer::JUSTIFY_RIGHT);
$printer -> text("Right\n");
$logo = new EscposImage(dirname(__FILE__) . "/test.jpg");
$printer -> bitImage( $logo );

$printer -> setJustification( Printer::JUSTIFY_RIGHT );
$printer -> selectPrintMode( Printer::MODE_DOUBLE_WIDTH | Printer::MODE_DOUBLE_HEIGHT );
$printer -> text("Center Double\n");
$logo = new EscposImage(dirname(__FILE__) . "/test.jpg");
$printer -> bitImage( $logo , Printer::IMG_DOUBLE_WIDTH | Printer::IMG_DOUBLE_HEIGHT );

//Doesn't cut unless a \n is sent??
$printer -> text("\n");

$printer -> cut();
$printer -> close();


```
![ticket5](https://cloud.githubusercontent.com/assets/4934622/13828195/fdf2e4d6-eb85-11e5-8bb5-9a319574da63.jpg)

Thanks for the help!

**Comment by mike42** [comment]
I'd expect these to align, but not resize (There's a second argument to the image print commands which can double the height or width)

Can you post a link to any vendor documentation which might shed some light on what the printer supports, attempt to run using `bitImageColumnFormat()`, and post the snippet you've run so that I can compare?

**Comment by franvera** [comment]
Thanks Mike,

I have updated the initial comment with code and another image showing the result.

this is the documentation sent to me when complained about this issue:

[80XX Programmer_Manual(latest version).pdf](https://github.com/mike42/escpos-php/files/176876/80XX.Programmer_Manual.latest.version.pdf)

**Comment by mike42** [comment]
See also python-escpos/python-escpos#109

**Comment by franvera** [comment]
Thanks @mike42 , I created that issue too. This is of course printer specific. After trying many things I hoped someone could think of something else that might make it work on this printer. I have attached the vendor's documentation but as @DavisGoglin commented on the python issue, it's the same as Epson's. Any help is very much appreciated!

**Comment by mike42** [comment]
More suggestions-

- I see in the manual that your printer also supports `ESC *`, so please also try `bitImageColumnFormat()` (Same method signature as `bitImage()`). The output for `ESC *` is actually inline, so it tends to behave a lot more like text.
- Left-pad the images with white-space before use.

**Comment by franvera** [comment]
Thanks @mike42 , I updated the code and bitImageColumnFormat() aligns and resizes the image correctly! Thank you very much for your help!!

**Comment by franvera** [comment]
One quick comment @mike42 , when using IMG_DOUBLE_WIDTH | IMG_DOUBLE_HEIGHT mode, the image does get bigger but the height gets a bigger scale making a square's height about 1.5 times the width. Tested with different image sizes and the problem persists.

**Comment by mike42** [comment]
Yep, these are badly named for historical reasons.

The stretched output options will be renamed to "high density vertical = False / high density horizontal = False" in a future version, because the height is multiplied by three with this command (8 pixels per row in low density vs 24 pixels per row in high density), while on other commands, the height is actually doubled.

You will need to either
- print with `bitImage()` (forego centre-alignment)
- double the size in an image editor first and print in high density (a bit slower)
- size the image down by 1/3 vertically in an image editor before printing at low density (compensating for the image being printed at a different aspect ratio)
