### ISSUE TITLE
Test the printing of a ticket without a printer?

### ISSUE THREAD

**Issue by diquispe** [mike42/escpos-php#989]
There is the possibility to test the printing of a ticket without having the printer physically present, to prove that the printing is being done correctly in the right size and amount of characters.

or if there is the possibility to send the ticket by console only for development purposes

**Comment by JavierPAYTEF** [comment]
This would be awesome to have, but not sure if there is any project in any language that converts ESC/POS to a visible image (like a preview) without using a printer. I've been searching something like this since forever and, I don't know if I'm using the wrong search terms, but the only thing I find is how to print images using escpos.
One thing you can do if you don't have a printer and want to use it for testing is to install a "Virtual printer" in your computer. You can probably find one in google or maybe use RedMon to redirect traffic from any printer to a file.

**Comment by JavierPAYTEF** [comment]
There is also this issue #797, escpos-php has a way to directly print to a file and then you can use https://github.com/receipt-print-hq/escpos-tools to convert the esc pos to html.

**Comment by Muraveiko** [comment]
https://github.com/402d/Virtual_POS_printer

If you have an android smartphone, then my program can emulate a network printer.
https://www.youtube.com/watch?v=TxQJMpp7UIg

**Comment by mike42** [comment]
+1 for escpos-tools. It's related to this project, and is also a community-developed open source project.

If you find any ESC/POS that it can't understand properly, then you can attach it to an issue on GitHub so that we can track it. :)

I'll close this as answered.

**Comment by abanghendri** [comment]
I use escpos-tools and I can convert escpos .bin file to html
but I wonder how to output print file to .bin file instead of printing to printer for testing?

**Comment by grzesl** [comment]
There is few tools available for printout emulation. One is SoftPrintMe for iOS and Mac witch work like network printer. https://softprint.me
